# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Adapted from the ::guru ebuild (amd64), which vendors its frontend
# node_modules as a single prebuilt, x86_64-only tarball. That tarball's
# @rollup/rollup-linux-*, @esbuild/*, and @tauri-apps/cli-linux-* optional
# native npm packages are x86_64-gnu builds only, so `npm run build` fails
# on arm64 with "Cannot find module @rollup/rollup-linux-arm64-gnu". This
# arm64-only ebuild instead fetches the exact linux/arm64/glibc npm
# dependency closure individually from registry.npmjs.org and assembles
# node_modules from those distfiles in src_prepare, so no network access
# is needed during src_compile and no prebuilt vendor blob needs to be
# hosted for arm64.
#
# The dependency closure below is locked from
# files/restic-browser-0.3.3-vaadin-23.3.25-package-lock.json.gz
# (gzipped to stay under pkgcheck's files/ size thresholds), NOT
# upstream's own package-lock.json: it pins the 24 @vaadin/* packages
# that upstream's unpinned "^23.3" range would otherwise resolve to a
# commercially licensed release (see the RESTIC_BROWSER_NPM_SRC_URI and
# LICENSE comments below). That same committed file is installed
# (decompressed) over the stock package-lock.json in src_prepare, so the
# prepared source tree, this ebuild's arrays, and the file used to
# regenerate them are always one consistent lockfile, not three copies
# that could drift apart.
#
# Regenerate the dependency arrays below with:
#   scripts/generate-restic-browser-npm-deps.py 0.3.3 \
#     app-backup/restic-browser/files/restic-browser-0.3.3-vaadin-23.3.25-package-lock.json.gz out.gen
# The generator itself refuses to emit an entry for any package whose
# lockfile-recorded license is a URL (the pattern proprietary licenses
# use, including Vaadin's), so pointing it at a fresh, unpinned lockfile
# fails loudly instead of producing a mislicensed ebuild.

EAPI=8

CRATES="
"

declare -A GIT_CRATES=(
	[fix-path-env]='https://github.com/tauri-apps/fix-path-env-rs;8481725b7ebfc56cdb052d522517421242eac36b;fix-path-env-rs-%commit%'
)

RUST_MIN_VER="1.82.0"

inherit cargo desktop xdg

DESCRIPTION="A GUI to browse and restore from restic backup repositories"
HOMEPAGE="https://github.com/emuell/restic-browser"

# Generated by scripts/generate-restic-browser-npm-deps.py; do not edit.
# Locked linux/arm64/glibc npm dependency closure: 63 packages
RESTIC_BROWSER_NPM_DEPS_VERSION="0.3.3"
#
# The 24 commercially-relicensed @vaadin/* packages (see LICENSE comment
# below) are pinned here to 23.3.25 -- the exact version upstream itself
# used in its v0.3.0 release, still Apache-2.0 -- overriding package.json's
# own "^23.3" range, which npm would otherwise resolve to 23.6.1 (commercial
# since 23.5.0). Verified compatible with 0.3.3's actual source: a real
# `npm run build` against this pinned tree type-checks and bundles cleanly,
# and the resulting Tauri binary renders its Vaadin-based UI correctly
# under Xvfb (see scripts/README.restic-browser.md).
RESTIC_BROWSER_NPM_SRC_URI=(
	"https://registry.npmjs.org/@adobe/lit-mobx/-/lit-mobx-2.2.2.tgz -> restic-browser-npm-adobe-lit-mobx-2.2.2.tgz"
	"https://registry.npmjs.org/@esbuild/linux-arm64/-/linux-arm64-0.25.10.tgz -> restic-browser-npm-esbuild-linux-arm64-0.25.10.tgz"
	"https://registry.npmjs.org/@lit-labs/ssr-dom-shim/-/ssr-dom-shim-1.4.0.tgz -> restic-browser-npm-lit-labs-ssr-dom-shim-1.4.0.tgz"
	"https://registry.npmjs.org/@lit/reactive-element/-/reactive-element-1.6.3.tgz -> restic-browser-npm-lit-reactive-element-1.6.3.tgz"
	"https://registry.npmjs.org/@open-wc/dedupe-mixin/-/dedupe-mixin-1.4.0.tgz -> restic-browser-npm-open-wc-dedupe-mixin-1.4.0.tgz"
	"https://registry.npmjs.org/@polymer/iron-flex-layout/-/iron-flex-layout-3.0.1.tgz -> restic-browser-npm-polymer-iron-flex-layout-3.0.1.tgz"
	"https://registry.npmjs.org/@polymer/iron-icon/-/iron-icon-3.0.1.tgz -> restic-browser-npm-polymer-iron-icon-3.0.1.tgz"
	"https://registry.npmjs.org/@polymer/iron-iconset-svg/-/iron-iconset-svg-3.0.1.tgz -> restic-browser-npm-polymer-iron-iconset-svg-3.0.1.tgz"
	"https://registry.npmjs.org/@polymer/iron-meta/-/iron-meta-3.0.1.tgz -> restic-browser-npm-polymer-iron-meta-3.0.1.tgz"
	"https://registry.npmjs.org/@polymer/polymer/-/polymer-3.5.2.tgz -> restic-browser-npm-polymer-polymer-3.5.2.tgz"
	"https://registry.npmjs.org/@rollup/rollup-linux-arm64-gnu/-/rollup-linux-arm64-gnu-4.52.4.tgz -> restic-browser-npm-rollup-rollup-linux-arm64-gnu-4.52.4.tgz"
	"https://registry.npmjs.org/@tauri-apps/api/-/api-2.8.0.tgz -> restic-browser-npm-tauri-apps-api-2.8.0.tgz"
	"https://registry.npmjs.org/@tauri-apps/cli/-/cli-2.8.4.tgz -> restic-browser-npm-tauri-apps-cli-2.8.4.tgz"
	"https://registry.npmjs.org/@tauri-apps/cli-linux-arm64-gnu/-/cli-linux-arm64-gnu-2.8.4.tgz -> restic-browser-npm-tauri-apps-cli-linux-arm64-gnu-2.8.4.tgz"
	"https://registry.npmjs.org/@tauri-apps/plugin-dialog/-/plugin-dialog-2.4.0.tgz -> restic-browser-npm-tauri-apps-plugin-dialog-2.4.0.tgz"
	"https://registry.npmjs.org/@tauri-apps/plugin-fs/-/plugin-fs-2.4.2.tgz -> restic-browser-npm-tauri-apps-plugin-fs-2.4.2.tgz"
	"https://registry.npmjs.org/@types/estree/-/estree-1.0.8.tgz -> restic-browser-npm-types-estree-1.0.8.tgz"
	"https://registry.npmjs.org/@types/node/-/node-20.19.21.tgz -> restic-browser-npm-types-node-20.19.21.tgz"
	"https://registry.npmjs.org/@types/trusted-types/-/trusted-types-2.0.7.tgz -> restic-browser-npm-types-trusted-types-2.0.7.tgz"
	"https://registry.npmjs.org/@vaadin/button/-/button-23.3.25.tgz -> restic-browser-npm-vaadin-button-23.3.25.tgz"
	"https://registry.npmjs.org/@vaadin/checkbox/-/checkbox-23.3.25.tgz -> restic-browser-npm-vaadin-checkbox-23.3.25.tgz"
	"https://registry.npmjs.org/@vaadin/component-base/-/component-base-23.3.25.tgz -> restic-browser-npm-vaadin-component-base-23.3.25.tgz"
	"https://registry.npmjs.org/@vaadin/dialog/-/dialog-23.3.25.tgz -> restic-browser-npm-vaadin-dialog-23.3.25.tgz"
	"https://registry.npmjs.org/@vaadin/field-base/-/field-base-23.3.25.tgz -> restic-browser-npm-vaadin-field-base-23.3.25.tgz"
	"https://registry.npmjs.org/@vaadin/grid/-/grid-23.3.25.tgz -> restic-browser-npm-vaadin-grid-23.3.25.tgz"
	"https://registry.npmjs.org/@vaadin/horizontal-layout/-/horizontal-layout-23.3.25.tgz -> restic-browser-npm-vaadin-horizontal-layout-23.3.25.tgz"
	"https://registry.npmjs.org/@vaadin/icon/-/icon-23.3.25.tgz -> restic-browser-npm-vaadin-icon-23.3.25.tgz"
	"https://registry.npmjs.org/@vaadin/icons/-/icons-23.3.25.tgz -> restic-browser-npm-vaadin-icons-23.3.25.tgz"
	"https://registry.npmjs.org/@vaadin/input-container/-/input-container-23.3.25.tgz -> restic-browser-npm-vaadin-input-container-23.3.25.tgz"
	"https://registry.npmjs.org/@vaadin/item/-/item-23.3.25.tgz -> restic-browser-npm-vaadin-item-23.3.25.tgz"
	"https://registry.npmjs.org/@vaadin/list-box/-/list-box-23.3.25.tgz -> restic-browser-npm-vaadin-list-box-23.3.25.tgz"
	"https://registry.npmjs.org/@vaadin/lit-renderer/-/lit-renderer-23.3.25.tgz -> restic-browser-npm-vaadin-lit-renderer-23.3.25.tgz"
	"https://registry.npmjs.org/@vaadin/notification/-/notification-23.3.25.tgz -> restic-browser-npm-vaadin-notification-23.3.25.tgz"
	"https://registry.npmjs.org/@vaadin/overlay/-/overlay-23.3.25.tgz -> restic-browser-npm-vaadin-overlay-23.3.25.tgz"
	"https://registry.npmjs.org/@vaadin/password-field/-/password-field-23.3.25.tgz -> restic-browser-npm-vaadin-password-field-23.3.25.tgz"
	"https://registry.npmjs.org/@vaadin/select/-/select-23.3.25.tgz -> restic-browser-npm-vaadin-select-23.3.25.tgz"
	"https://registry.npmjs.org/@vaadin/split-layout/-/split-layout-23.3.25.tgz -> restic-browser-npm-vaadin-split-layout-23.3.25.tgz"
	"https://registry.npmjs.org/@vaadin/text-field/-/text-field-23.3.25.tgz -> restic-browser-npm-vaadin-text-field-23.3.25.tgz"
	"https://registry.npmjs.org/@vaadin/vaadin-development-mode-detector/-/vaadin-development-mode-detector-2.0.7.tgz -> restic-browser-npm-vaadin-vaadin-development-mode-detector-2.0.7.tgz"
	"https://registry.npmjs.org/@vaadin/vaadin-list-mixin/-/vaadin-list-mixin-23.3.25.tgz -> restic-browser-npm-vaadin-vaadin-list-mixin-23.3.25.tgz"
	"https://registry.npmjs.org/@vaadin/vaadin-lumo-styles/-/vaadin-lumo-styles-23.3.25.tgz -> restic-browser-npm-vaadin-vaadin-lumo-styles-23.3.25.tgz"
	"https://registry.npmjs.org/@vaadin/vaadin-material-styles/-/vaadin-material-styles-23.3.25.tgz -> restic-browser-npm-vaadin-vaadin-material-styles-23.3.25.tgz"
	"https://registry.npmjs.org/@vaadin/vaadin-themable-mixin/-/vaadin-themable-mixin-23.3.25.tgz -> restic-browser-npm-vaadin-vaadin-themable-mixin-23.3.25.tgz"
	"https://registry.npmjs.org/@vaadin/vaadin-usage-statistics/-/vaadin-usage-statistics-2.1.3.tgz -> restic-browser-npm-vaadin-vaadin-usage-statistics-2.1.3.tgz"
	"https://registry.npmjs.org/@vaadin/vertical-layout/-/vertical-layout-23.3.25.tgz -> restic-browser-npm-vaadin-vertical-layout-23.3.25.tgz"
	"https://registry.npmjs.org/@webcomponents/shadycss/-/shadycss-1.11.2.tgz -> restic-browser-npm-webcomponents-shadycss-1.11.2.tgz"
	"https://registry.npmjs.org/esbuild/-/esbuild-0.25.10.tgz -> restic-browser-npm-esbuild-0.25.10.tgz"
	"https://registry.npmjs.org/fdir/-/fdir-6.5.0.tgz -> restic-browser-npm-fdir-6.5.0.tgz"
	"https://registry.npmjs.org/lit/-/lit-2.8.0.tgz -> restic-browser-npm-lit-2.8.0.tgz"
	"https://registry.npmjs.org/lit-element/-/lit-element-3.3.3.tgz -> restic-browser-npm-lit-element-3.3.3.tgz"
	"https://registry.npmjs.org/lit-html/-/lit-html-2.8.0.tgz -> restic-browser-npm-lit-html-2.8.0.tgz"
	"https://registry.npmjs.org/mobx/-/mobx-6.15.0.tgz -> restic-browser-npm-mobx-6.15.0.tgz"
	"https://registry.npmjs.org/nanoid/-/nanoid-3.3.11.tgz -> restic-browser-npm-nanoid-3.3.11.tgz"
	"https://registry.npmjs.org/picocolors/-/picocolors-1.1.1.tgz -> restic-browser-npm-picocolors-1.1.1.tgz"
	"https://registry.npmjs.org/picomatch/-/picomatch-4.0.3.tgz -> restic-browser-npm-picomatch-4.0.3.tgz"
	"https://registry.npmjs.org/postcss/-/postcss-8.5.6.tgz -> restic-browser-npm-postcss-8.5.6.tgz"
	"https://registry.npmjs.org/pretty-bytes/-/pretty-bytes-6.1.1.tgz -> restic-browser-npm-pretty-bytes-6.1.1.tgz"
	"https://registry.npmjs.org/rollup/-/rollup-4.52.4.tgz -> restic-browser-npm-rollup-4.52.4.tgz"
	"https://registry.npmjs.org/source-map-js/-/source-map-js-1.2.1.tgz -> restic-browser-npm-source-map-js-1.2.1.tgz"
	"https://registry.npmjs.org/tinyglobby/-/tinyglobby-0.2.15.tgz -> restic-browser-npm-tinyglobby-0.2.15.tgz"
	"https://registry.npmjs.org/typescript/-/typescript-5.9.3.tgz -> restic-browser-npm-typescript-5.9.3.tgz"
	"https://registry.npmjs.org/undici-types/-/undici-types-6.21.0.tgz -> restic-browser-npm-undici-types-6.21.0.tgz"
	"https://registry.npmjs.org/vite/-/vite-7.1.9.tgz -> restic-browser-npm-vite-7.1.9.tgz"
)

# node_modules/<path> -> distfile, one per line
RESTIC_BROWSER_NPM_PATHS=(
	"node_modules/@adobe/lit-mobx|restic-browser-npm-adobe-lit-mobx-2.2.2.tgz"
	"node_modules/@esbuild/linux-arm64|restic-browser-npm-esbuild-linux-arm64-0.25.10.tgz"
	"node_modules/@lit-labs/ssr-dom-shim|restic-browser-npm-lit-labs-ssr-dom-shim-1.4.0.tgz"
	"node_modules/@lit/reactive-element|restic-browser-npm-lit-reactive-element-1.6.3.tgz"
	"node_modules/@open-wc/dedupe-mixin|restic-browser-npm-open-wc-dedupe-mixin-1.4.0.tgz"
	"node_modules/@polymer/iron-flex-layout|restic-browser-npm-polymer-iron-flex-layout-3.0.1.tgz"
	"node_modules/@polymer/iron-icon|restic-browser-npm-polymer-iron-icon-3.0.1.tgz"
	"node_modules/@polymer/iron-iconset-svg|restic-browser-npm-polymer-iron-iconset-svg-3.0.1.tgz"
	"node_modules/@polymer/iron-meta|restic-browser-npm-polymer-iron-meta-3.0.1.tgz"
	"node_modules/@polymer/polymer|restic-browser-npm-polymer-polymer-3.5.2.tgz"
	"node_modules/@rollup/rollup-linux-arm64-gnu|restic-browser-npm-rollup-rollup-linux-arm64-gnu-4.52.4.tgz"
	"node_modules/@tauri-apps/api|restic-browser-npm-tauri-apps-api-2.8.0.tgz"
	"node_modules/@tauri-apps/cli|restic-browser-npm-tauri-apps-cli-2.8.4.tgz"
	"node_modules/@tauri-apps/cli-linux-arm64-gnu|restic-browser-npm-tauri-apps-cli-linux-arm64-gnu-2.8.4.tgz"
	"node_modules/@tauri-apps/plugin-dialog|restic-browser-npm-tauri-apps-plugin-dialog-2.4.0.tgz"
	"node_modules/@tauri-apps/plugin-fs|restic-browser-npm-tauri-apps-plugin-fs-2.4.2.tgz"
	"node_modules/@types/estree|restic-browser-npm-types-estree-1.0.8.tgz"
	"node_modules/@types/node|restic-browser-npm-types-node-20.19.21.tgz"
	"node_modules/@types/trusted-types|restic-browser-npm-types-trusted-types-2.0.7.tgz"
	"node_modules/@vaadin/button|restic-browser-npm-vaadin-button-23.3.25.tgz"
	"node_modules/@vaadin/checkbox|restic-browser-npm-vaadin-checkbox-23.3.25.tgz"
	"node_modules/@vaadin/component-base|restic-browser-npm-vaadin-component-base-23.3.25.tgz"
	"node_modules/@vaadin/dialog|restic-browser-npm-vaadin-dialog-23.3.25.tgz"
	"node_modules/@vaadin/field-base|restic-browser-npm-vaadin-field-base-23.3.25.tgz"
	"node_modules/@vaadin/grid|restic-browser-npm-vaadin-grid-23.3.25.tgz"
	"node_modules/@vaadin/horizontal-layout|restic-browser-npm-vaadin-horizontal-layout-23.3.25.tgz"
	"node_modules/@vaadin/icon|restic-browser-npm-vaadin-icon-23.3.25.tgz"
	"node_modules/@vaadin/icons|restic-browser-npm-vaadin-icons-23.3.25.tgz"
	"node_modules/@vaadin/input-container|restic-browser-npm-vaadin-input-container-23.3.25.tgz"
	"node_modules/@vaadin/item|restic-browser-npm-vaadin-item-23.3.25.tgz"
	"node_modules/@vaadin/list-box|restic-browser-npm-vaadin-list-box-23.3.25.tgz"
	"node_modules/@vaadin/lit-renderer|restic-browser-npm-vaadin-lit-renderer-23.3.25.tgz"
	"node_modules/@vaadin/notification|restic-browser-npm-vaadin-notification-23.3.25.tgz"
	"node_modules/@vaadin/overlay|restic-browser-npm-vaadin-overlay-23.3.25.tgz"
	"node_modules/@vaadin/password-field|restic-browser-npm-vaadin-password-field-23.3.25.tgz"
	"node_modules/@vaadin/select|restic-browser-npm-vaadin-select-23.3.25.tgz"
	"node_modules/@vaadin/split-layout|restic-browser-npm-vaadin-split-layout-23.3.25.tgz"
	"node_modules/@vaadin/text-field|restic-browser-npm-vaadin-text-field-23.3.25.tgz"
	"node_modules/@vaadin/vaadin-development-mode-detector|restic-browser-npm-vaadin-vaadin-development-mode-detector-2.0.7.tgz"
	"node_modules/@vaadin/vaadin-list-mixin|restic-browser-npm-vaadin-vaadin-list-mixin-23.3.25.tgz"
	"node_modules/@vaadin/vaadin-lumo-styles|restic-browser-npm-vaadin-vaadin-lumo-styles-23.3.25.tgz"
	"node_modules/@vaadin/vaadin-material-styles|restic-browser-npm-vaadin-vaadin-material-styles-23.3.25.tgz"
	"node_modules/@vaadin/vaadin-themable-mixin|restic-browser-npm-vaadin-vaadin-themable-mixin-23.3.25.tgz"
	"node_modules/@vaadin/vaadin-usage-statistics|restic-browser-npm-vaadin-vaadin-usage-statistics-2.1.3.tgz"
	"node_modules/@vaadin/vertical-layout|restic-browser-npm-vaadin-vertical-layout-23.3.25.tgz"
	"node_modules/@webcomponents/shadycss|restic-browser-npm-webcomponents-shadycss-1.11.2.tgz"
	"node_modules/esbuild|restic-browser-npm-esbuild-0.25.10.tgz"
	"node_modules/fdir|restic-browser-npm-fdir-6.5.0.tgz"
	"node_modules/lit|restic-browser-npm-lit-2.8.0.tgz"
	"node_modules/lit-element|restic-browser-npm-lit-element-3.3.3.tgz"
	"node_modules/lit-html|restic-browser-npm-lit-html-2.8.0.tgz"
	"node_modules/mobx|restic-browser-npm-mobx-6.15.0.tgz"
	"node_modules/nanoid|restic-browser-npm-nanoid-3.3.11.tgz"
	"node_modules/picocolors|restic-browser-npm-picocolors-1.1.1.tgz"
	"node_modules/picomatch|restic-browser-npm-picomatch-4.0.3.tgz"
	"node_modules/postcss|restic-browser-npm-postcss-8.5.6.tgz"
	"node_modules/pretty-bytes|restic-browser-npm-pretty-bytes-6.1.1.tgz"
	"node_modules/rollup|restic-browser-npm-rollup-4.52.4.tgz"
	"node_modules/source-map-js|restic-browser-npm-source-map-js-1.2.1.tgz"
	"node_modules/tinyglobby|restic-browser-npm-tinyglobby-0.2.15.tgz"
	"node_modules/typescript|restic-browser-npm-typescript-5.9.3.tgz"
	"node_modules/undici-types|restic-browser-npm-undici-types-6.21.0.tgz"
	"node_modules/vite|restic-browser-npm-vite-7.1.9.tgz"
)

SRC_URI="
	https://github.com/emuell/restic-browser/archive/refs/tags/v${PV}.tar.gz
		-> ${P}.tar.gz
	https://gitlab.com/api/v4/projects/64331580/packages/generic/${PN}/${PV}/${P}-crates.tar.xz
	${CARGO_CRATE_URIS}
	${RESTIC_BROWSER_NPM_SRC_URI[*]}
"
S="${WORKDIR}/${P}/src-tauri"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD ISC MIT MPL-2.0
	Unicode-3.0
"
# The frontend's runtime-bundled npm dependencies (embedded in the
# installed binary via Tauri's asset system) are Apache-2.0, MIT, or
# BSD-3-Clause -- the latter already covered by the "BSD" crate-license
# entry above (Gentoo's licenses/BSD file is the 3-clause text). This
# notably includes the vendored @vaadin/* family, deliberately pinned to
# 23.3.25 (see the RESTIC_BROWSER_NPM_SRC_URI comment above)
# specifically because 23.5.0+ relicensed those same packages under the
# non-redistributable Vaadin Commercial License and Service Terms
# (https://vaadin.com/commercial-license-and-service-terms).
SLOT="0"
KEYWORDS="~arm64"

# The bundled linux/arm64 npm dependency closure below was resolved for
# glibc (the "-gnu" npm native-addon variants); it does not cover musl.
REQUIRED_USE="elibc_glibc"

# Actual link-time/runtime libraries pulled in by the built Tauri binary
# (confirmed via `readelf -d` NEEDED entries against a real build image;
# see scripts/README.restic-browser.md). Neither an X server nor a specific
# GTK display backend is linked in -- GTK/WebKitGTK select their backend
# (X11 or Wayland) at runtime from whichever the installed gtk+:3/
# webkit-gtk were built with (see their own REQUIRED_USE), so this ebuild
# must not force either one.
COMMON_DEPEND="
	dev-libs/glib:2
	net-libs/libsoup:3.0
	net-libs/webkit-gtk:4.1
	x11-libs/cairo
	x11-libs/gdk-pixbuf:2
	x11-libs/gtk+:3
	x11-libs/pango
"
RDEPEND="
	${COMMON_DEPEND}
	app-backup/restic
"
DEPEND="${COMMON_DEPEND}"
BDEPEND="
	net-libs/nodejs[npm]
"

# Keeps package.json consistent with the actually-vendored node_modules
# (see the RESTIC_BROWSER_NPM_SRC_URI comment above): src_prepare's
# hand-assembled node_modules never reads package.json or package-lock.json,
# so neither this patch nor installing the pinned lockfile below has any
# effect on the build itself, but both leave the unpacked source tree
# accurately declaring the pinned @vaadin/* versions instead of upstream's
# unpinned "^23.3" ranges and commercially-licensed resolutions.
PATCHES=( "${FILESDIR}/${P}-vaadin-23.3.25.patch" )

pkg_setup() {
	# rust.eclass (pulled in via cargo.eclass) normally exports this as
	# pkg_setup itself (sets up CARGO/RUSTC and PATH for the selected Rust
	# slot); defining our own pkg_setup below shadows that unless we call
	# it explicitly.
	rust_pkg_setup

	[[ ${RESTIC_BROWSER_NPM_DEPS_VERSION} == ${PV} ]] ||
		die "RESTIC_BROWSER_NPM_DEPS_VERSION (${RESTIC_BROWSER_NPM_DEPS_VERSION}) does not match PV (${PV}); the pasted-in dependency arrays were generated for a different version"
}

src_prepare() {
	pushd .. >/dev/null || die
	default
	popd >/dev/null || die

	local npm_root="${WORKDIR}/${P}"
	local entry pkgpath filename tmpdir rootdir

	gunzip -c "${FILESDIR}/${P}-vaadin-23.3.25-package-lock.json.gz" \
		> "${npm_root}/package-lock.json" || die

	mkdir "${npm_root}/node_modules" || die
	for entry in "${RESTIC_BROWSER_NPM_PATHS[@]}"; do
		pkgpath=${entry%%|*}
		filename=${entry##*|}
		tmpdir=$(mktemp -d --tmpdir="${T}") || die
		tar -xzf "${DISTDIR}/${filename}" -C "${tmpdir}" || die
		rootdir=$(find "${tmpdir}" -mindepth 1 -maxdepth 1 -type d)
		[[ -n ${rootdir} ]] || die "no top-level directory found in ${filename}"
		mkdir -p "${npm_root}/$(dirname "${pkgpath}")" || die
		mv "${rootdir}" "${npm_root}/${pkgpath}" || die
		rm -rf "${tmpdir}" || die
	done

	# "npm run build" (tsc && vite build) only ever invokes these two
	# binaries directly; everything else (rollup, esbuild) is loaded by
	# vite/tsc as a library, not via PATH, so no full `npm install`
	# bin-linking pass is needed.
	mkdir "${npm_root}/node_modules/.bin" || die
	ln -s ../typescript/bin/tsc "${npm_root}/node_modules/.bin/tsc" || die
	ln -s ../vite/bin/vite.js "${npm_root}/node_modules/.bin/vite" || die
}

src_configure() {
	local myfeatures=(
		custom-protocol
	)
	cargo_src_configure
}

src_compile() {
	pushd .. >/dev/null || die
	npm run build || die
	popd >/dev/null || die

	cargo_src_compile
}

src_install() {
	cargo_src_install

	newicon "${S}/icons/icon.png" "${PN}.png"
	make_desktop_entry "${PN}" Restic-Browser "${PN}"
}
