# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# python-single-r1.eclass does not (yet) support EAPI 9 (see
# dev-util/semgrep-bin, which hit the same constraint); keep this at 8
# until it does.
EAPI=8

# Resolved via `pip install --dry-run --report` against cp312 manylinux
# wheels (see scripts/generate-open-webui-wheel-deps.py); upstream's own
# requires-python is "<3.13.0a1,>=3.11". python3.11 is not available on
# the host this was authored on, so only python3.12 has been resolved
# and validated -- do not add python3_11 without re-running the resolver
# for the cp311 ABI tag first, its wheel set may differ.
PYTHON_COMPAT=( python3_12 )

inherit python-single-r1 systemd

DESCRIPTION="Self-hosted web interface for LLM backends (Ollama, OpenAI-compatible APIs)"
HOMEPAGE="
	https://openwebui.com/
	https://github.com/open-webui/open-webui/
	https://pypi.org/project/open-webui/
"

# Immutable, hash-pinned files.pythonhosted.org URL for the main package,
# taken directly from https://pypi.org/pypi/open-webui/0.11.0/json
# (verified against the sha256 digest published there). Do NOT point
# this at ::nest, ::pentoo, or any GitHub Actions build artifact.
OPEN_WEBUI_MAIN_WHEEL="open_webui-0.11.0-py3-none-any.whl"

# Generated by scripts/generate-open-webui-wheel-deps.py; do not edit.
# Locked PyPI wheel dependency closure for www-apps/open-webui-bin-0.11.0:
#   191 arch-independent (pure-Python) + 65 arch-specific pairs
OPEN_WEBUI_WHEEL_DEPS_VERSION="0.11.0"

# name|version|distfile, arch-independent (identical wheel both platforms)
OPEN_WEBUI_WHEELS_COMMON=(
	"APScheduler|3.11.2|apscheduler-3.11.2-py3-none-any.whl"
	"Authlib|1.7.2|authlib-1.7.2-py2.py3-none-any.whl"
	"Events|0.5|Events-0.5-py3-none-any.whl"
	"Jinja2|3.1.6|jinja2-3.1.6-py3-none-any.whl"
	"Mako|1.4.1|mako-1.4.1-py3-none-any.whl"
	"Markdown|3.10.2|markdown-3.10.2-py3-none-any.whl"
	"PyJWT|2.13.0|pyjwt-2.13.0-py3-none-any.whl"
	"PyMySQL|1.2.0|pymysql-1.2.0-py3-none-any.whl"
	"PyPika|0.51.1|pypika-0.51.1-py2.py3-none-any.whl"
	"Pygments|2.21.0|pygments-2.21.0-py3-none-any.whl"
	"RestrictedPython|8.2|restrictedpython-8.2-py3-none-any.whl"
	"accelerate|1.13.0|accelerate-1.13.0-py3-none-any.whl"
	"aiocache|0.12.3|aiocache-0.12.3-py2.py3-none-any.whl"
	"aiodns|4.0.4|aiodns-4.0.4-py3-none-any.whl"
	"aiofiles|25.1.0|aiofiles-25.1.0-py3-none-any.whl"
	"aiohappyeyeballs|2.7.1|aiohappyeyeballs-2.7.1-py3-none-any.whl"
	"aiosignal|1.4.0|aiosignal-1.4.0-py3-none-any.whl"
	"aiosqlite|0.22.1|aiosqlite-0.22.1-py3-none-any.whl"
	"alembic|1.18.4|alembic-1.18.4-py3-none-any.whl"
	"annotated-doc|0.0.5|annotated_doc-0.0.5-py3-none-any.whl"
	"annotated-types|0.8.0|annotated_types-0.8.0-py3-none-any.whl"
	"anthropic|0.86.0|anthropic-0.86.0-py3-none-any.whl"
	"anyio|4.14.2|anyio-4.14.2-py3-none-any.whl"
	"argon2-cffi|25.1.0|argon2_cffi-25.1.0-py3-none-any.whl"
	"asgiref|3.11.1|asgiref-3.11.1-py3-none-any.whl"
	"async-timeout|5.0.1|async_timeout-5.0.1-py3-none-any.whl"
	"attrs|26.1.0|attrs-26.1.0-py3-none-any.whl"
	"azure-ai-documentintelligence|1.0.2|azure_ai_documentintelligence-1.0.2-py3-none-any.whl"
	"azure-core|1.41.0|azure_core-1.41.0-py3-none-any.whl"
	"azure-identity|1.25.3|azure_identity-1.25.3-py3-none-any.whl"
	"azure-storage-blob|12.29.0|azure_storage_blob-12.29.0-py3-none-any.whl"
	"beautifulsoup4|4.14.3|beautifulsoup4-4.14.3-py3-none-any.whl"
	"bidict|0.24.0|bidict-0.24.0-py3-none-any.whl"
	"boto3|1.42.62|boto3-1.42.62-py3-none-any.whl"
	"botocore|1.42.97|botocore-1.42.97-py3-none-any.whl"
	"build|1.5.0|build-1.5.0-py3-none-any.whl"
	"certifi|2026.7.22|certifi-2026.7.22-py3-none-any.whl"
	"click|8.4.2|click-8.4.2-py3-none-any.whl"
	"colorlog|6.12.0|colorlog-6.12.0-py3-none-any.whl"
	"ddgs|9.14.4|ddgs-9.14.4-py3-none-any.whl"
	"defusedxml|0.7.1|defusedxml-0.7.1-py2.py3-none-any.whl"
	"distro|1.9.0|distro-1.9.0-py3-none-any.whl"
	"docstring_parser|0.18.0|docstring_parser-0.18.0-py3-none-any.whl"
	"docx2txt|0.9|docx2txt-0.9-py3-none-any.whl"
	"durationpy|0.10|durationpy-0.10-py3-none-any.whl"
	"einops|0.8.2|einops-0.8.2-py3-none-any.whl"
	"et_xmlfile|2.0.0|et_xmlfile-2.0.0-py3-none-any.whl"
	"fake-useragent|2.2.0|fake_useragent-2.2.0-py3-none-any.whl"
	"fastapi|0.136.3|fastapi-0.136.3-py3-none-any.whl"
	"faster-whisper|1.2.1|faster_whisper-1.2.1-py3-none-any.whl"
	"filelock|3.32.4|filelock-3.32.4-py3-none-any.whl"
	"flatbuffers|25.12.19|flatbuffers-25.12.19-py2.py3-none-any.whl"
	"fpdf2|2.8.7|fpdf2-2.8.7-py3-none-any.whl"
	"fsspec|2026.7.0|fsspec-2026.7.0-py3-none-any.whl"
	"ftfy|6.3.1|ftfy-6.3.1-py3-none-any.whl"
	"google-api-core|2.34.0|google_api_core-2.34.0-py3-none-any.whl"
	"google-api-python-client|2.197.0|google_api_python_client-2.197.0-py3-none-any.whl"
	"google-auth|2.57.0|google_auth-2.57.0-py3-none-any.whl"
	"google-auth-httplib2|0.4.0|google_auth_httplib2-0.4.0-py3-none-any.whl"
	"google-auth-oauthlib|1.4.0|google_auth_oauthlib-1.4.0-py3-none-any.whl"
	"google-cloud-core|2.7.0|google_cloud_core-2.7.0-py3-none-any.whl"
	"google-cloud-storage|3.9.0|google_cloud_storage-3.9.0-py3-none-any.whl"
	"google-genai|1.66.0|google_genai-1.66.0-py3-none-any.whl"
	"google-resumable-media|2.10.1|google_resumable_media-2.10.1-py3-none-any.whl"
	"googleapis-common-protos|1.75.0|googleapis_common_protos-1.75.0-py3-none-any.whl"
	"h11|0.16.0|h11-0.16.0-py3-none-any.whl"
	"h2|4.4.1|h2-4.4.1-py3-none-any.whl"
	"hpack|4.2.0|hpack-4.2.0-py3-none-any.whl"
	"httpcore|1.0.9|httpcore-1.0.9-py3-none-any.whl"
	"httplib2|0.32.0|httplib2-0.32.0-py3-none-any.whl"
	"httpx|0.28.1|httpx-0.28.1-py3-none-any.whl"
	"httpx-sse|0.4.3|httpx_sse-0.4.3-py3-none-any.whl"
	"huggingface_hub|1.28.0|huggingface_hub-1.28.0-py3-none-any.whl"
	"hyperframe|6.1.0|hyperframe-6.1.0-py3-none-any.whl"
	"idna|3.19|idna-3.19-py3-none-any.whl"
	"importlib_resources|7.1.0|importlib_resources-7.1.0-py3-none-any.whl"
	"isodate|0.7.2|isodate-0.7.2-py3-none-any.whl"
	"itsdangerous|2.2.0|itsdangerous-2.2.0-py3-none-any.whl"
	"jmespath|1.1.0|jmespath-1.1.0-py3-none-any.whl"
	"joblib|1.5.3|joblib-1.5.3-py3-none-any.whl"
	"joserfc|1.7.4|joserfc-1.7.4-py3-none-any.whl"
	"jsonpatch|1.33|jsonpatch-1.33-py2.py3-none-any.whl"
	"jsonpointer|3.1.1|jsonpointer-3.1.1-py3-none-any.whl"
	"jsonschema|4.26.0|jsonschema-4.26.0-py3-none-any.whl"
	"jsonschema-specifications|2025.9.1|jsonschema_specifications-2025.9.1-py3-none-any.whl"
	"kubernetes|36.0.3|kubernetes-36.0.3-py2.py3-none-any.whl"
	"langchain|1.2.10|langchain-1.2.10-py3-none-any.whl"
	"langchain-classic|1.0.7|langchain_classic-1.0.7-py3-none-any.whl"
	"langchain-community|0.4.2|langchain_community-0.4.2-py3-none-any.whl"
	"langchain-core|1.6.0|langchain_core-1.6.0-py3-none-any.whl"
	"langchain-protocol|0.0.18|langchain_protocol-0.0.18-py3-none-any.whl"
	"langchain-text-splitters|1.1.2|langchain_text_splitters-1.1.2-py3-none-any.whl"
	"langgraph|1.0.10|langgraph-1.0.10-py3-none-any.whl"
	"langgraph-checkpoint|4.2.0|langgraph_checkpoint-4.2.0-py3-none-any.whl"
	"langgraph-prebuilt|1.0.13|langgraph_prebuilt-1.0.13-py3-none-any.whl"
	"langgraph-sdk|0.3.15|langgraph_sdk-0.3.15-py3-none-any.whl"
	"langsmith|0.11.1|langsmith-0.11.1-py3-none-any.whl"
	"ldap3|2.9.1|ldap3-2.9.1-py2.py3-none-any.whl"
	"loguru|0.7.3|loguru-0.7.3-py3-none-any.whl"
	"markdown-it-py|4.2.0|markdown_it_py-4.2.0-py3-none-any.whl"
	"mcp|1.27.2|mcp-1.27.2-py3-none-any.whl"
	"mdurl|0.1.2|mdurl-0.1.2-py3-none-any.whl"
	"mpmath|1.3.0|mpmath-1.3.0-py3-none-any.whl"
	"msal|1.38.0|msal-1.38.0-py3-none-any.whl"
	"msal-extensions|1.3.1|msal_extensions-1.3.1-py3-none-any.whl"
	"msoffcrypto-tool|6.0.0|msoffcrypto_tool-6.0.0-py3-none-any.whl"
	"mypy_extensions|1.1.0|mypy_extensions-1.1.0-py3-none-any.whl"
	"narwhals|2.25.0|narwhals-2.25.0-py3-none-any.whl"
	"networkx|3.6.1|networkx-3.6.1-py3-none-any.whl"
	"nltk|3.9.4|nltk-3.9.4-py3-none-any.whl"
	"oauthlib|3.3.1|oauthlib-3.3.1-py3-none-any.whl"
	"olefile|0.47|olefile-0.47-py2.py3-none-any.whl"
	"omegaconf|2.3.1|omegaconf-2.3.1-py3-none-any.whl"
	"openai|2.29.0|openai-2.29.0-py3-none-any.whl"
	"openpyxl|3.1.5|openpyxl-3.1.5-py2.py3-none-any.whl"
	"opensearch-protobufs|1.2.0|opensearch_protobufs-1.2.0-py3-none-any.whl"
	"opensearch-py|3.2.0|opensearch_py-3.2.0-py3-none-any.whl"
	"opentelemetry-api|1.44.0|opentelemetry_api-1.44.0-py3-none-any.whl"
	"opentelemetry-exporter-otlp-proto-common|1.44.0|opentelemetry_exporter_otlp_proto_common-1.44.0-py3-none-any.whl"
	"opentelemetry-exporter-otlp-proto-grpc|1.44.0|opentelemetry_exporter_otlp_proto_grpc-1.44.0-py3-none-any.whl"
	"opentelemetry-proto|1.44.0|opentelemetry_proto-1.44.0-py3-none-any.whl"
	"opentelemetry-sdk|1.44.0|opentelemetry_sdk-1.44.0-py3-none-any.whl"
	"opentelemetry-semantic-conventions|0.65b0|opentelemetry_semantic_conventions-0.65b0-py3-none-any.whl"
	"overrides|7.7.0|overrides-7.7.0-py3-none-any.whl"
	"packaging|26.3|packaging-26.3-py3-none-any.whl"
	"pathspec|1.1.1|pathspec-1.1.1-py3-none-any.whl"
	"platformdirs|4.11.4|platformdirs-4.11.4-py3-none-any.whl"
	"proto-plus|1.28.3|proto_plus-1.28.3-py3-none-any.whl"
	"psycopg|3.3.4|psycopg-3.3.4-py3-none-any.whl"
	"pyasn1|0.6.4|pyasn1-0.6.4-py3-none-any.whl"
	"pyasn1_modules|0.4.2|pyasn1_modules-0.4.2-py3-none-any.whl"
	"pycparser|3.0|pycparser-3.0-py3-none-any.whl"
	"pydantic|2.13.4|pydantic-2.13.4-py3-none-any.whl"
	"pydantic-settings|2.15.0|pydantic_settings-2.15.0-py3-none-any.whl"
	"pydub|0.25.1|pydub-0.25.1-py2.py3-none-any.whl"
	"pymdown-extensions|10.21.3|pymdown_extensions-10.21.3-py3-none-any.whl"
	"pypandoc|1.17|pypandoc-1.17-py3-none-any.whl"
	"pyparsing|3.3.2|pyparsing-3.3.2-py3-none-any.whl"
	"pypdf|6.7.5|pypdf-6.7.5-py3-none-any.whl"
	"pyproject_hooks|1.2.0|pyproject_hooks-1.2.0-py3-none-any.whl"
	"python-dateutil|2.9.0.post0|python_dateutil-2.9.0.post0-py2.py3-none-any.whl"
	"python-dotenv|1.2.3|python_dotenv-1.2.3-py3-none-any.whl"
	"python-engineio|4.13.5|python_engineio-4.13.5-py3-none-any.whl"
	"python-mimeparse|2.0.0|python_mimeparse-2.0.0-py3-none-any.whl"
	"python-multipart|0.0.32|python_multipart-0.0.32-py3-none-any.whl"
	"python-pptx|1.0.2|python_pptx-1.0.2-py3-none-any.whl"
	"python-socketio|5.16.2|python_socketio-5.16.2-py3-none-any.whl"
	"pytube|15.0.0|pytube-15.0.0-py3-none-any.whl"
	"pytz|2026.2|pytz-2026.2-py2.py3-none-any.whl"
	"pyxlsb|1.0.10|pyxlsb-1.0.10-py2.py3-none-any.whl"
	"rank-bm25|0.2.2|rank_bm25-0.2.2-py3-none-any.whl"
	"rapidocr|3.9.2|rapidocr-3.9.2-py3-none-any.whl"
	"redis|8.0.1|redis-8.0.1-py3-none-any.whl"
	"referencing|0.37.0|referencing-0.37.0-py3-none-any.whl"
	"requests|2.34.2|requests-2.34.2-py3-none-any.whl"
	"requests-oauthlib|2.0.0|requests_oauthlib-2.0.0-py2.py3-none-any.whl"
	"requests-toolbelt|1.0.0|requests_toolbelt-1.0.0-py2.py3-none-any.whl"
	"rich|13.9.4|rich-13.9.4-py3-none-any.whl"
	"s3transfer|0.16.1|s3transfer-0.16.1-py3-none-any.whl"
	"sentence-transformers|5.5.1|sentence_transformers-5.5.1-py3-none-any.whl"
	"setuptools|84.0.0|setuptools-84.0.0-py3-none-any.whl"
	"shellingham|1.5.4|shellingham-1.5.4-py2.py3-none-any.whl"
	"simple-websocket|1.1.0|simple_websocket-1.1.0-py3-none-any.whl"
	"six|1.17.0|six-1.17.0-py2.py3-none-any.whl"
	"sniffio|1.3.1|sniffio-1.3.1-py3-none-any.whl"
	"socksio|1.0.0|socksio-1.0.0-py3-none-any.whl"
	"soupsieve|2.9.2|soupsieve-2.9.2-py3-none-any.whl"
	"sse-starlette|3.4.8|sse_starlette-3.4.8-py3-none-any.whl"
	"starlette|1.6.0|starlette-1.6.0-py3-none-any.whl"
	"starlette-compress|1.7.1|starlette_compress-1.7.1-py3-none-any.whl"
	"starsessions|2.2.1|starsessions-2.2.1-py3-none-any.whl"
	"sympy|1.14.0|sympy-1.14.0-py3-none-any.whl"
	"tenacity|9.1.4|tenacity-9.1.4-py3-none-any.whl"
	"threadpoolctl|3.6.0|threadpoolctl-3.6.0-py3-none-any.whl"
	"tqdm|4.70.0|tqdm-4.70.0-py3-none-any.whl"
	"transformers|5.5.4|transformers-5.5.4-py3-none-any.whl"
	"typer|0.27.1|typer-0.27.1-py3-none-any.whl"
	"typing-inspection|0.4.4|typing_inspection-0.4.4-py3-none-any.whl"
	"typing_extensions|4.16.0|typing_extensions-4.16.0-py3-none-any.whl"
	"tzlocal|5.4.4|tzlocal-5.4.4-py3-none-any.whl"
	"uritemplate|4.2.0|uritemplate-4.2.0-py3-none-any.whl"
	"urllib3|2.7.0|urllib3-2.7.0-py3-none-any.whl"
	"uvicorn|0.51.0|uvicorn-0.51.0-py3-none-any.whl"
	"validators|0.35.0|validators-0.35.0-py3-none-any.whl"
	"wcwidth|0.8.2|wcwidth-0.8.2-py3-none-any.whl"
	"websocket-client|1.9.0|websocket_client-1.9.0-py3-none-any.whl"
	"wsproto|1.3.2|wsproto-1.3.2-py3-none-any.whl"
	"xlrd|2.0.2|xlrd-2.0.2-py2.py3-none-any.whl"
	"xlsxwriter|3.2.9|xlsxwriter-3.2.9-py3-none-any.whl"
	"youtube-transcript-api|1.2.4|youtube_transcript_api-1.2.4-py3-none-any.whl"
	"antlr4-python3-runtime|4.9.3|antlr4-python3-runtime-4.9.3.tar.gz"
)

# name|version|distfile, amd64-only wheel
OPEN_WEBUI_WHEELS_AMD64=(
	"MarkupSafe|3.0.3|markupsafe-3.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl"
	"PyYAML|6.0.3|pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl"
	"SQLAlchemy|2.0.50|sqlalchemy-2.0.50-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl"
	"aiohttp|3.13.5|aiohttp-3.13.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl"
	"argon2-cffi-bindings|26.1.0|argon2_cffi_bindings-26.1.0-cp310-abi3-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl"
	"av|18.1.0|av-18.1.0-cp311-abi3-manylinux_2_28_x86_64.whl"
	"bcrypt|5.0.0|bcrypt-5.0.0-cp39-abi3-manylinux_2_28_x86_64.whl"
	"black|26.5.1|black-26.5.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl"
	"brotli|1.2.0|brotli-1.2.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl"
	"brotlicffi|1.2.0.1|brotlicffi-1.2.0.1-cp38-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl"
	"cffi|2.1.1|cffi-2.1.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl"
	"chardet|7.4.3|chardet-7.4.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl"
	"charset-normalizer|3.5.1|charset_normalizer-3.5.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl"
	"chromadb|1.5.9|chromadb-1.5.9-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
	"cryptography|48.0.0|cryptography-48.0.0-cp311-abi3-manylinux_2_28_x86_64.whl"
	"ctranslate2|4.8.1|ctranslate2-4.8.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl"
	"fonttools|4.63.0|fonttools-4.63.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl"
	"frozenlist|1.8.0|frozenlist-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl"
	"google-crc32c|1.8.0|google_crc32c-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl"
	"greenlet|3.5.5|greenlet-3.5.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl"
	"grpcio|1.83.0|grpcio-1.83.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl"
	"hf-xet|1.6.0|hf_xet-1.6.0-cp38-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl"
	"hiredis|3.4.0|hiredis-3.4.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl"
	"httptools|0.8.0|httptools-0.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl"
	"jiter|0.16.0|jiter-0.16.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
	"lxml|6.1.1|lxml-6.1.1-cp312-cp312-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl"
	"mmh3|5.2.1|mmh3-5.2.1-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl"
	"multidict|6.7.1|multidict-6.7.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl"
	"numpy|2.5.2|numpy-2.5.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl"
	"onnxruntime|1.26.0|onnxruntime-1.26.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl"
	"opencv-python-headless|4.13.0.92|opencv_python_headless-4.13.0.92-cp37-abi3-manylinux_2_28_x86_64.whl"
	"orjson|3.11.9|orjson-3.11.9-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
	"ormsgpack|1.12.2|ormsgpack-1.12.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
	"pandas|3.0.3|pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl"
	"pillow|12.2.0|pillow-12.2.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl"
	"primp|1.3.1|primp-1.3.1-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
	"propcache|0.5.2|propcache-0.5.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl"
	"protobuf|7.36.0|protobuf-7.36.0-cp310-abi3-manylinux2014_x86_64.whl"
	"psutil|7.2.2|psutil-7.2.2-cp36-abi3-manylinux2010_x86_64.manylinux_2_12_x86_64.manylinux_2_28_x86_64.whl"
	"psycopg-binary|3.3.4|psycopg_binary-3.3.4-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl"
	"pyarrow|20.0.0|pyarrow-20.0.0-cp312-cp312-manylinux_2_28_x86_64.whl"
	"pybase64|1.5.0|pybase64-1.5.0-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl"
	"pycares|5.0.1|pycares-5.0.1-cp312-cp312-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl"
	"pyclipper|1.4.0|pyclipper-1.4.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl"
	"pycrdt|0.13.1|pycrdt-0.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
	"pydantic_core|2.46.4|pydantic_core-2.46.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
	"pytokens|0.4.1|pytokens-0.4.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl"
	"regex|2026.5.9|regex-2026.5.9-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl"
	"rpds-py|2026.6.3|rpds_py-2026.6.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
	"safetensors|0.8.0|safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
	"scikit-learn|1.9.0|scikit_learn-1.9.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl"
	"scipy|1.18.1|scipy-1.18.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl"
	"sentencepiece|0.2.1|sentencepiece-0.2.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl"
	"shapely|2.1.2|shapely-2.1.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl"
	"soundfile|0.13.1|soundfile-0.13.1-py2.py3-none-manylinux_2_28_x86_64.whl"
	"tiktoken|0.13.0|tiktoken-0.13.0-cp312-cp312-manylinux_2_28_x86_64.whl"
	"tokenizers|0.22.2|tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
	"torch|2.10.0+cpu|torch-2.10.0+cpu-cp312-cp312-manylinux_2_28_x86_64.whl"
	"uuid_utils|0.17.0|uuid_utils-0.17.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
	"uvloop|0.22.1|uvloop-0.22.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl"
	"watchfiles|1.2.0|watchfiles-1.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
	"websockets|16.1.1|websockets-16.1.1-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl"
	"xxhash|4.0.1|xxhash-4.0.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl"
	"yarl|1.24.5|yarl-1.24.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl"
	"zstandard|0.25.0|zstandard-0.25.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl"
)

# name|version|distfile, arm64-only wheel
OPEN_WEBUI_WHEELS_ARM64=(
	"MarkupSafe|3.0.3|markupsafe-3.0.3-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
	"PyYAML|6.0.3|pyyaml-6.0.3-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
	"SQLAlchemy|2.0.50|sqlalchemy-2.0.50-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
	"aiohttp|3.13.5|aiohttp-3.13.5-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
	"argon2-cffi-bindings|26.1.0|argon2_cffi_bindings-26.1.0-cp310-abi3-manylinux_2_26_aarch64.manylinux_2_28_aarch64.whl"
	"av|18.1.0|av-18.1.0-cp311-abi3-manylinux_2_28_aarch64.whl"
	"bcrypt|5.0.0|bcrypt-5.0.0-cp39-abi3-manylinux_2_28_aarch64.whl"
	"black|26.5.1|black-26.5.1-py3-none-any.whl"
	"brotli|1.2.0|brotli-1.2.0-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
	"brotlicffi|1.2.0.1|brotlicffi-1.2.0.1-cp38-abi3-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
	"cffi|2.1.1|cffi-2.1.1-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.whl"
	"chardet|7.4.3|chardet-7.4.3-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
	"charset-normalizer|3.5.1|charset_normalizer-3.5.1-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
	"chromadb|1.5.9|chromadb-1.5.9-cp39-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl"
	"cryptography|48.0.0|cryptography-48.0.0-cp311-abi3-manylinux_2_28_aarch64.whl"
	"ctranslate2|4.8.1|ctranslate2-4.8.1-cp312-cp312-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl"
	"fonttools|4.63.0|fonttools-4.63.0-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
	"frozenlist|1.8.0|frozenlist-1.8.0-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
	"google-crc32c|1.8.0|google_crc32c-1.8.0-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.whl"
	"greenlet|3.5.5|greenlet-3.5.5-cp312-cp312-manylinux_2_24_aarch64.manylinux_2_28_aarch64.whl"
	"grpcio|1.83.0|grpcio-1.83.0-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.whl"
	"hf-xet|1.6.0|hf_xet-1.6.0-cp38-abi3-manylinux_2_28_aarch64.whl"
	"hiredis|3.4.0|hiredis-3.4.0-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
	"httptools|0.8.0|httptools-0.8.0-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
	"jiter|0.16.0|jiter-0.16.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl"
	"lxml|6.1.1|lxml-6.1.1-cp312-cp312-manylinux_2_26_aarch64.manylinux_2_28_aarch64.whl"
	"mmh3|5.2.1|mmh3-5.2.1-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
	"multidict|6.7.1|multidict-6.7.1-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
	"numpy|2.5.2|numpy-2.5.2-cp312-cp312-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl"
	"onnxruntime|1.26.0|onnxruntime-1.26.0-cp312-cp312-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl"
	"opencv-python-headless|4.13.0.92|opencv_python_headless-4.13.0.92-cp37-abi3-manylinux_2_28_aarch64.whl"
	"orjson|3.11.9|orjson-3.11.9-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl"
	"ormsgpack|1.12.2|ormsgpack-1.12.2-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl"
	"pandas|3.0.3|pandas-3.0.3-cp312-cp312-manylinux_2_24_aarch64.manylinux_2_28_aarch64.whl"
	"pillow|12.2.0|pillow-12.2.0-cp312-cp312-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl"
	"primp|1.3.1|primp-1.3.1-cp310-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl"
	"propcache|0.5.2|propcache-0.5.2-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
	"protobuf|7.36.0|protobuf-7.36.0-cp310-abi3-manylinux2014_aarch64.whl"
	"psutil|7.2.2|psutil-7.2.2-cp36-abi3-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
	"psycopg-binary|3.3.4|psycopg_binary-3.3.4-cp312-cp312-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl"
	"pyarrow|20.0.0|pyarrow-20.0.0-cp312-cp312-manylinux_2_28_aarch64.whl"
	"pybase64|1.5.0|pybase64-1.5.0-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.whl"
	"pycares|5.0.1|pycares-5.0.1-cp312-cp312-manylinux_2_26_aarch64.manylinux_2_28_aarch64.whl"
	"pyclipper|1.4.0|pyclipper-1.4.0-cp312-cp312-manylinux_2_24_aarch64.manylinux_2_28_aarch64.whl"
	"pycrdt|0.13.1|pycrdt-0.13.1-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl"
	"pydantic_core|2.46.4|pydantic_core-2.46.4-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl"
	"pytokens|0.4.1|pytokens-0.4.1-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
	"regex|2026.5.9|regex-2026.5.9-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
	"rpds-py|2026.6.3|rpds_py-2026.6.3-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl"
	"safetensors|0.8.0|safetensors-0.8.0-cp310-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl"
	"scikit-learn|1.9.0|scikit_learn-1.9.0-cp312-cp312-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl"
	"scipy|1.18.1|scipy-1.18.1-cp312-cp312-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl"
	"sentencepiece|0.2.1|sentencepiece-0.2.1-cp312-cp312-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl"
	"shapely|2.1.2|shapely-2.1.2-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.whl"
	"soundfile|0.13.1|soundfile-0.13.1-py2.py3-none-manylinux_2_28_aarch64.whl"
	"tiktoken|0.13.0|tiktoken-0.13.0-cp312-cp312-manylinux_2_28_aarch64.whl"
	"tokenizers|0.22.2|tokenizers-0.22.2-cp39-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl"
	"torch|2.10.0+cpu|torch-2.10.0+cpu-cp312-cp312-manylinux_2_28_aarch64.whl"
	"uuid_utils|0.17.0|uuid_utils-0.17.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl"
	"uvloop|0.22.1|uvloop-0.22.1-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
	"watchfiles|1.2.0|watchfiles-1.2.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl"
	"websockets|16.1.1|websockets-16.1.1-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
	"xxhash|4.0.1|xxhash-4.0.1-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
	"yarl|1.24.5|yarl-1.24.5-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
	"zstandard|0.25.0|zstandard-0.25.0-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.whl"
)

OPEN_WEBUI_WHEEL_SRC_URI="
	https://files.pythonhosted.org/packages/9f/64/2e54428beba8d9992aa478bb8f6de9e4ecaa5f8f513bcfd567ed7fb0262d/apscheduler-3.11.2-py3-none-any.whl
	https://files.pythonhosted.org/packages/fb/95/adcb68e20c34162e9135f370d6e31737719c2b6f94bc953fe7ed1f10fe21/authlib-1.7.2-py2.py3-none-any.whl
	https://files.pythonhosted.org/packages/25/ed/e47dec0626edd468c84c04d97769e7ab4ea6457b7f54dcb3f72b17fcd876/Events-0.5-py3-none-any.whl
	https://files.pythonhosted.org/packages/62/a1/3d680cbfd5f4b8f15abc1d571870c5fc3e594bb582bc3b64ea099db13e56/jinja2-3.1.6-py3-none-any.whl
	https://files.pythonhosted.org/packages/a5/54/12ed58d458474aaab5c3d180173e745a4fe131bb330370596876d19ff60f/mako-1.4.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/de/1f/77fa3081e4f66ca3576c896ae5d31c3002ac6607f9747d2e3aa49227e464/markdown-3.10.2-py3-none-any.whl
	https://files.pythonhosted.org/packages/a3/5e/ecf12fdb62546d64385c158514e9b2b671f7832108ef2ecd2020ce0af2d1/pyjwt-2.13.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/c4/bd/2534e130295c8cfd4f0a2e31623baab7502278f1e97bcfe61db75656a77f/pymysql-1.2.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/57/83/c77dfeed04022e8930b08eedca2b6e5efed256ab3321396fde90066efb65/pypika-0.51.1-py2.py3-none-any.whl
	https://files.pythonhosted.org/packages/71/46/17f022dd3e953bf20a04a028a21ec746d942f8d2af30fa0f124fa0e6a684/pygments-2.21.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/35/59/b2778bfafcc37fdfd87c02702bbfc5753c58c28c7eb82999b7b49ec6e0e7/restrictedpython-8.2-py3-none-any.whl
	https://files.pythonhosted.org/packages/7e/46/02ac5e262d4af18054b3e922b2baedbb2a03289ee792162de60a865defc5/accelerate-1.13.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/37/d7/15d67e05b235d1ed8c3ce61688fe4d84130e72af1657acadfaac3479f4cf/aiocache-0.12.3-py2.py3-none-any.whl
	https://files.pythonhosted.org/packages/7f/70/72e4ab117425ccdc4d10bd523a94c1baa051a15586057d64a4c6888f9e3f/aiodns-4.0.4-py3-none-any.whl
	https://files.pythonhosted.org/packages/bc/8a/340a1555ae33d7354dbca4faa54948d76d89a27ceef032c8c3bc661d003e/aiofiles-25.1.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/71/43/1947f06babed6b3f1d7f38b0c767f52df66bfb2bc10b468c4a7de9eceff2/aiohappyeyeballs-2.7.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/fb/76/641ae371508676492379f16e2fa48f4e2c11741bd63c48be4b12a6b09cba/aiosignal-1.4.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/00/b7/e3bf5133d697a08128598c8d0abc5e16377b51465a33756de24fa7dee953/aiosqlite-0.22.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/d2/29/6533c317b74f707ea28f8d633734dbda2119bbadfc61b2f3640ba835d0f7/alembic-1.18.4-py3-none-any.whl
	https://files.pythonhosted.org/packages/3e/30/e900b21425a860e195f32e37657aa1f7c7f2b1bfb26f03ca209b90933c06/annotated_doc-0.0.5-py3-none-any.whl
	https://files.pythonhosted.org/packages/99/91/8acff4f5e50511b911bbccb72b8628a49c68ce14148cd9f6431094859a90/annotated_types-0.8.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/63/5f/67db29c6e5d16c8c9c4652d3efb934d89cb750cad201539141781d8eae14/anthropic-0.86.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/da/35/f2287558c17e29fafc8ef3daf819bb9834061cfa43bff8014f7df7f63bdc/anyio-4.14.2-py3-none-any.whl
	https://files.pythonhosted.org/packages/4f/d3/a8b22fa575b297cd6e3e3b0155c7e25db170edf1c74783d6a31a2490b8d9/argon2_cffi-25.1.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/5c/0a/a72d10ed65068e115044937873362e6e32fab1b7dce0046aeb224682c989/asgiref-3.11.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/fe/ba/e2081de779ca30d473f21f5b30e0e737c438205440784c7dfc81efc2b029/async_timeout-5.0.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/64/b4/17d4b0b2a2dc85a6df63d1157e028ed19f90d4cd97c36717afef2bc2f395/attrs-26.1.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/d9/75/c9ec040f23082f54ffb1977ff8f364c2d21c79a640a13d1c1809e7fd6b1a/azure_ai_documentintelligence-1.0.2-py3-none-any.whl
	https://files.pythonhosted.org/packages/5b/db/325c6d7312d2200251c52323878281045aaffcb5586612296484e4280eaa/azure_core-1.41.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/49/9a/417b3a533e01953a7c618884df2cb05a71e7b68bdbce4fbdb62349d2a2e8/azure_identity-1.25.3-py3-none-any.whl
	https://files.pythonhosted.org/packages/c2/2c/6ddee6a3e42d0236ba9259e4df7fa97fdc415ff0802b736c634baaf4b285/azure_storage_blob-12.29.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/1a/39/47f9197bdd44df24d67ac8893641e16f386c984a0619ef2ee4c51fbbc019/beautifulsoup4-4.14.3-py3-none-any.whl
	https://files.pythonhosted.org/packages/0e/5b/e16e8cefa48c501b64bec8264f480dc45e87bb4c65d5c9ae5ac4252da3df/bidict-0.24.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/1f/68/b5e82dedd9c8d53a9542df4e3475d2d3ec331eef4a4a801e9c5fa98b583a/boto3-1.42.62-py3-none-any.whl
	https://files.pythonhosted.org/packages/e3/d2/8e025ba1a4e257879af72d06913272311af79673d82fa2581a351b924317/botocore-1.42.97-py3-none-any.whl
	https://files.pythonhosted.org/packages/0d/fe/6bea5c9162869c5beba5d9c8abbed835ec85bf1ec1fba05a3822325c45f3/build-1.5.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/0b/a7/71ac2cff56fec219ed242bb11b8efb69fcc4bec75db06fb7bfe35de520e6/certifi-2026.7.22-py3-none-any.whl
	https://files.pythonhosted.org/packages/fb/e2/79c688af8b210d232694e31e59da9f6ec747bae31c3f5946e4e9b98860d5/click-8.4.2-py3-none-any.whl
	https://files.pythonhosted.org/packages/d4/19/0b6647bf5e331521e55d2b63bfbdc210bd9cd605189273f03614a05f702d/colorlog-6.12.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/e8/5f/32de4d99220eb559b7b1cd1c529a1856efa8097f7a3e10b6c207aa95e36c/ddgs-9.14.4-py3-none-any.whl
	https://files.pythonhosted.org/packages/07/6c/aa3f2f849e01cb6a001cd8554a88d4c77c5c1a31c95bdf1cf9301e6d9ef4/defusedxml-0.7.1-py2.py3-none-any.whl
	https://files.pythonhosted.org/packages/12/b3/231ffd4ab1fc9d679809f356cebee130ac7daa00d6d6f3206dd4fd137e9e/distro-1.9.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/a7/5f/ed01f9a3cdffbd5a008556fc7b2a08ddb1cc6ace7effa7340604b1d16699/docstring_parser-0.18.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/d6/51/756e71bec48ece0ecc2a10e921ef2756e197dcb7e478f2b43673b6683902/docx2txt-0.9-py3-none-any.whl
	https://files.pythonhosted.org/packages/b0/0d/9feae160378a3553fa9a339b0e9c1a048e147a4127210e286ef18b730f03/durationpy-0.10-py3-none-any.whl
	https://files.pythonhosted.org/packages/2a/09/f8d8f8f31e4483c10a906437b4ce31bdf3d6d417b73fe33f1a8b59e34228/einops-0.8.2-py3-none-any.whl
	https://files.pythonhosted.org/packages/c1/8b/5fe2cc11fee489817272089c4203e679c63b570a5aaeb18d852ae3cbba6a/et_xmlfile-2.0.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/51/37/b3ea9cd5558ff4cb51957caca2193981c6b0ff30bd0d2630ac62505d99d0/fake_useragent-2.2.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/e0/82/45359b62a067409bd929ae8a56b8ed13e5a8c8a61194b3c236920999ab83/fastapi-0.136.3-py3-none-any.whl
	https://files.pythonhosted.org/packages/05/99/49ee85903dee060d9f08297b4a342e5e0bcfca2f027a07b4ee0a38ab13f9/faster_whisper-1.2.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/01/a4/9b63d595d748e3aff8812b65eacc1a2c4bd90b7c2012e08e72373b4835eb/filelock-3.32.4-py3-none-any.whl
	https://files.pythonhosted.org/packages/e8/2d/d2a548598be01649e2d46231d151a6c56d10b964d94043a335ae56ea2d92/flatbuffers-25.12.19-py2.py3-none-any.whl
	https://files.pythonhosted.org/packages/66/0a/cf50ecffa1e3747ed9380a3adfc829259f1f86b3fdbd9e505af789003141/fpdf2-2.8.7-py3-none-any.whl
	https://files.pythonhosted.org/packages/fd/3c/6a2bf344106328fd04963664a60b9bb6496fc25df8e962fcdc1367285fb9/fsspec-2026.7.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/ab/6e/81d47999aebc1b155f81eca4477a616a70f238a2549848c38983f3c22a82/ftfy-6.3.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/bc/c1/a8a92ae1bc4b1a8f804c776d7d3f0c771b78a62c3ad4df1be41b3fd8c767/google_api_core-2.34.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/a0/e5/e9cc221fd75230974d4ef45eb72d2261feca3c110d5554215d516bfe6534/google_api_python_client-2.197.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/00/f3/8508a702c094af5f6e89773f4dfdeee74913df0f41a02c21b5e7dc3d75cd/google_auth-2.57.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/97/be/954c35a62b9e31de66b0a43c225c9b6bb9e0f98d6b1dc110a2308e3644f5/google_auth_httplib2-0.4.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/37/d3/d7dff0d58a9e9244b48044bfb6a898bfcc8ecc42e0031d1bebc695344725/google_auth_oauthlib-1.4.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/cb/64/904dbc9bee128e7b87eeb60da67c8fa4d1a8acdc9a45dd2fedca67ef184d/google_cloud_core-2.7.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/46/0b/816a6ae3c9fd096937d2e5f9670558908811d57d59ddf69dd4b83b326fd1/google_cloud_storage-3.9.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/d1/dd/403949d922d4e261b08b64aaa132af4e456c3b15c8e2a2d9e6ef693f66e2/google_genai-1.66.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/ac/ba/77ef49baf338c03a11deadac984e3161b3f2b4fa4bb5aab160e7ca0fd522/google_resumable_media-2.10.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/e7/c8/e2645aa8ed02fd4c7a2f59d68783b65b1f3cbdfe39a6308e156509d1fee8/googleapis_common_protos-1.75.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/04/4b/29cac41a4d98d144bf5f6d33995617b185d14b22401f75ca86f384e87ff1/h11-0.16.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/7e/22/e85faf23bd72a92d1921e37d674ca56eb298a3c8be31fdecef0ff2b3aaac/h2-4.4.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/71/b4/4a9fcfb2aef6ba44d9073ecd301443aa00b3dac95de5619f2a7de7ec8a91/hpack-4.2.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/7e/f5/f66802a942d491edb555dd61e3a9961140fd64c90bce1eafd741609d334d/httpcore-1.0.9-py3-none-any.whl
	https://files.pythonhosted.org/packages/33/a0/550eec327e5f5c7b732531c489f5307efec41f047b0d703bd4ca1e5ad2db/httplib2-0.32.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/2a/39/e50c7c3a983047577ee07d2a9e53faf5a69493943ec3f6a384bdc792deb2/httpx-0.28.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/d2/fd/6668e5aec43ab844de6fc74927e155a3b37bf40d7c3790e49fc0406b6578/httpx_sse-0.4.3-py3-none-any.whl
	https://files.pythonhosted.org/packages/51/0e/eafef18f1a75e125e68395db21131db0cf868a128ecd2fce69b4df6c584b/huggingface_hub-1.28.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/48/30/47d0bf6072f7252e6521f3447ccfa40b421b6824517f82854703d0f5a98b/hyperframe-6.1.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/57/b0/0e52c878c53f245edd3a11020f20979b3f490f245af532c7cae3027754b5/idna-3.19-py3-none-any.whl
	https://files.pythonhosted.org/packages/8a/db/55a262f3606bebcae07cc14095338471ad7c0bbcaa37707e6f0ee49725b7/importlib_resources-7.1.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/15/aa/0aca39a37d3c7eb941ba736ede56d689e7be91cab5d9ca846bde3999eba6/isodate-0.7.2-py3-none-any.whl
	https://files.pythonhosted.org/packages/04/96/92447566d16df59b2a776c0fb82dbc4d9e07cd95062562af01e408583fc4/itsdangerous-2.2.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/14/2f/967ba146e6d58cf6a652da73885f52fc68001525b4197effc174321d70b4/jmespath-1.1.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/7b/91/984aca2ec129e2757d1e4e3c81c3fcda9d0f85b74670a094cc443d9ee949/joblib-1.5.3-py3-none-any.whl
	https://files.pythonhosted.org/packages/f9/bf/249dcd99b3376375910b7fa922383b57792975c8758f50d44612e749226c/joserfc-1.7.4-py3-none-any.whl
	https://files.pythonhosted.org/packages/73/07/02e16ed01e04a374e644b575638ec7987ae846d25ad97bcc9945a3ee4b0e/jsonpatch-1.33-py2.py3-none-any.whl
	https://files.pythonhosted.org/packages/9e/6a/a83720e953b1682d2d109d3c2dbb0bc9bf28cc1cbc205be4ef4be5da709d/jsonpointer-3.1.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/69/90/f63fb5873511e014207a475e2bb4e8b2e570d655b00ac19a9a0ca0a385ee/jsonschema-4.26.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/41/45/1a4ed80516f02155c51f51e8cedb3c1902296743db0bbc66608a0db2814f/jsonschema_specifications-2025.9.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/5b/30/a96d47df739689ac0001ade0afefc16e3b477fc2fb426b568515fdc8afce/kubernetes-36.0.3-py2.py3-none-any.whl
	https://files.pythonhosted.org/packages/7c/06/c3394327f815fade875724c0f6cff529777c96a1e17fea066deb997f8cf5/langchain-1.2.10-py3-none-any.whl
	https://files.pythonhosted.org/packages/f5/78/2d9980d028ff0523eea503a77c200e2ff252a3a75eb6e7842bcf5f9c979b/langchain_classic-1.0.7-py3-none-any.whl
	https://files.pythonhosted.org/packages/8f/39/5d97e42a3e95dc2a6d71b2f902a3fae71786131e11d01bddb604accb0ebe/langchain_community-0.4.2-py3-none-any.whl
	https://files.pythonhosted.org/packages/84/4c/508a90b9d2e3bd7738fd93cb2ac2178ce734662c75e69b3b81c445f1b360/langchain_core-1.6.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/99/2e/d82db9eec13ad0f72e7aaad5c4bc730ab111934fdc83c85523206eb9b0a0/langchain_protocol-0.0.18-py3-none-any.whl
	https://files.pythonhosted.org/packages/d3/26/1ef06f56198d631296d646a6223de35bcc6cf9795ceb2442816bc963b84c/langchain_text_splitters-1.1.2-py3-none-any.whl
	https://files.pythonhosted.org/packages/5d/60/260e0c04620a37ba8916b712766c341cc5fc685dabc6948c899494bbc2ae/langgraph-1.0.10-py3-none-any.whl
	https://files.pythonhosted.org/packages/05/71/3b475f09bd57d3a5649792c66353312b4432afd843f301739dfcebd157f0/langgraph_checkpoint-4.2.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/69/ef/5ada0bef4013ef5ae53a0ca1de5736517f1076a54d313f156ca545ec65d5/langgraph_prebuilt-1.0.13-py3-none-any.whl
	https://files.pythonhosted.org/packages/be/a5/0196d9c05749c25bc198e4909d68c998bc3120297e14944921baf2f4c384/langgraph_sdk-0.3.15-py3-none-any.whl
	https://files.pythonhosted.org/packages/f1/85/0ad6df25588122760b2b40ec182eafc55532c9e66015c83e16675bd34a29/langsmith-0.11.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/4e/f6/71d6ec9f18da0b2201287ce9db6afb1a1f637dedb3f0703409558981c723/ldap3-2.9.1-py2.py3-none-any.whl
	https://files.pythonhosted.org/packages/0c/29/0348de65b8cc732daa3e33e67806420b2ae89bdce2b04af740289c5c6c8c/loguru-0.7.3-py3-none-any.whl
	https://files.pythonhosted.org/packages/b3/81/4da04ced5a082363ecfa159c010d200ecbd959ae410c10c0264a38cac0f5/markdown_it_py-4.2.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/c9/11/252c6f971dc4f16af1d98a1c469d8ba523aab00d1bb76b4d3bc1ff32eacc/mcp-1.27.2-py3-none-any.whl
	https://files.pythonhosted.org/packages/b3/38/89ba8ad64ae25be8de66a6d463314cf1eb366222074cfda9ee839c56a4b4/mdurl-0.1.2-py3-none-any.whl
	https://files.pythonhosted.org/packages/43/e3/7d92a15f894aa0c9c4b49b8ee9ac9850d6e63b03c9c32c0367a13ae62209/mpmath-1.3.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/c4/ca/d768f77a27d81ed0a6884f2458f8613c31c79b2eb95defbeca2273fd0754/msal-1.38.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/5e/75/bd9b7bb966668920f06b200e84454c8f3566b102183bc55c5473d96cb2b9/msal_extensions-1.3.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/3c/85/9e359fa9279e1d6861faaf9b6f037a3226374deb20a054c3937be6992013/msoffcrypto_tool-6.0.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/79/7b/2c79738432f5c924bef5071f933bcc9efd0473bac3b4aa584a6f7c1c8df8/mypy_extensions-1.1.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/eb/dc/55481808fd70ef1567cf13540ffd4702af3f74b112e35427564b03f79c2d/narwhals-2.25.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/9e/c9/b2622292ea83fbb4ec318f5b9ab867d0a28ab43c5717bb85b0a5f6b3b0a4/networkx-3.6.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/9d/91/04e965f8e717ba0ab4bdca5c112deeab11c9e750d94c4d4602f050295d39/nltk-3.9.4-py3-none-any.whl
	https://files.pythonhosted.org/packages/be/9c/92789c596b8df838baa98fa71844d84283302f7604ed565dafe5a6b5041a/oauthlib-3.3.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/17/d3/b64c356a907242d719fc668b71befd73324e47ab46c8ebbbede252c154b2/olefile-0.47-py2.py3-none-any.whl
	https://files.pythonhosted.org/packages/a4/0e/152509871bf30df6fc38569f52a2db9b55dd41aae957adae50a053ac7778/omegaconf-2.3.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/d0/b1/35b6f9c8cf9318e3dbb7146cc82dab4cf61182a8d5406fc9b50864362895/openai-2.29.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/c0/da/977ded879c29cbd04de313843e76868e6e13408a94ed6b987245dc7c8506/openpyxl-3.1.5-py2.py3-none-any.whl
	https://files.pythonhosted.org/packages/d8/2f/e0cc165af7bb7b44cb00023b9fcaa01a28d1755a059ede28d0cd970c3cec/opensearch_protobufs-1.2.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/ef/63/7abb96bf2e3619acbd27de99e60619bfacfb7c55b68c4792a258e6d92871/opensearch_py-3.2.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/ca/6f/a04e900f465ff3221ccc395522503e2d10e79fa21f2723c8e177aae1e0d1/opentelemetry_api-1.44.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/5e/71/65fd9d54c10b860f87c045ccee1264cab7011268895d3528818a29c1172a/opentelemetry_exporter_otlp_proto_common-1.44.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/54/29/6ae42ba32b153ae0a44ae125f0caff2188bbe62d99c82d1768da30864e72/opentelemetry_exporter_otlp_proto_grpc-1.44.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/d1/7c/8be563d68e93bbefa5c8affb82ddcff91b3ad858ce49957ba7b16fd3e0ab/opentelemetry_proto-1.44.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/e7/23/ff077e61886ee020a17ce9c8b6fa11c601c8d8345b09ea24f605445df62a/opentelemetry_sdk-1.44.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/a6/0e/49df70d9b81fb5cbae4bbf2a49d865b09bcbcbc4eb53f5851b1027738d78/opentelemetry_semantic_conventions-0.65b0-py3-none-any.whl
	https://files.pythonhosted.org/packages/2c/ab/fc8290c6a4c722e5514d80f62b2dc4c4df1a68a41d1364e625c35990fcf3/overrides-7.7.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/63/34/ba1c580383c9eada3711951fef0795c80b829a078d72188184bcab9dd527/packaging-26.3-py3-none-any.whl
	https://files.pythonhosted.org/packages/f1/d9/7fb5aa316bc299258e68c73ba3bddbc499654a07f151cba08f6153988714/pathspec-1.1.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/28/be/0ff05fcd2938fb58ad9219bd54135968342d214737e012d62d43f06a2dd6/platformdirs-4.11.4-py3-none-any.whl
	https://files.pythonhosted.org/packages/61/3a/cfee3c50294f55a2f0f9575052dec2c2a48891ad4b1c2a133b05a87026cd/proto_plus-1.28.3-py3-none-any.whl
	https://files.pythonhosted.org/packages/5c/e0/7b3dee031daae7743609ce3c746565d4a3ed7c2c186479eb48e34e838c64/psycopg-3.3.4-py3-none-any.whl
	https://files.pythonhosted.org/packages/9a/3b/6163796d69c3977d1e4287bea4a6979161cbbdd170ebb430511e8e1999ce/pyasn1-0.6.4-py3-none-any.whl
	https://files.pythonhosted.org/packages/47/8d/d529b5d697919ba8c11ad626e835d4039be708a35b0d22de83a269a6682c/pyasn1_modules-0.4.2-py3-none-any.whl
	https://files.pythonhosted.org/packages/0c/c3/44f3fbbfa403ea2a7c779186dc20772604442dde72947e7d01069cbe98e3/pycparser-3.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/fd/7b/122376b1fd3c62c1ed9dc80c931ace4844b3c55407b6fb2d199377c9736f/pydantic-2.13.4-py3-none-any.whl
	https://files.pythonhosted.org/packages/30/a4/2bffa9f8e804325a09867f0e9d30795c80ea9f8d62560bd1b6ad6220eb2f/pydantic_settings-2.15.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/a6/53/d78dc063216e62fc55f6b2eebb447f6a4b0a59f55c8406376f76bf959b08/pydub-0.25.1-py2.py3-none-any.whl
	https://files.pythonhosted.org/packages/7e/85/545a951eecc270fcd688288c600017e2050a1aacb56c711d208586d3e470/pymdown_extensions-10.21.3-py3-none-any.whl
	https://files.pythonhosted.org/packages/0c/86/e2ffa604eacfbec3f430b1d850e7e04c4101eca1a5828f9ae54bf51dfba4/pypandoc-1.17-py3-none-any.whl
	https://files.pythonhosted.org/packages/10/bd/c038d7cc38edc1aa5bf91ab8068b63d4308c66c4c8bb3cbba7dfbc049f9c/pyparsing-3.3.2-py3-none-any.whl
	https://files.pythonhosted.org/packages/05/89/336673efd0a88956562658aba4f0bbef7cb92a6fbcbcaf94926dbc82b408/pypdf-6.7.5-py3-none-any.whl
	https://files.pythonhosted.org/packages/bd/24/12818598c362d7f300f18e74db45963dbcb85150324092410c8b49405e42/pyproject_hooks-1.2.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/ec/57/56b9bcc3c9c6a792fcbaf139543cee77261f3651ca9da0c93f5c1221264b/python_dateutil-2.9.0.post0-py2.py3-none-any.whl
	https://files.pythonhosted.org/packages/0d/17/c5c6b53ddc18f297992099b3d9ec16c855c0ccc83263a21fe4d1c625ec6c/python_dotenv-1.2.3-py3-none-any.whl
	https://files.pythonhosted.org/packages/6b/01/f804208061b504894546fddc479f6075e0f00dfe88cb1703dafaa8c3c67e/python_engineio-4.13.5-py3-none-any.whl
	https://files.pythonhosted.org/packages/65/d9/1093a9d6d22d04d433003c96b9b1d46741b43fee5b11ece5098297737fce/python_mimeparse-2.0.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/e1/04/e8135ebd1ad02c56ec633277529b2602ff99ff634be76cdba5744cf554fd/python_multipart-0.0.32-py3-none-any.whl
	https://files.pythonhosted.org/packages/d9/4f/00be2196329ebbff56ce564aa94efb0fbc828d00de250b1980de1a34ab49/python_pptx-1.0.2-py3-none-any.whl
	https://files.pythonhosted.org/packages/72/dc/0decaf5da92a7a969374474025787102d811d42aed1d32191fa338620e15/python_socketio-5.16.2-py3-none-any.whl
	https://files.pythonhosted.org/packages/51/64/bcf8632ed2b7a36bbf84a0544885ffa1d0b4bcf25cc0903dba66ec5fdad9/pytube-15.0.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/ec/dd/96da98f892250475bdf2328112d7468abdd4acc7b902b6af23f4ed958ea0/pytz-2026.2-py2.py3-none-any.whl
	https://files.pythonhosted.org/packages/7e/92/345823838ae367c59b63e03aef9c331f485370f9df6d049256a61a28f06d/pyxlsb-1.0.10-py2.py3-none-any.whl
	https://files.pythonhosted.org/packages/2a/21/f691fb2613100a62b3fa91e9988c991e9ca5b89ea31c0d3152a3210344f9/rank_bm25-0.2.2-py3-none-any.whl
	https://files.pythonhosted.org/packages/55/ed/0ee9b9281986974be9d2406ae0134c8d7c91d2fc613f16ffda9701eeda6f/rapidocr-3.9.2-py3-none-any.whl
	https://files.pythonhosted.org/packages/fd/0a/c2345ebf1ebe70840ce3f6c6ee612f8fa749cfbd1b03069c53bf0c62aaad/redis-8.0.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/2c/58/ca301544e1fa93ed4f80d724bf5b194f6e4b945841c5bfd555878eea9fcb/referencing-0.37.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/a0/f4/c67b0b3f1b9245e8d266f0f112c500d50e5b4e83cb6f3b71b6528104182a/requests-2.34.2-py3-none-any.whl
	https://files.pythonhosted.org/packages/3b/5d/63d4ae3b9daea098d5d6f5da83984853c1bbacd5dc826764b249fe119d24/requests_oauthlib-2.0.0-py2.py3-none-any.whl
	https://files.pythonhosted.org/packages/3f/51/d4db610ef29373b879047326cbf6fa98b6c1969d6f6dc423279de2b1be2c/requests_toolbelt-1.0.0-py2.py3-none-any.whl
	https://files.pythonhosted.org/packages/19/71/39c7c0d87f8d4e6c020a393182060eaefeeae6c01dab6a84ec346f2567df/rich-13.9.4-py3-none-any.whl
	https://files.pythonhosted.org/packages/03/19/90d7d4ed51932c022d53f1d02d564b62d10e272692a1f9b76425c1ad2a02/s3transfer-0.16.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/bf/03/ee99a6b030e7a2e056547729f8a4709dd93e13d9c6f07590f74c395c4017/sentence_transformers-5.5.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/95/9c/c510029fc6ef33a6275cd2c5d3cecd6613dfd6aa401d57c54f1c18852ccf/setuptools-84.0.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/e0/f9/0595336914c5619e5f28a1fb793285925a8cd4b432c9da0a987836c7f822/shellingham-1.5.4-py2.py3-none-any.whl
	https://files.pythonhosted.org/packages/52/59/0782e51887ac6b07ffd1570e0364cf901ebc36345fea669969d2084baebb/simple_websocket-1.1.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/b7/ce/149a00dd41f10bc29e5921b496af8b574d8413afcd5e30dfa0ed46c2cc5e/six-1.17.0-py2.py3-none-any.whl
	https://files.pythonhosted.org/packages/e9/44/75a9c9421471a6c4805dbf2356f7c181a29c1879239abab1ea2cc8f38b40/sniffio-1.3.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/37/c3/6eeb6034408dac0fa653d126c9204ade96b819c936e136c5e8a6897eee9c/socksio-1.0.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/eb/dc/ad025c1ee131eba60c69f4dd5779b18fcf1e6b21a343e2162a84d5d133c7/soupsieve-2.9.2-py3-none-any.whl
	https://files.pythonhosted.org/packages/dd/3a/764912c58293d95b6dcdf4cc255f9d10de310580ced547b082eb9d72018c/sse_starlette-3.4.8-py3-none-any.whl
	https://files.pythonhosted.org/packages/c8/cb/6a6a47d5b464bd08695d254f3da6e7986cc70c9fa5d778eda57538edfe56/starlette-1.6.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/d4/d7/2580440b73549ea453351de57bdaafc629177fc6135810b20fd40cf70e6f/starlette_compress-1.7.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/d2/ce/fc699345a3cdfb4425b5dc1e446f1b49702ac55907a6a4d5d806f2512dae/starsessions-2.2.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/a2/09/77d55d46fd61b4a135c444fc97158ef34a095e5681d0a6c10b75bf356191/sympy-1.14.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/d7/c1/eb8f9debc45d3b7918a32ab756658a0904732f75e555402972246b0b8e71/tenacity-9.1.4-py3-none-any.whl
	https://files.pythonhosted.org/packages/32/d5/f9a850d79b0851d1d4ef6456097579a9005b31fea68726a4ae5f2d82ddd9/threadpoolctl-3.6.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/f9/1c/01bfd571a64e7f270e6bab5e33777debe0edc56759233ce84f27dec92d14/tqdm-4.70.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/29/fb/162a66789c65e5afa3b051309240c26bf37fbc8fea285b4546ae747995a2/transformers-5.5.4-py3-none-any.whl
	https://files.pythonhosted.org/packages/43/89/9518bc0c3929bee36b3a4a8e3daddd6e03f92f9961c66d4983b837160543/typer-0.27.1-py3-none-any.whl
	https://files.pythonhosted.org/packages/67/81/4add07e5172b7ac40d8ed5ff580409a7801a4fe26d529bdd915401dabfbe/typing_inspection-0.4.4-py3-none-any.whl
	https://files.pythonhosted.org/packages/49/d3/b8441a820a491ddfc024b0b0cf0393375b75ea13866d9c66727e54c2fc80/typing_extensions-4.16.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/9e/a4/017a7a6cbe387d961a688ec31364ae60a5c4e22c96ae9921b79a947c855d/tzlocal-5.4.4-py3-none-any.whl
	https://files.pythonhosted.org/packages/a9/99/3ae339466c9183ea5b8ae87b34c0b897eda475d2aec2307cae60e5cd4f29/uritemplate-4.2.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/7f/3e/5db95bcf282c52709639744ca2a8b149baccf648e39c8cc87553df9eae0c/urllib3-2.7.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/45/ec/dbb7e5a6b91f86bfb9eb7d2988a2730907b6a729875b949c7f022e8b88fa/uvicorn-0.51.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/fa/6e/3e955517e22cbdd565f2f8b2e73d52528b14b8bcfdb04f62466b071de847/validators-0.35.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/96/42/3e5985a0a7e57de470b320c6d6a1a67c844f6737a587f3d44dd13d1819e7/wcwidth-0.8.2-py3-none-any.whl
	https://files.pythonhosted.org/packages/34/db/b10e48aa8fff7407e67470363eac595018441cf32d5e1001567a7aeba5d2/websocket_client-1.9.0-py3-none-any.whl
	https://files.pythonhosted.org/packages/a4/f5/10b68b7b1544245097b2a1b8238f66f2fc6dcaeb24ba5d917f52bd2eed4f/wsproto-1.3.2-py3-none-any.whl
	https://files.pythonhosted.org/packages/1a/62/c8d562e7766786ba6587d09c5a8ba9f718ed3fa8af7f4553e8f91c36f302/xlrd-2.0.2-py2.py3-none-any.whl
	https://files.pythonhosted.org/packages/3a/0c/3662f4a66880196a590b202f0db82d919dd2f89e99a27fadef91c4a33d41/xlsxwriter-3.2.9-py3-none-any.whl
	https://files.pythonhosted.org/packages/be/95/129ea37efd6cd6ed00f62baae6543345c677810b8a3bf0026756e1d3cf3c/youtube_transcript_api-1.2.4-py3-none-any.whl
	https://files.pythonhosted.org/packages/3e/38/7859ff46355f76f8d19459005ca000b6e7012f2f1ca597746cbcd1fbfe5e/antlr4-python3-runtime-4.9.3.tar.gz
	amd64? (
		https://files.pythonhosted.org/packages/3c/2e/8d0c2ab90a8c1d9a24f0399058ab8519a3279d1bd4289511d74e909f060e/markupsafe-3.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/8b/9d/b3589d3877982d4f2329302ef98a8026e7f4443c765c46cfecc8858c6b4b/pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/8a/2b/514fce8a7df81cf5bad7ff7865de7ac0c5776a38cc043475c4703eb7fe8b/sqlalchemy-2.0.50-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/57/d8/8d44036d7eb7b6a8ec4c5494ea0c8c8b94fbc0ed3991c1a7adf230df03bf/aiohttp-3.13.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/6f/86/5363df11b86d02cf3662208e7406496327649cc90eb365bf6f4e8a54a41f/argon2_cffi_bindings-26.1.0-cp310-abi3-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/27/3a/204dbfc3e08eb4cdc6e6ff57be02150bc44523ebdb50182d10025792ebd9/av-18.1.0-cp311-abi3-manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/24/b4/11f8a31d8b67cca3371e046db49baa7c0594d71eb40ac8121e2fc0888db0/bcrypt-5.0.0-cp39-abi3-manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/1f/0e/36044316b65ca471d3bb6d3703fd06fb50c6b727c3562f6a5a3153634f88/black-26.5.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/03/a7/03aa61fbc3c5cbf99b44d158665f9b0dd3d8059be16c460208d9e385c837/brotli-1.2.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl
		https://files.pythonhosted.org/packages/99/39/e7410db7f6f56de57744ea52a115084ceb2735f4d44973f349bb92136586/brotlicffi-1.2.0.1-cp38-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/b1/db/dceb9dd5b231e1da801793f8acc9f3c52a7e1afe40bb1aae37e02b0faad5/cffi-2.1.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl
		https://files.pythonhosted.org/packages/e5/59/a32a241d861cf180853a11c8e5a67641cb1b2af13c3a5ccce83ec07e2c9f/chardet-7.4.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/6f/89/bb5108dc6c3651dca963f2b0a3ba19bbcb370c94e1b6d3e0e844a58e6dca/charset_normalizer-3.5.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/e6/ec/0c42039e80b9acc534f67b73b7a42471948042859b3a64867b50a4a77fa3/chromadb-1.5.9-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
		https://files.pythonhosted.org/packages/95/38/0d29a6fd7d0d1373f0c0c88a04ba20e359b257753ac497564cd660fc1d55/cryptography-48.0.0-cp311-abi3-manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/47/c9/976a565398a03fb2973cbe5edd5ca03c4332d86b634799e0ee562420d3bc/ctranslate2-4.8.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/77/c7/2342da9830e3e9d4870305ca5d2091d2a83284f2953079b7bdd3b5e029d8/fonttools-4.63.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl
		https://files.pythonhosted.org/packages/6a/bd/d91c5e39f490a49df14320f4e8c80161cfcce09f1e2cde1edd16a551abb3/frozenlist-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl
		https://files.pythonhosted.org/packages/ce/a9/a780cc66f86335a6019f557a8aaca8fbb970728f0efd2430d15ff1beae0e/google_crc32c-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl
		https://files.pythonhosted.org/packages/78/ac/5c5b959999b6f09c3026b5dfe171575bc3121c5236ce74f495096f25b203/greenlet-3.5.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/b2/78/c9e81f806ac704b6b145cb01628db398985b1f8dfdc10e23b55fb0902b3d/grpcio-1.83.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl
		https://files.pythonhosted.org/packages/67/4e/a28359bf1c1ecf11eba22123168c138698f7cb576ac678f5a2e16cd5da08/hf_xet-1.6.0-cp38-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl
		https://files.pythonhosted.org/packages/1e/8c/440369f727dcb856f3eeda238d6e67781b180feaa831bd28997d8af10c3b/hiredis-3.4.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/e3/a6/febbb8b8db0f58b38e44ad6cb946e6a255ae49b55f2e8543408fb7501ccd/httptools-0.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl
		https://files.pythonhosted.org/packages/a8/d2/4839422241aa12860ce597b20068727094ba0bc480723c74924ca5bad483/jiter-0.16.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
		https://files.pythonhosted.org/packages/08/f6/af32e23e563971ffb0fb86be52bc5be5c2c118858ffc119bf6a9039b173d/lxml-6.1.1-cp312-cp312-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/e5/e2/51ed62063b44d10b06d975ac87af287729eeb5e3ed9772f7584a17983e90/mmh3-5.2.1-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl
		https://files.pythonhosted.org/packages/f3/8d/5e5be3ced1d12966fefb5c4ea3b2a5b480afcea36406559442c6e31d4a48/multidict-6.7.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/3a/5f/62d28cf019460c7f1394105b4d49d9911a9c444cb77ab0bd95a204c5a6de/numpy-2.5.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/7c/43/2a4e04f8dbeffad19bbcced4bcd4289bf478921518437404d6b92bdf213b/onnxruntime-1.26.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/4b/33/b5db29a6c00eb8f50708110d8d453747ca125c8b805bc437b289dbdcc057/opencv_python_headless-4.13.0.92-cp37-abi3-manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/0e/a4/82b7a2fe5d8a67a59ed831b24d59a3d46ea7d207b66e1602d376541d94a6/orjson-3.11.9-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
		https://files.pythonhosted.org/packages/7b/ba/795b1036888542c9113269a3f5690ab53dd2258c6fb17676ac4bd44fcf94/ormsgpack-1.12.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
		https://files.pythonhosted.org/packages/65/b6/09b01cdbc15224e2850365192d17b7bdebb8bdbd8780ed221fcdf0d9a515/pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/43/e3/fdc657359e919462369869f1c9f0e973f353f9a9ee295a39b1fea8ee1a77/pillow-12.2.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/34/bb/9b66986b7ecf2eff987134cd94bde533142e3085d6f67531f1a369ceaaae/primp-1.3.1-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
		https://files.pythonhosted.org/packages/14/15/5574111ae50dd6e879456888c0eadd4c5a869959775854e18e18a6b345f3/propcache-0.5.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/c7/f8/bd5804695ba400e423c33fd4d9f58c28d86633d5ba1945c36ff3967d98cb/protobuf-7.36.0-cp310-abi3-manylinux2014_x86_64.whl
		https://files.pythonhosted.org/packages/b5/70/5d8df3b09e25bce090399cf48e452d25c935ab72dad19406c77f4e828045/psutil-7.2.2-cp36-abi3-manylinux2010_x86_64.manylinux_2_12_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/7c/b1/b83136c6e510593d9b0c759ba5384337bc4ad82d19fda675adc4b2703c84/psycopg_binary-3.3.4-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl
		https://files.pythonhosted.org/packages/bb/1b/2168d6050e52ff1e6cefc61d600723870bf569cbf41d13db939c8cf97a16/pyarrow-20.0.0-cp312-cp312-manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/af/36/4e44a0688efe26434bf378b4565b01ac94f81422e8a5746291a03472cd56/pybase64-1.5.0-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl
		https://files.pythonhosted.org/packages/a4/d0/c67967a10abd89529cb9aded9d73f43e5de00cf21243638ef529f6757262/pycares-5.0.1-cp312-cp312-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/7a/06/6e3e241882bf7d6ab23d9c69ba4e85f1ec47397cbbeee948a16cf75e21ed/pyclipper-1.4.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl
		https://files.pythonhosted.org/packages/00/ec/7363504d395d6785f159830430e24ecb1e9d074e2ce364db39fbc104d94f/pycrdt-0.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
		https://files.pythonhosted.org/packages/5f/97/2aab507d3d00ca626e8e57c1eac6a79e4e5fbcc63eb99733ff55d1717f65/pydantic_core-2.46.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
		https://files.pythonhosted.org/packages/bf/3c/2d5297d82286f6f3d92770289fd439956b201c0a4fc7e72efb9b2293758e/pytokens-0.4.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/cc/1e/3fbe2fa1e8cebd62f3bb7d3321cff1640aca2e240b51d9bd624aad949260/regex-2026.5.9-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/04/8f/d2f3f532616be4d06c316ef119683e832bd3d41e112bf3a88f4151c95b17/rpds_py-2026.6.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
		https://files.pythonhosted.org/packages/28/50/f203ff3a3ddfe19308efc83c5a3a29ed02bf786732ec35e68bf9162f3365/safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
		https://files.pythonhosted.org/packages/6c/c2/63fdda36c56437eeb44aaf9493c8bcd62ce230ab1598924fc626ffbfa943/scikit_learn-1.9.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/df/64/ff35eb9e54894cf471ff4716abd3c81eb0a0626869217ce3e6ba4ccf17d7/scipy-1.18.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/04/88/14f2f4a2b922d8b39be45bf63d79e6cd3a9b2f248b2fcb98a69b12af12f5/sentencepiece-0.2.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/b9/37/e781683abac55dde9771e086b790e554811a71ed0b2b8a1e789b7430dd44/shapely-2.1.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl
		https://files.pythonhosted.org/packages/57/5e/70bdd9579b35003a489fc850b5047beeda26328053ebadc1fb60f320f7db/soundfile-0.13.1-py2.py3-none-manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/34/de/2ca96b07a82d972b74fe4b46de055b79c904e45c7eab699354a0bfa697dc/tiktoken-0.13.0-cp312-cp312-manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/2e/76/932be4b50ef6ccedf9d3c6639b056a967a86258c6d9200643f01269211ca/tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
		https://download-r2.pytorch.org/whl/cpu/torch-2.10.0%2Bcpu-cp312-cp312-manylinux_2_28_x86_64.whl -> torch-2.10.0+cpu-cp312-cp312-manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/59/30/91795bd01e17a13661280d4899fbf38fb05e3f38e873f9aaec106ec30aa0/uuid_utils-0.17.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
		https://files.pythonhosted.org/packages/5f/6f/e62b4dfc7ad6518e7eff2516f680d02a0f6eb62c0c212e152ca708a0085e/uvloop-0.22.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/22/24/ed72f68cbc1333ca9b9f2200aa048bb6658ae41709bc1caad4310f4bdffd/watchfiles-1.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
		https://files.pythonhosted.org/packages/fe/ed/f1831681fce0e3242346e5458486003c5f124ed69e5e0b847fd029db4973/websockets-16.1.1-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl
		https://files.pythonhosted.org/packages/83/97/31bd8b8279e6935a0719f6910ced15e9d5a2cd554b253f6027ce1b5a1c2c/xxhash-4.0.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/d6/d0/d56c859b8222116f5d68459199f48359e0bf121b6f65a69bf329b3602ba0/yarl-1.24.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
		https://files.pythonhosted.org/packages/53/60/7be26e610767316c028a2cbedb9a3beabdbe33e2182c373f71a1c0b88f36/zstandard-0.25.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl
	)
	arm64? (
		https://files.pythonhosted.org/packages/1e/2c/799f4742efc39633a1b54a92eec4082e4f815314869865d876824c257c1e/markupsafe-3.0.3-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/ed/23/7a778b6bd0b9a8039df8b1b1d80e2e2ad78aa04171592c8a5c43a56a6af4/pyyaml-6.0.3-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/f5/2c/191dd58a248fd2cfd4780fa82c375c505e4ad98c8b522fa69ec492130d77/sqlalchemy-2.0.50-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/67/84/c9ecc5828cb0b3695856c07c0a6817a99d51e2473400f705275a2b3d9239/aiohttp-3.13.5-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/7e/e4/ad91d8297638aa2258aad4501c306aca99480dfe76ccd638173fa3702db9/argon2_cffi_bindings-26.1.0-cp310-abi3-manylinux_2_26_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/d9/84/2464ffb64c08c5ce8b522c8e74594714414e3b0575267652c5c51c0574b9/av-18.1.0-cp311-abi3-manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/36/c4/ed00ed32f1040f7990dac7115f82273e3c03da1e1a1587a778d8cea496d8/bcrypt-5.0.0-cp39-abi3-manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/94/51/f975cae76d44274cc2868dc9040ac5d58d464784610234455b4e7b19c6ef/black-26.5.1-py3-none-any.whl
		https://files.pythonhosted.org/packages/3d/6f/feba03130d5fceadfa3a1bb102cb14650798c848b1df2a808356f939bb16/brotli-1.2.0-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/b1/7a/ac4ee56595a061e3718a6d1ea7e921f4df156894acffb28ed88a1fd52022/brotlicffi-1.2.0.1-cp38-abi3-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/44/de/f98430906df1545ffde0d543dd124a7a439bc2cd32b36b9c53f805df7333/cffi-2.1.1-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.whl
		https://files.pythonhosted.org/packages/36/21/edb36ad5dfa48d7f8eed97ab43931ecdaa8c15166c21b1d614967e49d681/chardet-7.4.3-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/9a/4c/be49ada26b1f0232d57aa89bbebf997a5cc2332a5616b6eca26ff680044d/charset_normalizer-3.5.1-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/38/4e/937bc4d2e6f8ab9664ec79931fbbd69efff47e513ec2924b071e4b0ff774/chromadb-1.5.9-cp39-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
		https://files.pythonhosted.org/packages/14/d5/e9c4ef932c8d800490c34d8bd589d64a31d5890e27ec9e9ad532be893294/cryptography-48.0.0-cp311-abi3-manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/2c/d4/03428106134a0a58922461074f8942f92c5ed0bb3a8d018677ad64a9c476/ctranslate2-4.8.1-cp312-cp312-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/44/04/0b91d8e916e92ad1fac9e4624760baf0fd5ff2ead614c2f68fb21373f03f/fonttools-4.63.0-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/8f/83/f61505a05109ef3293dfb1ff594d13d64a2324ac3482be2cedc2be818256/frozenlist-1.8.0-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/21/3f/3457ea803db0198c9aaca2dd373750972ce28a26f00544b6b85088811939/google_crc32c-1.8.0-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.whl
		https://files.pythonhosted.org/packages/35/73/60e4bbcc89252037b18087f2ec16405d5b2d5be42dde191bbf3667e96102/greenlet-3.5.5-cp312-cp312-manylinux_2_24_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/7b/5f/734e72e7b9f79bcf0b2c270b8d3bca0e4ebb97a27a50d06240b145f6d41e/grpcio-1.83.0-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.whl
		https://files.pythonhosted.org/packages/9a/69/1f0cbc2fb22ae6082d094f743d1b8945a3f36f6089cb95f42b7ee348cda7/hf_xet-1.6.0-cp38-abi3-manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/98/99/62340215f80e59680c79ae5080c5422311da105870c57bbefc5d87487025/hiredis-3.4.0-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/b7/e4/f90a0df0b83beff265b7e3b65f2a4cefd95792d4be0ac3e16049f2acd3c2/httptools-0.8.0-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/88/6c/59bd309cab4460c54cf1079f3eb7fe7af6a4c895c5c957a53378693bad2b/jiter-0.16.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
		https://files.pythonhosted.org/packages/29/91/317b332636bfc7bddcff828d41b3307f50043f4b237e40849c333d80fa1a/lxml-6.1.1-cp312-cp312-manylinux_2_26_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/75/ce/12a7524dca59eec92e5b31fdb13ede1e98eda277cf2b786cf73bfbc24e81/mmh3-5.2.1-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/fd/80/c959c5933adedb9ac15152e4067c702a808ea183a8b64cf8f31af8ad3155/multidict-6.7.1-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/e5/21/4947e0e9d6c9fc2e2ff15b8949049ee44f63adb9cacc729ab8793f97e712/numpy-2.5.2-cp312-cp312-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/f6/a0/3f9d896a0385a36bd04345d6d0b802821a5782adde562e7e135f6bb71c73/onnxruntime-1.26.0-cp312-cp312-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/8f/b4/b7bcbf7c874665825a8c8e1097e93ea25d1f1d210a3e20d4451d01da30aa/opencv_python_headless-4.13.0.92-cp37-abi3-manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/ab/86/1c3a47df3bc8191ea9ac51603bbb872a95167a364320c269f2557911f406/orjson-3.11.9-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
		https://files.pythonhosted.org/packages/c0/68/468de634079615abf66ed13bb5c34ff71da237213f29294363beeeca5306/ormsgpack-1.12.2-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
		https://files.pythonhosted.org/packages/31/a8/fa2535168fffcedf67f4f6de28d2dd903a747ca7c8ea6989451aaeb3a92f/pandas-3.0.3-cp312-cp312-manylinux_2_24_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/2b/54/1789c455ed10176066b6e7e6da1b01e50e36f94ba584dc68d9eebfe9156d/pillow-12.2.0-cp312-cp312-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/9c/99/f4248d8d833d43fd8ba78208f2f4bf7fba7d3aec8c516090a95d18d6f550/primp-1.3.1-cp310-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
		https://files.pythonhosted.org/packages/44/c7/085d0cd63062e84044e3f05797749c3f8e3938ff3aeb0eb2f69d43fafc91/propcache-0.5.2-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/f0/15/5162230af4912697f0fe406f6800f80760945babcff0e2c2fe6c84ef2d5d/protobuf-7.36.0-cp310-abi3-manylinux2014_aarch64.whl
		https://files.pythonhosted.org/packages/63/65/37648c0c158dc222aba51c089eb3bdfa238e621674dc42d48706e639204f/psutil-7.2.2-cp36-abi3-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/67/8d/a9821e2a648afe6091989929982a3b0f00b2631a859cb81379728f08fb75/psycopg_binary-3.3.4-cp312-cp312-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/10/f7/da98ccd86354c332f593218101ae56568d5dcedb460e342000bd89c49cc1/pyarrow-20.0.0-cp312-cp312-manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/aa/d1/fc02005906fd48081b7b8f077cd422a55399fa351c2a6d3e5fed951794ce/pybase64-1.5.0-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.whl
		https://files.pythonhosted.org/packages/0e/ea/f431599f1ac42149ea4768e516db7cdae3a503a6646319ae63ab66da1486/pycares-5.0.1-cp312-cp312-manylinux_2_26_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/cf/f4/3418c1cd5eea640a9fa2501d4bc0b3655fa8d40145d1a4f484b987990a75/pyclipper-1.4.0-cp312-cp312-manylinux_2_24_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/cc/e5/595d8582952be13060556f2faa29bff2b10b9247011a1a5882240fea6f33/pycrdt-0.13.1-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
		https://files.pythonhosted.org/packages/8e/bc/f47d1ff9cbb1620e1b5b697eef06010035735f07820180e74178226b27b3/pydantic_core-2.46.4-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
		https://files.pythonhosted.org/packages/f0/e6/5bbc3019f8e6f21d09c41f8b8654536117e5e211a85d89212d59cbdab381/pytokens-0.4.1-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/d8/dd/ba103dc19614e25f3880800ca67ce093d6e21b325d72b8383c7bf906e9fa/regex-2026.5.9-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/21/63/4239893be1c4d09b709b1a8f6be4188f0870084ff547f46606b8a75f1b03/rpds_py-2026.6.3-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
		https://files.pythonhosted.org/packages/09/7d/65a7de0af421317bb36a067241e4235fff194eed60b961ed6d3f59a3fc60/safetensors-0.8.0-cp310-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
		https://files.pythonhosted.org/packages/a0/ee/5adbc77656b71f9456a2f5a7a9fdb4bcf9207a6b962889f1c2f9323afa4e/scikit_learn-1.9.0-cp312-cp312-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/75/9a/2e71719f31eaefe0e3a1706c4a1ded94e664bfd95ffca2b219a671faee01/scipy-1.18.1-cp312-cp312-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/89/fa/d3d5ebcba3cb9e6d3775a096251860c41a6bc53a1b9461151df83fe93255/sentencepiece-0.2.1-cp312-cp312-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/26/29/a5397e75b435b9895cd53e165083faed5d12fd9626eadec15a83a2411f0f/shapely-2.1.2-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.whl
		https://files.pythonhosted.org/packages/58/ae/c0e4a53d77cf6e9a04179535766b3321b0b9ced5f70522e4caf9329f0046/soundfile-0.13.1-py2.py3-none-manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/74/ed/6bb8d05b9f731f749fee5c6f5ca63e981143c826a5985877330507bd13b7/tiktoken-0.13.0-cp312-cp312-manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/d6/84/7990e799f1309a8b87af6b948f31edaa12a3ed22d11b352eaf4f4b2e5753/tokenizers-0.22.2-cp39-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
		https://download-r2.pytorch.org/whl/cpu/torch-2.10.0%2Bcpu-cp312-cp312-manylinux_2_28_aarch64.whl -> torch-2.10.0+cpu-cp312-cp312-manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/55/fb/d59695f0f8db065b93c63316eaafa05a22d75a0486978a33736c52c646d5/uuid_utils-0.17.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
		https://files.pythonhosted.org/packages/24/68/a6ac446820273e71aa762fa21cdcc09861edd3536ff47c5cd3b7afb10eeb/uvloop-0.22.1-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/13/01/b32a967c56fb3e3e5be3db52c3d3b87fa4513aa367d8ed1ad96d42952e5f/watchfiles-1.2.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
		https://files.pythonhosted.org/packages/6f/79/4ff9dcc1bb46f6b4c536936dde1fd60f9b564f3304307274db97f4c9496d/websockets-16.1.1-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/de/bb/542005206af59518bc8d78a210f1e0172217bc53beb32f64a5b632e72b6b/xxhash-4.0.1-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/20/16/e618c875c73e0e39611f20a581b3d5e8d59b8857bf001bee3263044c6deb/yarl-1.24.5-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
		https://files.pythonhosted.org/packages/1e/15/efef5a2f204a64bdb5571e6161d49f7ef0fffdbca953a615efbec045f60f/zstandard-0.25.0-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.whl
	)
"

SRC_URI="
	https://files.pythonhosted.org/packages/b0/63/87edc2cade790151d1595b05fbba1bde0c2df1fb2d0be80f2863667816e0/open_webui-0.11.0-py3-none-any.whl
	${OPEN_WEBUI_WHEEL_SRC_URI}
"
S="${WORKDIR}"

LICENSE="
	Open-WebUI
	0BSD
	Apache-2.0
	BSD
	BSD-2
	HPND
	ISC
	LGPL-2.1
	LGPL-3
	LGPL-3+
	MIT
	MPL-2.0
	PSF-2
	Unlicense
	ZPL
	|| ( Apache-2.0 BSD )
	|| ( Apache-2.0 BSD-2 )
	|| ( Apache-2.0 MIT )
	|| ( BSD Apache-2.0 )
	|| ( MPL-2.0 MIT )
"
# The above dependency-closure license list is a best-effort audit at the
# PyPI metadata level (License classifiers, PEP 639 license_expression /
# short license fields, and well-established public knowledge for a
# handful of very common packages lacking either) across all 256 vendored
# runtime dependencies -- see scripts/generate-open-webui-wheel-deps.py
# and the accompanying packaging report. It is NOT a byte-level source
# audit of every bundled native library the way dev-util/semgrep-bin's
# LICENSE comment is (that covered ~30 bundled .so files; this bundles
# 256 independent PyPI packages, several of which themselves bundle their
# own further native code, e.g. torch, onnxruntime, opencv-python-headless
# -- auditing each of those to that same depth was not attempted here).
# Treat this as reasonably reliable but not exhaustively verified.

SLOT="0"
KEYWORDS="~amd64 ~arm64"
REQUIRED_USE="${PYTHON_REQUIRED_USE}"

# `strip`: the compiled native extensions inside several vendored wheels
# (torch, onnxruntime, numpy, scipy, tokenizers, pyarrow, ...) are
# manylinux-repaired prebuilt binaries whose bundled shared libraries and
# symbol-versioning metadata Portage's default `strip` pass can corrupt,
# the same failure mode documented in dev-util/semgrep-bin for its one
# prebuilt binary.
#
# `mirror`: NOT a license concern -- the Open WebUI License's clauses 1-2
# (see licenses/Open-WebUI) explicitly permit redistribution "in source
# and binary forms", and every one of the 256 vendored dependencies'
# licenses (see the LICENSE comment above) is a standard OSS license that
# permits redistribution too, so nothing here is legally restricted from
# being mirrored. The reason is purely practical: this vendors ~2GB of
# large prebuilt binary wheels (see scripts/generate-open-webui-wheel-deps.py)
# individually fetched straight from files.pythonhosted.org, which
# already serves them from a CDN -- pushing another ~2GB copy of already-
# well-distributed upstream binaries through Gentoo's own distfile mirror
# network would just be redundant load on that shared infrastructure for
# no real availability benefit, the same practical (not license-driven)
# reasoning under which large prebuilt binary blobs are conventionally
# kept off Gentoo's mirror tier elsewhere in the tree. This is a personal
# overlay with no mirror tier of its own today, so this RESTRICT is inert
# in practice right now; it is kept so the ebuild states the correct
# intent if this overlay (or these files) ever end up mirrored.
RESTRICT="mirror strip"

pkg_setup() {
	[[ ${OPEN_WEBUI_WHEEL_DEPS_VERSION} == ${PV} ]] ||
		die "OPEN_WEBUI_WHEEL_DEPS_VERSION (${OPEN_WEBUI_WHEEL_DEPS_VERSION}) does not match PV (${PV}); the pasted-in dependency arrays were generated for a different version"

	python-single-r1_pkg_setup
}

RDEPEND="
	${PYTHON_DEPS}
	acct-group/open-webui
	acct-user/open-webui
"
BDEPEND="
	${PYTHON_DEPS}
	$(python_gen_cond_dep '
		dev-python/pip[${PYTHON_USEDEP}]
		dev-python/setuptools[${PYTHON_USEDEP}]
		dev-python/wheel[${PYTHON_USEDEP}]
	')
"

# The vendored wheels bundle their own compiled native extensions
# (manylinux-repaired, self-contained); leave them exactly as installed
# by pip rather than letting QA machinery try to "fix" them.
QA_PREBUILT="usr/lib*/open-webui/site-packages/*"

src_compile() {
	local antlr_wheel_dir="${T}/antlr-wheel"
	mkdir -p "${antlr_wheel_dir}" || die

	# PyPI publishes antlr4-python3-runtime-4.9.3 only as an sdist.  Build
	# its pure-Python wheel here, never in src_install, using only the
	# pip/setuptools/wheel implementations declared in BDEPEND.  The pip
	# environment variables and options make network access impossible.
	PIP_NO_INDEX=1 PIP_NO_CACHE_DIR=1 PIP_NO_INPUT=1 \
	PIP_DISABLE_PIP_VERSION_CHECK=1 PIP_ROOT_USER_ACTION=ignore \
	PIP_PROGRESS_BAR=off \
	"${EPYTHON}" -m pip wheel \
		--no-index --no-deps --no-build-isolation \
		--wheel-dir "${antlr_wheel_dir}" \
		"${DISTDIR}/antlr4-python3-runtime-4.9.3.tar.gz" ||
		die "building the Antlr runtime wheel failed"

	local antlr_wheels=( "${antlr_wheel_dir}"/antlr4_python3_runtime-4.9.3-py3-none-any.whl )
	[[ ${#antlr_wheels[@]} -eq 1 && -f ${antlr_wheels[0]} ]] ||
		die "expected exactly one antlr4_python3_runtime-4.9.3-py3-none-any.whl"
	local produced_wheels=( "${antlr_wheel_dir}"/*.whl )
	[[ ${#produced_wheels[@]} -eq 1 && -f ${produced_wheels[0]} ]] ||
		die "Antlr build produced an unexpected number of wheels"
}

src_install() {
	local sitedir="${ED}/usr/$(get_libdir)/open-webui/site-packages"
	mkdir -p "${sitedir}" || die

	local wheels=() entry filename
	for entry in "${OPEN_WEBUI_WHEELS_COMMON[@]}"; do
		filename=${entry##*|}
		[[ ${filename} == antlr4-python3-runtime-4.9.3.tar.gz ]] && continue
		[[ ${filename} == *.whl ]] || die "non-wheel dependency in install set: ${filename}"
		wheels+=( "${DISTDIR}/${filename}" )
	done
	if use amd64; then
		for entry in "${OPEN_WEBUI_WHEELS_AMD64[@]}"; do
			filename=${entry##*|}
			[[ ${filename} == *.whl ]] || die "non-wheel dependency in install set: ${filename}"
			wheels+=( "${DISTDIR}/${filename}" )
		done
	fi
	if use arm64; then
		for entry in "${OPEN_WEBUI_WHEELS_ARM64[@]}"; do
			filename=${entry##*|}
			[[ ${filename} == *.whl ]] || die "non-wheel dependency in install set: ${filename}"
			wheels+=( "${DISTDIR}/${filename}" )
		done
	fi
	local antlr_wheels=( "${T}/antlr-wheel"/antlr4_python3_runtime-4.9.3-py3-none-any.whl )
	[[ ${#antlr_wheels[@]} -eq 1 && -f ${antlr_wheels[0]} ]] ||
		die "expected exactly one built Antlr wheel"
	wheels+=( "${antlr_wheels[0]}" )
	wheels+=( "${DISTDIR}/${OPEN_WEBUI_MAIN_WHEEL}" )

	# --no-index/--no-deps/local paths only: every wheel is already fetched
	# into DISTDIR by Portage, and the full dependency closure was
	# pre-resolved by scripts/generate-open-webui-wheel-deps.py, so this
	# performs no network access and no dependency resolution of its own.
	#
	PIP_NO_INDEX=1 PIP_NO_CACHE_DIR=1 PIP_NO_INPUT=1 \
	PIP_DISABLE_PIP_VERSION_CHECK=1 PIP_ROOT_USER_ACTION=ignore \
	PIP_PROGRESS_BAR=off \
	"${EPYTHON}" -m pip install \
		--no-index --no-deps --no-compile \
		--target "${sitedir}" \
		"${wheels[@]}" || die "pip install of vendored wheels failed"

	# RapidOCR imports only cv2, for which the deliberately retained
	# opencv-python-headless wheel is the non-GUI provider.  Since Python
	# distribution metadata cannot express alternative providers, update
	# only RapidOCR's exact installed requirement to name that provider.
	"${EPYTHON}" - "${sitedir}" <<-'PY' || die "patching RapidOCR metadata failed"
		from pathlib import Path
		import sys

		sitedir = Path(sys.argv[1])
		dist_infos = list(sitedir.glob("rapidocr-3.9.2.dist-info"))
		if len(dist_infos) != 1 or not dist_infos[0].is_dir():
		    raise SystemExit(f"expected exactly one RapidOCR dist-info directory, found {dist_infos!r}")
		metadata = dist_infos[0] / "METADATA"
		old = "Requires-Dist: opencv_python>=4.5.1.48"
		new = "Requires-Dist: opencv-python-headless>=4.5.1.48"
		lines = metadata.read_text(encoding="utf-8").splitlines(keepends=True)
		matches = [i for i, line in enumerate(lines) if line.rstrip("\r\n") == old]
		if len(matches) != 1:
		    raise SystemExit(f"expected exactly one {old!r} requirement, found {len(matches)}")
		i = matches[0]
		ending = "\r\n" if lines[i].endswith("\r\n") else "\n" if lines[i].endswith("\n") else ""
		lines[i] = new + ending
		metadata.write_text("".join(lines), encoding="utf-8")
	PY

	# Validate every active dependency requirement in the private target
	# offline. distributions(path=[sitedir]) deliberately excludes system
	# Python distributions, so they cannot mask missing vendored wheels.
	"${EPYTHON}" -S - "${sitedir}" <<-'PY' || die "private dependency metadata check failed"
		from importlib.metadata import distributions
		from pathlib import Path
		import sys

		sitedir = Path(sys.argv[1])
		sys.path.insert(0, str(sitedir))
		from packaging.markers import default_environment
		from packaging.requirements import Requirement
		from packaging.utils import canonicalize_name
		from packaging.version import Version

		dists = list(distributions(path=[sitedir]))
		installed = {}
		for dist in dists:
		    name = canonicalize_name(dist.metadata["Name"])
		    if name in installed:
		        raise SystemExit(f"duplicate private distribution metadata for {name}")
		    installed[name] = (Version(dist.version), dist)
		if "opencv-python" in installed:
		    raise SystemExit("unexpected private opencv-python GUI distribution")
		env = default_environment()
		problems = []
		for _, dist in installed.values():
		    for raw in dist.requires or ():
		        req = Requirement(raw)
		        if req.marker and not req.marker.evaluate(env):
		            continue
		        found = installed.get(canonicalize_name(req.name))
		        if found is None:
		            problems.append(f"{dist.metadata['Name']} requires missing {req}")
		        elif req.specifier and found[0] not in req.specifier:
		            problems.append(f"{dist.metadata['Name']} requires {req}, found {found[0]}")
		if problems:
		    raise SystemExit("\n".join(problems))
		print(f"private dependency metadata check: {len(installed)} distributions satisfied")
	PY

	# pip's --target mode installs package files but not console_scripts
	# wrapper scripts (unlike a normal prefix/venv install); write the one
	# entry point this package actually needs by hand instead. Confirmed
	# via the wheel's own dist-info/entry_points.txt:
	#   [console_scripts]
	#   open-webui = open_webui:app
	# where `open_webui.app` is a typer.Typer() instance (callable).
	cat > "${T}/open-webui" <<-EOF || die
		#!/usr/bin/env ${EPYTHON}
		import sys
		sys.path.insert(0, "${EPREFIX}/usr/$(get_libdir)/open-webui/site-packages")
		from open_webui import app
		if __name__ == "__main__":
		    sys.exit(app())
	EOF
	python_newscript "${T}/open-webui" open-webui

	newinitd "${FILESDIR}/open-webui.initd" open-webui
	newconfd "${FILESDIR}/open-webui.confd" open-webui
	# WEBUI_SECRET_KEY and any backend API keys set in this file are
	# secrets (see the file's own header comment); newconfd's default
	# mode leaves it world-readable, which contradicts that comment.
	fperms 0600 /etc/conf.d/open-webui
	systemd_newunit "${FILESDIR}/open-webui.service" open-webui.service

	keepdir /var/lib/open-webui
	fowners open-webui:open-webui /var/lib/open-webui
	fperms 0750 /var/lib/open-webui
}
