# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

inherit desktop xdg

DESCRIPTION="Yubico Authenticator for TOTP"
HOMEPAGE="
	https://developers.yubico.com/yubioath-flutter/
	https://github.com/Yubico/yubioath-flutter"
# Upstream arm64 CI artifact from commit
# a157217776436bdc6a7beafc0e624087417dded7 (7.5.0-dev.0, CI tag dain).
# GitHub Actions artifacts expire in January 2027; refresh before expiry.
SRC_URI="
	arm64? (
		https://nightly.link/Yubico/yubioath-flutter/actions/artifacts/11535046656.zip
			-> ${P}-arm64.zip
	)
"
S="${WORKDIR}/yubico-authenticator"

LICENSE="Apache-2.0"
SLOT="0"
KEYWORDS="-* ~arm64"

RDEPEND="
	app-accessibility/at-spi2-core:2
	app-crypt/ccid
	dev-libs/glib:2
	media-libs/fontconfig
	media-libs/harfbuzz
	media-libs/libepoxy
	sys-apps/dbus
	sys-apps/pcsc-lite
	arm64? ( >=sys-libs/glibc-2.34 )
	virtual/libudev
	x11-libs/cairo
	x11-libs/gdk-pixbuf:2
	x11-libs/gtk+:3[X,wayland]
	x11-libs/libnotify
	x11-libs/libX11
	x11-libs/libXi
	x11-libs/pango"
BDEPEND="${BDEPEND}
	app-admin/chrpath
	app-arch/unzip"

# The bundle contains Flutter and a Rust helper. These are upstream prebuilt
# binaries; the helper links against the system PC/SC, D-Bus and udev libraries.
QA_PREBUILT="opt/yubico-authenticator/*"

src_unpack() {
	local bundle
	if use arm64; then
		bundle=yubioath-desktop-dain-linux-arm64
		unpack "${P}-arm64.zip"
	else
		die "Unsupported architecture: ${ARCH}"
	fi
	unpack "./${bundle}.tar.gz"
	mv "${WORKDIR}/${bundle}" "${S}" || die
}

src_install() {
	einstalldocs
	rm -r README* || die

	sed -e 's|@EXEC_PATH/authenticator|authenticator|' \
		-e 's|@EXEC_PATH/linux_support/com.yubico.yubioath.png|com.yubico.yubioath|g' \
		-i linux_support/com.yubico.yubioath.desktop || die
	domenu linux_support/com.yubico.yubioath.desktop
	doicon -s 128 linux_support/com.yubico.yubioath.png
	rm -r linux_support || die

	exeinto /opt/yubico-authenticator
	doexe authenticator
	rm authenticator || die

	exeinto /opt/yubico-authenticator/helper
	doexe helper/authenticator-helper
	rm helper/authenticator-helper || die

	# Generated by a transitive Android dependency. The Linux native-assets
	# manifest is empty and the application has no reference to this library.
	if use arm64; then
		rm lib/libdartjni.so || die
	fi

	# Remove CI build-directory RUNPATHs from Flutter plugins.
	chrpath -d \
		lib/libdesktop_drop_plugin.so \
		lib/liblocal_notifier_plugin.so \
		lib/libscreen_retriever_linux_plugin.so \
		lib/liburl_launcher_linux_plugin.so \
		lib/libwindow_manager_plugin.so || die

	insinto /opt/yubico-authenticator
	doins -r .

	dosym ../../opt/yubico-authenticator/authenticator /usr/bin/authenticator
}

pkg_postinst() {
	xdg_pkg_postinst

	elog "Make sure you are a member of the pcscd group"
	elog "and the pcscd service is running."
}
