# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

inherit desktop xdg

MY_ARTIFACT_ID=11225676753
MY_BUNDLE="yubioath-desktop-0.0.0-rc.8-linux-arm64"

DESCRIPTION="Yubico Authenticator for TOTP"
HOMEPAGE="
	https://developers.yubico.com/yubioath-flutter/
	https://github.com/Yubico/yubioath-flutter"
# Upstream publishes ARM64 builds as expiring GitHub Actions artifacts rather
# than release assets. This 7.5.0-dev.0 snapshot is built from commit
# cbf563f8536b622dd506414622b1222247daa5db (CI tag 0.0.0-rc.8).
# nightly.link provides access to this artifact, expiring 2026-12-31 12:09:25 UTC.
SRC_URI="https://nightly.link/Yubico/yubioath-flutter/actions/artifacts/${MY_ARTIFACT_ID}.zip
	-> ${P}-arm64.zip"
S="${WORKDIR}/${MY_BUNDLE}"

LICENSE="Apache-2.0"
SLOT="0"
KEYWORDS="-* ~arm64"

RDEPEND="
	app-accessibility/at-spi2-core:2
	app-crypt/ccid
	dev-libs/glib:2
	media-libs/fontconfig
	media-libs/harfbuzz
	media-libs/libepoxy
	sys-apps/dbus
	sys-apps/pcsc-lite
	sys-libs/glibc
	virtual/libudev
	x11-libs/cairo
	x11-libs/gdk-pixbuf:2
	x11-libs/gtk+:3[X,wayland]
	x11-libs/libnotify
	x11-libs/libX11
	x11-libs/libXi
	x11-libs/pango"
BDEPEND="${BDEPEND}
	app-admin/chrpath
	app-arch/unzip"

# The bundle contains Flutter and a Rust helper. These are upstream prebuilt
# binaries; the helper links against the system PC/SC, D-Bus and udev libraries.
QA_PREBUILT="opt/yubico-authenticator/*"

src_unpack() {
	unpack "${P}-arm64.zip"
	unpack "./${MY_BUNDLE}.tar.gz"
}

src_install() {
	einstalldocs
	rm -r README* || die

	sed -e 's|@EXEC_PATH/authenticator|authenticator|' \
		-e 's|@EXEC_PATH/linux_support/com.yubico.yubioath.png|com.yubico.yubioath|g' \
		-i linux_support/com.yubico.yubioath.desktop || die
	domenu linux_support/com.yubico.yubioath.desktop
	doicon -s 128 linux_support/com.yubico.yubioath.png
	rm -r linux_support || die

	exeinto /opt/yubico-authenticator
	doexe authenticator
	rm authenticator || die

	exeinto /opt/yubico-authenticator/helper
	doexe helper/authenticator-helper
	rm helper/authenticator-helper || die

	# Generated by a transitive Android dependency. The Linux native-assets
	# manifest is empty and the application has no reference to this library.
	rm lib/libdartjni.so || die

	# Remove CI build-directory RUNPATHs from Flutter plugins.
	chrpath -d \
		lib/libdesktop_drop_plugin.so \
		lib/liblocal_notifier_plugin.so \
		lib/libscreen_retriever_linux_plugin.so \
		lib/liburl_launcher_linux_plugin.so \
		lib/libwindow_manager_plugin.so || die

	insinto /opt/yubico-authenticator
	doins -r .

	dosym ../../opt/yubico-authenticator/authenticator /usr/bin/authenticator
}

pkg_postinst() {
	xdg_pkg_postinst

	elog "Make sure you are a member of the pcscd group"
	elog "and the pcscd service is running."
}
