#!/usr/bin/env python3
"""Generate the filtered pnpm closure for the n8n external JavaScript runner."""

from __future__ import annotations

import argparse
import posixpath
from collections import deque
from pathlib import Path

import yaml


ROOT_IMPORTER = "packages/@n8n/task-runner"
EXTRA_PACKAGES = {
    "moment@2.30.1",
    "wa-sqlite@https://codeload.github.com/rhashimoto/wa-sqlite/tar.gz/779219540f66cecaa159da32b3b8936697ba10a7",
    "xlsx@https://cdn.sheetjs.com/xlsx-0.20.2/xlsx-0.20.2.tgz",
}
SPECIAL_DISTFILES = {
    "N8N_TASK_RUNNERS_MOMENT_DISTFILE": "moment@2.30.1",
    "N8N_TASK_RUNNERS_XLSX_DISTFILE": "xlsx@https://cdn.sheetjs.com/xlsx-0.20.2/xlsx-0.20.2.tgz",
    "N8N_TASK_RUNNERS_WA_SQLITE_DISTFILE": (
        "wa-sqlite@https://codeload.github.com/rhashimoto/wa-sqlite/tar.gz/"
        "779219540f66cecaa159da32b3b8936697ba10a7"
    ),
}


def registry_uri(name: str, version: str) -> str:
    basename = name.rsplit("/", 1)[-1]
    return f"https://registry.npmjs.org/{name}/-/{basename}-{version}.tgz"


def base_locator(locator: str) -> str:
    return locator.split("(", 1)[0]


def derive_closure(lock: dict) -> tuple[set[str], set[str]]:
    importers = lock["importers"]
    packages = lock["packages"]
    snapshots = lock["snapshots"]
    # pnpm installs the workspace root's build tooling even for a filtered
    # recursive install, so it is part of the reproducible source-build graph.
    workspace = deque([".", ROOT_IMPORTER])
    pending: deque[str] = deque()
    seen_workspace: set[str] = set()
    seen_snapshots: set[str] = set()
    artifacts: set[str] = set()

    def snapshot_key(dependency: str, value: str) -> str:
        candidate = f"{dependency}@{value}"
        if candidate in snapshots:
            return candidate
        if value in snapshots:
            return value
        choices = [key for key in snapshots if base_locator(key) == base_locator(candidate)]
        if len(choices) == 1:
            return choices[0]
        raise RuntimeError(
            f"cannot resolve locked dependency {dependency}={value}: {len(choices)} choices"
        )

    while workspace:
        importer = workspace.popleft()
        if importer in seen_workspace:
            continue
        if importer not in importers:
            raise RuntimeError(f"missing workspace importer: {importer}")
        seen_workspace.add(importer)
        for field in ("dependencies", "devDependencies", "optionalDependencies"):
            for dependency, record in (importers[importer].get(field) or {}).items():
                value = record.get("version", record) if isinstance(record, dict) else record
                value = str(value)
                if value.startswith("link:"):
                    workspace.append(posixpath.normpath(posixpath.join(importer, value[5:])))
                else:
                    pending.append(snapshot_key(dependency, value))

    while pending:
        key = pending.popleft()
        if key in seen_snapshots:
            continue
        seen_snapshots.add(key)
        locator = base_locator(key)
        if locator not in packages:
            raise RuntimeError(f"missing package metadata: {locator}")
        artifacts.add(locator)
        for field in ("dependencies", "optionalDependencies"):
            for dependency, value in (snapshots[key].get(field) or {}).items():
                pending.append(snapshot_key(dependency, str(value)))

    artifacts.update(EXTRA_PACKAGES)
    return artifacts, seen_workspace


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("version")
    parser.add_argument("lockfile", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    lock = yaml.safe_load(args.lockfile.read_text(encoding="utf-8"))
    artifacts, workspace = derive_closure(lock)
    entries = []
    for locator in sorted(artifacts):
        package = lock["packages"][locator]
        name, version = locator.rsplit("@", 1)
        uri = package.get("resolution", {}).get("tarball") or registry_uri(name, version)
        entries.append((locator, uri))

    aliases = {
        locator: f"n8n-runner-js-{index:06d}.tgz"
        for index, (locator, _) in enumerate(entries, 1)
    }
    missing_special = set(SPECIAL_DISTFILES.values()) - aliases.keys()
    if missing_special:
        raise RuntimeError(f"special artifacts missing from closure: {sorted(missing_special)}")

    lines = [
        "# Generated by scripts/generate-n8n-task-runner-deps.py; do not edit.",
        f"# Workspace importers: {len(workspace)}; external artifacts: {len(entries)}",
        "# @ECLASS: n8n-task-runners-pnpm-deps.eclass",
        f"# @BLURB: Generated pnpm closure for app-misc/n8n-task-runners-{args.version}",
        f'N8N_TASK_RUNNERS_PNPM_VERSION="{args.version}"',
        "",
        "N8N_TASK_RUNNERS_PNPM_SRC_URI=(",
    ]
    lines.extend(
        f'\t"{uri} -> n8n-runner-js-{index:06d}.tgz"'
        for index, (_, uri) in enumerate(entries, 1)
    )
    lines.extend((")", "", "N8N_TASK_RUNNERS_PNPM_PACKAGE_IDS=("))
    lines.extend(f'\t"{locator}"' for locator, _ in entries)
    lines.extend(
        (
            ")",
            "",
            *(f'{variable}="{aliases[locator]}"' for variable, locator in SPECIAL_DISTFILES.items()),
            "",
            "# @FUNCTION: n8n_task_runners_pnpm_add_src_uri",
            "# @DESCRIPTION:",
            "# Verify the n8n release and append the runner-specific closure.",
            "n8n_task_runners_pnpm_add_src_uri() {",
            '\t[[ $# -eq 1 ]] || die "${FUNCNAME}: expected one n8n version argument"',
            '\t[[ ${1} == ${N8N_TASK_RUNNERS_PNPM_VERSION} ]] ||',
            '\t\tdie "${FUNCNAME}: metadata is for n8n-${N8N_TASK_RUNNERS_PNPM_VERSION}, not n8n-${1}"',
            '\tSRC_URI+=" ${N8N_TASK_RUNNERS_PNPM_SRC_URI[*]}"',
            "}",
            "",
        )
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
