#!/usr/bin/env python3
"""Generate Anki's exact offline npm inputs from its upstream Yarn lock."""

import argparse
import hashlib
from pathlib import Path

import yaml


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("version")
    parser.add_argument("lockfile", type=Path)
    parser.add_argument("eclass", type=Path)
    args = parser.parse_args()
    lock = yaml.safe_load(args.lockfile.read_text())
    artifacts = {}
    for key, record in lock.items():
        if key == "__metadata":
            continue
        locator = record["resolution"]
        if "@npm:" not in locator:
            if "@workspace:" in locator or "@patch:" in locator:
                # Builtin Yarn patches fetch their npm source locator separately.
                continue
            raise ValueError(f"unsupported Yarn locator: {locator}")
        name, version = locator.rsplit("@npm:", 1)
        uri = f"https://registry.npmjs.org/{name}/-/{name.rsplit('/', 1)[-1]}-{version}.tgz"
        filename = "anki-npm-" + hashlib.sha256(uri.encode()).hexdigest()[:20] + ".tgz"
        artifacts[name + "@" + version] = (uri, filename)
    lines = [
        "# Generated by scripts/generate-anki-npm-deps.py; do not edit.",
        f"# @ECLASS: anki-npm-deps-{args.version}.eclass",
        "# @BLURB: Exact upstream Yarn-lock artifacts for Anki",
        f'ANKI_NPM_VERSION="{args.version}"',
        "ANKI_NPM_SRC_URI=(",
        *(f'\t"{uri} -> {filename}"' for _, (uri, filename) in sorted(artifacts.items())),
        ")",
        "",
        "# @FUNCTION: anki_npm_add_src_uri",
        "# @DESCRIPTION:",
        "# Append the exact npm distfiles when the GUI is enabled.",
        "anki_npm_add_src_uri() {",
        '\t[[ ${PV} == ${ANKI_NPM_VERSION} ]] || die "Anki dependency version mismatch"',
        '\tSRC_URI+=" gui? ( ${ANKI_NPM_SRC_URI[*]} )"',
        "}",
        "",
    ]
    args.eclass.write_text("\n".join(lines))
    print(f"Generated {len(artifacts)} exact upstream npm artifacts")


if __name__ == "__main__":
    main()
