#!/usr/bin/env python3
"""Generate deterministic app-backup/restic-browser npm distfile metadata
from package-lock.json, restricted to the linux+arm64+glibc dependency
closure needed to build the frontend without network access.
"""

from __future__ import annotations

import argparse
import gzip
import json
import re
from pathlib import Path


def distfile(name: str, version: str) -> str:
    safe_name = re.sub(r"[^A-Za-z0-9+_.-]", "-", name.lstrip("@"))
    safe_version = re.sub(r"[^A-Za-z0-9+_.-]", "-", version)
    return f"restic-browser-npm-{safe_name}-{safe_version}.tgz"


def wanted(path: str, info: dict) -> bool:
    os_ = info.get("os")
    cpu_ = info.get("cpu")
    name = path.rsplit("/", 1)[-1]
    if os_ and "linux" not in os_:
        return False
    if cpu_ and "arm64" not in cpu_:
        return False
    # package-lock.json does not record the libc constraint; npm packages
    # that ship both glibc and musl native builds encode it only in the
    # package name (e.g. "-gnu" vs "-musl"). This overlay targets glibc.
    if "musl" in name:
        return False
    return True


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("version")
    parser.add_argument("lockfile", type=Path, help="package-lock.json, optionally gzip-compressed (.gz)")
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    if args.lockfile.suffix == ".gz":
        with gzip.open(args.lockfile, "rt", encoding="utf-8") as f:
            lock = json.load(f)
    else:
        lock = json.loads(args.lockfile.read_text(encoding="utf-8"))
    entries: list[tuple[str, str, str]] = []  # (node_modules path, uri, filename)
    seen_distfiles: dict[str, str] = {}

    for path, info in lock["packages"].items():
        if path == "":
            continue
        if not path.startswith("node_modules/"):
            raise SystemExit(f"unexpected non-flat lockfile entry: {path}")
        if not wanted(path, info):
            continue
        # Open-source npm packages declare a short SPDX identifier (e.g.
        # "Apache-2.0", "MIT"). A "license" field containing a URL is the
        # pattern proprietary packages use instead (e.g. Vaadin's
        # "https://vaadin.com/commercial-license-and-service-terms", which
        # 24 @vaadin/* packages switched to at 23.5.0 after this overlay
        # pinned them to the last Apache-2.0 release, 23.3.25 -- see
        # scripts/README.restic-browser.md). Refuse to silently vendor
        # anything matching that pattern, regardless of which package it
        # is, so a future version bump that re-resolves to a
        # commercially-licensed release fails loudly here instead of
        # producing an ebuild with an inaccurate LICENSE.
        license_ = info.get("license")
        if isinstance(license_, str) and "://" in license_:
            raise SystemExit(
                f"{path}@{info.get('version')}: non-open-source license "
                f"({license_!r}) -- do not vendor; re-pin to the last "
                "open-source release or update the license accounting"
            )
        uri = info.get("resolved")
        if not uri or not uri.startswith("https://registry.npmjs.org/"):
            raise SystemExit(f"{path}: not a plain npm-registry tarball dependency")
        name = path.rsplit("node_modules/", 1)[-1]
        filename = distfile(name, info["version"])
        if filename in seen_distfiles and seen_distfiles[filename] != uri:
            raise SystemExit(f"distfile collision: {filename}")
        seen_distfiles[filename] = uri
        entries.append((path, uri, filename))

    entries.sort(key=lambda item: item[0])

    lines = [
        "# Generated by scripts/generate-restic-browser-npm-deps.py; do not edit.",
        f"# Locked linux/arm64/glibc npm dependency closure: {len(entries)} packages",
        f'RESTIC_BROWSER_NPM_DEPS_VERSION="{args.version}"',
        "",
        "RESTIC_BROWSER_NPM_SRC_URI=(",
    ]
    lines.extend(f'\t"{uri} -> {filename}"' for _, uri, filename in entries)
    lines.extend((")", "", "# node_modules/<path> -> distfile, one per line", "RESTIC_BROWSER_NPM_PATHS=("))
    lines.extend(f'\t"{path}|{filename}"' for path, _, filename in entries)
    lines.append(")")
    lines.append("")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
