#!/usr/bin/env python3
"""Generate deterministic n8n pnpm distfile metadata from pnpm-lock.yaml."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import yaml


def registry_uri(name: str, version: str) -> str:
    basename = name.rsplit("/", 1)[-1]
    return f"https://registry.npmjs.org/{name}/-/{basename}-{version}.tgz"


def distfile(name: str, version: str) -> str:
    safe_name = re.sub(r"[^A-Za-z0-9+_.-]", "-", name.lstrip("@"))
    safe_version = re.sub(r"[^A-Za-z0-9+_.-]", "-", version)
    return f"n8n-pnpm-{safe_name}-{safe_version}.tgz"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("version")
    parser.add_argument("lockfile", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    lock = yaml.safe_load(args.lockfile.read_text(encoding="utf-8"))
    entries: list[tuple[str, str, str, str]] = []
    seen_distfiles: dict[str, str] = {}

    for key, package in lock["packages"].items():
        name, version = key.rsplit("@", 1)
        resolution = package.get("resolution", {})
        if "tarball" in resolution:
            uri = resolution["tarball"]
            if name == "wa-sqlite":
                version = "779219540f66cecaa159da32b3b8936697ba10a7"
            elif name == "xlsx":
                version = "0.20.2"
        else:
            uri = registry_uri(name, version)
        filename = distfile(name, version)
        if filename in seen_distfiles and seen_distfiles[filename] != uri:
            raise SystemExit(f"distfile collision: {filename}")
        seen_distfiles[filename] = uri
        entries.append((key, name, uri, filename))

    entries.sort(key=lambda item: (item[1], item[3], item[2]))
    lines = [
        "# Generated by scripts/generate-n8n-pnpm-deps.py; do not edit.",
        f"# Locked external package artifacts: {len(entries)}",
        "# @ECLASS: n8n-pnpm-deps.eclass",
        f"# @BLURB: Generated pnpm dependency URIs for app-misc/n8n-{args.version}",
        f'N8N_PNPM_DEPS_VERSION="{args.version}"',
        "",
        "N8N_PNPM_SRC_URI=(",
    ]
    lines.extend(f'\t"{uri} -> {filename}"' for _, _, uri, filename in entries)
    lines.extend((")", "", "N8N_PNPM_PACKAGE_IDS=("))
    lines.extend(f'\t"{key}"' for key, _, _, _ in entries)
    lines.extend(
        (
            ")",
            "",
            "# @FUNCTION: n8n_pnpm_deps_add_src_uri",
            "# @DESCRIPTION:",
            "# Verify the requested n8n version and append its dependency closure to SRC_URI.",
            "n8n_pnpm_deps_add_src_uri() {",
            '\t[[ $# -eq 1 ]] || die "${FUNCNAME}: expected one n8n version argument"',
            '\t[[ ${1} == ${N8N_PNPM_DEPS_VERSION} ]] ||',
            '\t\tdie "${FUNCNAME}: dependency metadata is for n8n-${N8N_PNPM_DEPS_VERSION}, not n8n-${1}"',
            "\tSRC_URI+=\" ${N8N_PNPM_SRC_URI[*]}\"",
            "}",
            "",
        )
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
