# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# This is a -bin package: openclaw is published to the npm registry with
# its dist/ already bundled (esbuild/Vite output invoked by upstream's own
# release pipeline), so no TypeScript build step is needed here at all --
# unlike app-backup/restic-browser (which vendors an npm dependency
# closure the same way but still runs `npm run build`), this ebuild's
# src_prepare only ever assembles files, never compiles anything.
#
# The published tarball's dist/*.js chunks dynamically `import()`/require()
# a much larger set of bare package specifiers than package.json's own
# "dependencies" field declares (many per-provider/per-channel plugin
# integrations are lazy-loaded), so simply placing dist/+openclaw.mjs on
# disk is not enough for full functionality: node_modules must be
# populated from the exact npm-shrinkwrap.json-locked closure below, the
# same way restic-browser assembles its frontend node_modules --
# individually fetched from registry.npmjs.org via SRC_URI and extracted
# directly into the right node_modules/<path> in src_prepare, with no
# `npm install` invocation (and therefore no network access) at any build
# phase.
#
# Two optional native-addon dependencies (@lydell/node-pty, used by
# terminal/pty-based skills, and sqlite-vec, used for local vector search)
# publish separate prebuilt linux-x64/linux-arm64 npm packages; only those
# two Linux variants are vendored below (gated on the amd64/arm64 KEYWORDS
# the same way net-im/claude-desktop-bin gates its .deb SRC_URI), darwin
# and win32 variants are dropped. Every other dependency in the closure is
# plain JS with no os/cpu constraint, so it applies to both KEYWORDS.
#
# Regenerate the arrays below (and files/${P}-third-party-licenses.txt,
# see the dodoc call in src_install) with:
#   scripts/generate-openclaw-npm-deps.py 2026.7.1.2 \
#     path/to/npm-shrinkwrap.json out.gen \
#     files/${P}-third-party-licenses.txt
# (npm-shrinkwrap.json is not committed to this overlay; re-download it
# from the published tarball at
# https://registry.npmjs.org/openclaw/-/openclaw-<upstream-version>.tgz
# for the version being bumped to.) The generator refuses to emit an entry
# for any dependency whose lockfile-recorded license does not pass plain,
# regex-based SPDX-like syntax validation (and explicitly rejects
# npm's own "UNKNOWN"/"UNLICENSED" non-answer placeholders by name), so
# pointing it at a fresh lockfile fails loudly instead of silently
# producing an ebuild with an inaccurate LICENSE. The third-party-licenses
# file it also writes is a deterministic, sorted "name@version: license"
# listing of every vendored package -- installed via dodoc below so it's
# independently verifiable without re-deriving it from the lockfile.

# python-any-r1.eclass does not (yet) support EAPI 9 (@SUPPORTED_EAPIS: 7
# 8; same constraint www-apps/open-webui-bin already hit and documented
# for python-single-r1.eclass); keep this at 8 until it does. Python here
# is a pure build-time tool (safe tarball extraction in src_unpack/
# src_prepare, see _openclaw_safe_extract below), never installed or run
# at runtime, so python-any-r1 (not python-single-r1/python-r1) is the
# correct eclass -- it depends on "any" installed, supported interpreter
# rather than pinning one into RDEPEND.
EAPI=8

PYTHON_COMPAT=( python3_{11..15} )

inherit python-any-r1

DESCRIPTION="Multi-channel AI gateway with extensible messaging integrations"
HOMEPAGE="https://github.com/openclaw/openclaw https://openclaw.org"

# Upstream's own version string uses a bare hyphen ("2026.7.1-2"), which
# PMS version syntax does not allow mid-version; MY_PV keeps the real
# upstream string for URL construction while PV/${P} stay Gentoo-legal.
MY_PV="2026.7.1-2"
# Generated by scripts/generate-openclaw-npm-deps.py; do not edit.
# Locked closure: 301 node_modules paths, 299 distfiles (295 both, 2 amd64, 2 arm64)
OPENCLAW_NPM_DEPS_VERSION="2026.7.1.2"

OPENCLAW_NPM_SRC_URI=(
	"https://registry.npmjs.org/abort-controller/-/abort-controller-3.0.0.tgz -> openclaw-bin-npm-abort-controller-3.0.0.tgz"
	"https://registry.npmjs.org/accepts/-/accepts-2.0.0.tgz -> openclaw-bin-npm-accepts-2.0.0.tgz"
	"https://registry.npmjs.org/agent-base/-/agent-base-7.1.4.tgz -> openclaw-bin-npm-agent-base-7.1.4.tgz"
	"https://registry.npmjs.org/@agentclientprotocol/sdk/-/sdk-1.1.0.tgz -> openclaw-bin-npm-agentclientprotocol-sdk-1.1.0.tgz"
	"https://registry.npmjs.org/ajv/-/ajv-8.20.0.tgz -> openclaw-bin-npm-ajv-8.20.0.tgz"
	"https://registry.npmjs.org/ajv-formats/-/ajv-formats-3.0.1.tgz -> openclaw-bin-npm-ajv-formats-3.0.1.tgz"
	"https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz -> openclaw-bin-npm-ansi-regex-5.0.1.tgz"
	"https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz -> openclaw-bin-npm-ansi-styles-4.3.0.tgz"
	"https://registry.npmjs.org/@anthropic-ai/sdk/-/sdk-0.109.1.tgz -> openclaw-bin-npm-anthropic-ai-sdk-0.109.1.tgz"
	"https://registry.npmjs.org/asn1.js/-/asn1.js-5.4.1.tgz -> openclaw-bin-npm-asn1.js-5.4.1.tgz"
	"https://registry.npmjs.org/@babel/runtime/-/runtime-7.29.7.tgz -> openclaw-bin-npm-babel-runtime-7.29.7.tgz"
	"https://registry.npmjs.org/balanced-match/-/balanced-match-4.0.4.tgz -> openclaw-bin-npm-balanced-match-4.0.4.tgz"
	"https://registry.npmjs.org/base64-js/-/base64-js-1.5.1.tgz -> openclaw-bin-npm-base64-js-1.5.1.tgz"
	"https://registry.npmjs.org/bignumber.js/-/bignumber.js-9.3.1.tgz -> openclaw-bin-npm-bignumber.js-9.3.1.tgz"
	"https://registry.npmjs.org/bn.js/-/bn.js-4.12.4.tgz -> openclaw-bin-npm-bn.js-4.12.4.tgz"
	"https://registry.npmjs.org/body-parser/-/body-parser-2.3.0.tgz -> openclaw-bin-npm-body-parser-2.3.0.tgz"
	"https://registry.npmjs.org/boolbase/-/boolbase-1.0.0.tgz -> openclaw-bin-npm-boolbase-1.0.0.tgz"
	"https://registry.npmjs.org/@borewit/text-codec/-/text-codec-0.2.2.tgz -> openclaw-bin-npm-borewit-text-codec-0.2.2.tgz"
	"https://registry.npmjs.org/bottleneck/-/bottleneck-2.19.5.tgz -> openclaw-bin-npm-bottleneck-2.19.5.tgz"
	"https://registry.npmjs.org/brace-expansion/-/brace-expansion-5.0.7.tgz -> openclaw-bin-npm-brace-expansion-5.0.7.tgz"
	"https://registry.npmjs.org/buffer-equal-constant-time/-/buffer-equal-constant-time-1.0.1.tgz -> openclaw-bin-npm-buffer-equal-constant-time-1.0.1.tgz"
	"https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.2.tgz -> openclaw-bin-npm-buffer-from-1.1.2.tgz"
	"https://registry.npmjs.org/bytes/-/bytes-3.1.2.tgz -> openclaw-bin-npm-bytes-3.1.2.tgz"
	"https://registry.npmjs.org/call-bind-apply-helpers/-/call-bind-apply-helpers-1.0.2.tgz -> openclaw-bin-npm-call-bind-apply-helpers-1.0.2.tgz"
	"https://registry.npmjs.org/call-bound/-/call-bound-1.0.4.tgz -> openclaw-bin-npm-call-bound-1.0.4.tgz"
	"https://registry.npmjs.org/camelcase/-/camelcase-5.3.1.tgz -> openclaw-bin-npm-camelcase-5.3.1.tgz"
	"https://registry.npmjs.org/chalk/-/chalk-5.6.2.tgz -> openclaw-bin-npm-chalk-5.6.2.tgz"
	"https://registry.npmjs.org/chokidar/-/chokidar-5.0.0.tgz -> openclaw-bin-npm-chokidar-5.0.0.tgz"
	"https://registry.npmjs.org/chownr/-/chownr-3.0.0.tgz -> openclaw-bin-npm-chownr-3.0.0.tgz"
	"https://registry.npmjs.org/@clack/core/-/core-1.4.2.tgz -> openclaw-bin-npm-clack-core-1.4.2.tgz"
	"https://registry.npmjs.org/@clack/prompts/-/prompts-1.6.0.tgz -> openclaw-bin-npm-clack-prompts-1.6.0.tgz"
	"https://registry.npmjs.org/clawpdf/-/clawpdf-0.3.0.tgz -> openclaw-bin-npm-clawpdf-0.3.0.tgz"
	"https://registry.npmjs.org/cliui/-/cliui-6.0.0.tgz -> openclaw-bin-npm-cliui-6.0.0.tgz"
	"https://registry.npmjs.org/cliui/-/cliui-8.0.1.tgz -> openclaw-bin-npm-cliui-8.0.1.tgz"
	"https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz -> openclaw-bin-npm-color-convert-2.0.1.tgz"
	"https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz -> openclaw-bin-npm-color-name-1.1.4.tgz"
	"https://registry.npmjs.org/commander/-/commander-15.0.0.tgz -> openclaw-bin-npm-commander-15.0.0.tgz"
	"https://registry.npmjs.org/content-disposition/-/content-disposition-1.1.0.tgz -> openclaw-bin-npm-content-disposition-1.1.0.tgz"
	"https://registry.npmjs.org/content-type/-/content-type-1.0.5.tgz -> openclaw-bin-npm-content-type-1.0.5.tgz"
	"https://registry.npmjs.org/content-type/-/content-type-2.0.0.tgz -> openclaw-bin-npm-content-type-2.0.0.tgz"
	"https://registry.npmjs.org/cookie/-/cookie-0.7.2.tgz -> openclaw-bin-npm-cookie-0.7.2.tgz"
	"https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.2.2.tgz -> openclaw-bin-npm-cookie-signature-1.2.2.tgz"
	"https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.3.tgz -> openclaw-bin-npm-core-util-is-1.0.3.tgz"
	"https://registry.npmjs.org/cors/-/cors-2.8.6.tgz -> openclaw-bin-npm-cors-2.8.6.tgz"
	"https://registry.npmjs.org/croner/-/croner-10.0.1.tgz -> openclaw-bin-npm-croner-10.0.1.tgz"
	"https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.6.tgz -> openclaw-bin-npm-cross-spawn-7.0.6.tgz"
	"https://registry.npmjs.org/css-select/-/css-select-5.2.2.tgz -> openclaw-bin-npm-css-select-5.2.2.tgz"
	"https://registry.npmjs.org/css-what/-/css-what-6.2.2.tgz -> openclaw-bin-npm-css-what-6.2.2.tgz"
	"https://registry.npmjs.org/cssom/-/cssom-0.5.0.tgz -> openclaw-bin-npm-cssom-0.5.0.tgz"
	"https://registry.npmjs.org/data-uri-to-buffer/-/data-uri-to-buffer-4.0.1.tgz -> openclaw-bin-npm-data-uri-to-buffer-4.0.1.tgz"
	"https://registry.npmjs.org/debug/-/debug-4.4.3.tgz -> openclaw-bin-npm-debug-4.4.3.tgz"
	"https://registry.npmjs.org/decamelize/-/decamelize-1.2.0.tgz -> openclaw-bin-npm-decamelize-1.2.0.tgz"
	"https://registry.npmjs.org/depd/-/depd-2.0.0.tgz -> openclaw-bin-npm-depd-2.0.0.tgz"
	"https://registry.npmjs.org/diff/-/diff-9.0.0.tgz -> openclaw-bin-npm-diff-9.0.0.tgz"
	"https://registry.npmjs.org/dijkstrajs/-/dijkstrajs-1.0.3.tgz -> openclaw-bin-npm-dijkstrajs-1.0.3.tgz"
	"https://registry.npmjs.org/dom-serializer/-/dom-serializer-2.0.0.tgz -> openclaw-bin-npm-dom-serializer-2.0.0.tgz"
	"https://registry.npmjs.org/domelementtype/-/domelementtype-2.3.0.tgz -> openclaw-bin-npm-domelementtype-2.3.0.tgz"
	"https://registry.npmjs.org/domhandler/-/domhandler-5.0.3.tgz -> openclaw-bin-npm-domhandler-5.0.3.tgz"
	"https://registry.npmjs.org/domutils/-/domutils-3.2.2.tgz -> openclaw-bin-npm-domutils-3.2.2.tgz"
	"https://registry.npmjs.org/dotenv/-/dotenv-17.4.2.tgz -> openclaw-bin-npm-dotenv-17.4.2.tgz"
	"https://registry.npmjs.org/dunder-proto/-/dunder-proto-1.0.1.tgz -> openclaw-bin-npm-dunder-proto-1.0.1.tgz"
	"https://registry.npmjs.org/@earendil-works/pi-tui/-/pi-tui-0.80.3.tgz -> openclaw-bin-npm-earendil-works-pi-tui-0.80.3.tgz"
	"https://registry.npmjs.org/ecdsa-sig-formatter/-/ecdsa-sig-formatter-1.0.11.tgz -> openclaw-bin-npm-ecdsa-sig-formatter-1.0.11.tgz"
	"https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz -> openclaw-bin-npm-ee-first-1.1.1.tgz"
	"https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz -> openclaw-bin-npm-emoji-regex-8.0.0.tgz"
	"https://registry.npmjs.org/encodeurl/-/encodeurl-2.0.0.tgz -> openclaw-bin-npm-encodeurl-2.0.0.tgz"
	"https://registry.npmjs.org/entities/-/entities-4.5.0.tgz -> openclaw-bin-npm-entities-4.5.0.tgz"
	"https://registry.npmjs.org/entities/-/entities-7.0.1.tgz -> openclaw-bin-npm-entities-7.0.1.tgz"
	"https://registry.npmjs.org/es-define-property/-/es-define-property-1.0.1.tgz -> openclaw-bin-npm-es-define-property-1.0.1.tgz"
	"https://registry.npmjs.org/es-errors/-/es-errors-1.3.0.tgz -> openclaw-bin-npm-es-errors-1.3.0.tgz"
	"https://registry.npmjs.org/es-object-atoms/-/es-object-atoms-1.1.2.tgz -> openclaw-bin-npm-es-object-atoms-1.1.2.tgz"
	"https://registry.npmjs.org/escalade/-/escalade-3.2.0.tgz -> openclaw-bin-npm-escalade-3.2.0.tgz"
	"https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz -> openclaw-bin-npm-escape-html-1.0.3.tgz"
	"https://registry.npmjs.org/etag/-/etag-1.8.1.tgz -> openclaw-bin-npm-etag-1.8.1.tgz"
	"https://registry.npmjs.org/event-target-shim/-/event-target-shim-5.0.1.tgz -> openclaw-bin-npm-event-target-shim-5.0.1.tgz"
	"https://registry.npmjs.org/eventsource/-/eventsource-3.0.7.tgz -> openclaw-bin-npm-eventsource-3.0.7.tgz"
	"https://registry.npmjs.org/eventsource-parser/-/eventsource-parser-3.1.0.tgz -> openclaw-bin-npm-eventsource-parser-3.1.0.tgz"
	"https://registry.npmjs.org/express/-/express-5.2.1.tgz -> openclaw-bin-npm-express-5.2.1.tgz"
	"https://registry.npmjs.org/express-rate-limit/-/express-rate-limit-8.5.2.tgz -> openclaw-bin-npm-express-rate-limit-8.5.2.tgz"
	"https://registry.npmjs.org/extend/-/extend-3.0.2.tgz -> openclaw-bin-npm-extend-3.0.2.tgz"
	"https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz -> openclaw-bin-npm-fast-deep-equal-3.1.3.tgz"
	"https://registry.npmjs.org/fast-sha256/-/fast-sha256-1.3.0.tgz -> openclaw-bin-npm-fast-sha256-1.3.0.tgz"
	"https://registry.npmjs.org/fast-string-truncated-width/-/fast-string-truncated-width-3.0.3.tgz -> openclaw-bin-npm-fast-string-truncated-width-3.0.3.tgz"
	"https://registry.npmjs.org/fast-string-width/-/fast-string-width-3.0.2.tgz -> openclaw-bin-npm-fast-string-width-3.0.2.tgz"
	"https://registry.npmjs.org/fast-uri/-/fast-uri-3.1.2.tgz -> openclaw-bin-npm-fast-uri-3.1.2.tgz"
	"https://registry.npmjs.org/fast-wrap-ansi/-/fast-wrap-ansi-0.2.2.tgz -> openclaw-bin-npm-fast-wrap-ansi-0.2.2.tgz"
	"https://registry.npmjs.org/fetch-blob/-/fetch-blob-3.2.0.tgz -> openclaw-bin-npm-fetch-blob-3.2.0.tgz"
	"https://registry.npmjs.org/file-type/-/file-type-22.0.1.tgz -> openclaw-bin-npm-file-type-22.0.1.tgz"
	"https://registry.npmjs.org/finalhandler/-/finalhandler-2.1.1.tgz -> openclaw-bin-npm-finalhandler-2.1.1.tgz"
	"https://registry.npmjs.org/find-up/-/find-up-4.1.0.tgz -> openclaw-bin-npm-find-up-4.1.0.tgz"
	"https://registry.npmjs.org/formdata-polyfill/-/formdata-polyfill-4.0.10.tgz -> openclaw-bin-npm-formdata-polyfill-4.0.10.tgz"
	"https://registry.npmjs.org/forwarded/-/forwarded-0.2.0.tgz -> openclaw-bin-npm-forwarded-0.2.0.tgz"
	"https://registry.npmjs.org/fresh/-/fresh-2.0.0.tgz -> openclaw-bin-npm-fresh-2.0.0.tgz"
	"https://registry.npmjs.org/function-bind/-/function-bind-1.1.2.tgz -> openclaw-bin-npm-function-bind-1.1.2.tgz"
	"https://registry.npmjs.org/gaxios/-/gaxios-7.1.5.tgz -> openclaw-bin-npm-gaxios-7.1.5.tgz"
	"https://registry.npmjs.org/gcp-metadata/-/gcp-metadata-8.1.2.tgz -> openclaw-bin-npm-gcp-metadata-8.1.2.tgz"
	"https://registry.npmjs.org/get-caller-file/-/get-caller-file-2.0.5.tgz -> openclaw-bin-npm-get-caller-file-2.0.5.tgz"
	"https://registry.npmjs.org/get-east-asian-width/-/get-east-asian-width-1.6.0.tgz -> openclaw-bin-npm-get-east-asian-width-1.6.0.tgz"
	"https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.3.0.tgz -> openclaw-bin-npm-get-intrinsic-1.3.0.tgz"
	"https://registry.npmjs.org/get-proto/-/get-proto-1.0.1.tgz -> openclaw-bin-npm-get-proto-1.0.1.tgz"
	"https://registry.npmjs.org/glob/-/glob-13.0.6.tgz -> openclaw-bin-npm-glob-13.0.6.tgz"
	"https://registry.npmjs.org/google-auth-library/-/google-auth-library-10.9.0.tgz -> openclaw-bin-npm-google-auth-library-10.9.0.tgz"
	"https://registry.npmjs.org/@google/genai/-/genai-2.10.0.tgz -> openclaw-bin-npm-google-genai-2.10.0.tgz"
	"https://registry.npmjs.org/google-logging-utils/-/google-logging-utils-1.1.3.tgz -> openclaw-bin-npm-google-logging-utils-1.1.3.tgz"
	"https://registry.npmjs.org/gopd/-/gopd-1.2.0.tgz -> openclaw-bin-npm-gopd-1.2.0.tgz"
	"https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.11.tgz -> openclaw-bin-npm-graceful-fs-4.2.11.tgz"
	"https://registry.npmjs.org/grammy/-/grammy-1.44.0.tgz -> openclaw-bin-npm-grammy-1.44.0.tgz"
	"https://registry.npmjs.org/@grammyjs/runner/-/runner-2.0.3.tgz -> openclaw-bin-npm-grammyjs-runner-2.0.3.tgz"
	"https://registry.npmjs.org/@grammyjs/transformer-throttler/-/transformer-throttler-1.2.1.tgz -> openclaw-bin-npm-grammyjs-transformer-throttler-1.2.1.tgz"
	"https://registry.npmjs.org/@grammyjs/types/-/types-3.28.0.tgz -> openclaw-bin-npm-grammyjs-types-3.28.0.tgz"
	"https://registry.npmjs.org/has-symbols/-/has-symbols-1.1.0.tgz -> openclaw-bin-npm-has-symbols-1.1.0.tgz"
	"https://registry.npmjs.org/hasown/-/hasown-2.0.4.tgz -> openclaw-bin-npm-hasown-2.0.4.tgz"
	"https://registry.npmjs.org/highlight.js/-/highlight.js-11.11.1.tgz -> openclaw-bin-npm-highlight.js-11.11.1.tgz"
	"https://registry.npmjs.org/@homebridge/ciao/-/ciao-1.3.9.tgz -> openclaw-bin-npm-homebridge-ciao-1.3.9.tgz"
	"https://registry.npmjs.org/hono/-/hono-4.12.25.tgz -> openclaw-bin-npm-hono-4.12.25.tgz"
	"https://registry.npmjs.org/@hono/node-server/-/node-server-1.19.14.tgz -> openclaw-bin-npm-hono-node-server-1.19.14.tgz"
	"https://registry.npmjs.org/hosted-git-info/-/hosted-git-info-10.1.1.tgz -> openclaw-bin-npm-hosted-git-info-10.1.1.tgz"
	"https://registry.npmjs.org/html-escaper/-/html-escaper-3.0.3.tgz -> openclaw-bin-npm-html-escaper-3.0.3.tgz"
	"https://registry.npmjs.org/htmlparser2/-/htmlparser2-10.1.0.tgz -> openclaw-bin-npm-htmlparser2-10.1.0.tgz"
	"https://registry.npmjs.org/http-errors/-/http-errors-2.0.1.tgz -> openclaw-bin-npm-http-errors-2.0.1.tgz"
	"https://registry.npmjs.org/http_ece/-/http_ece-1.2.0.tgz -> openclaw-bin-npm-http_ece-1.2.0.tgz"
	"https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-7.0.6.tgz -> openclaw-bin-npm-https-proxy-agent-7.0.6.tgz"
	"https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.7.2.tgz -> openclaw-bin-npm-iconv-lite-0.7.2.tgz"
	"https://registry.npmjs.org/ieee754/-/ieee754-1.2.1.tgz -> openclaw-bin-npm-ieee754-1.2.1.tgz"
	"https://registry.npmjs.org/ignore/-/ignore-7.0.5.tgz -> openclaw-bin-npm-ignore-7.0.5.tgz"
	"https://registry.npmjs.org/immediate/-/immediate-3.0.6.tgz -> openclaw-bin-npm-immediate-3.0.6.tgz"
	"https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz -> openclaw-bin-npm-inherits-2.0.4.tgz"
	"https://registry.npmjs.org/ip-address/-/ip-address-10.2.0.tgz -> openclaw-bin-npm-ip-address-10.2.0.tgz"
	"https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.9.1.tgz -> openclaw-bin-npm-ipaddr.js-1.9.1.tgz"
	"https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz -> openclaw-bin-npm-is-fullwidth-code-point-3.0.0.tgz"
	"https://registry.npmjs.org/is-promise/-/is-promise-4.0.0.tgz -> openclaw-bin-npm-is-promise-4.0.0.tgz"
	"https://registry.npmjs.org/@isaacs/fs-minipass/-/fs-minipass-4.0.1.tgz -> openclaw-bin-npm-isaacs-fs-minipass-4.0.1.tgz"
	"https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz -> openclaw-bin-npm-isarray-1.0.0.tgz"
	"https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz -> openclaw-bin-npm-isexe-2.0.0.tgz"
	"https://registry.npmjs.org/jiti/-/jiti-2.7.0.tgz -> openclaw-bin-npm-jiti-2.7.0.tgz"
	"https://registry.npmjs.org/jose/-/jose-6.2.3.tgz -> openclaw-bin-npm-jose-6.2.3.tgz"
	"https://registry.npmjs.org/json-bigint/-/json-bigint-1.0.0.tgz -> openclaw-bin-npm-json-bigint-1.0.0.tgz"
	"https://registry.npmjs.org/json-schema-to-ts/-/json-schema-to-ts-3.1.1.tgz -> openclaw-bin-npm-json-schema-to-ts-3.1.1.tgz"
	"https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-1.0.0.tgz -> openclaw-bin-npm-json-schema-traverse-1.0.0.tgz"
	"https://registry.npmjs.org/json-schema-typed/-/json-schema-typed-8.0.2.tgz -> openclaw-bin-npm-json-schema-typed-8.0.2.tgz"
	"https://registry.npmjs.org/json5/-/json5-2.2.3.tgz -> openclaw-bin-npm-json5-2.2.3.tgz"
	"https://registry.npmjs.org/jszip/-/jszip-3.10.1.tgz -> openclaw-bin-npm-jszip-3.10.1.tgz"
	"https://registry.npmjs.org/jwa/-/jwa-2.0.1.tgz -> openclaw-bin-npm-jwa-2.0.1.tgz"
	"https://registry.npmjs.org/jws/-/jws-4.0.1.tgz -> openclaw-bin-npm-jws-4.0.1.tgz"
	"https://registry.npmjs.org/kysely/-/kysely-0.29.2.tgz -> openclaw-bin-npm-kysely-0.29.2.tgz"
	"https://registry.npmjs.org/lie/-/lie-3.3.0.tgz -> openclaw-bin-npm-lie-3.3.0.tgz"
	"https://registry.npmjs.org/linkedom/-/linkedom-0.18.12.tgz -> openclaw-bin-npm-linkedom-0.18.12.tgz"
	"https://registry.npmjs.org/locate-path/-/locate-path-5.0.0.tgz -> openclaw-bin-npm-locate-path-5.0.0.tgz"
	"https://registry.npmjs.org/long/-/long-5.3.2.tgz -> openclaw-bin-npm-long-5.3.2.tgz"
	"https://registry.npmjs.org/lru-cache/-/lru-cache-11.5.1.tgz -> openclaw-bin-npm-lru-cache-11.5.1.tgz"
	"https://registry.npmjs.org/@lydell/node-pty/-/node-pty-1.2.0-beta.12.tgz -> openclaw-bin-npm-lydell-node-pty-1.2.0-beta.12.tgz"
	"https://registry.npmjs.org/marked/-/marked-18.0.5.tgz -> openclaw-bin-npm-marked-18.0.5.tgz"
	"https://registry.npmjs.org/math-intrinsics/-/math-intrinsics-1.1.0.tgz -> openclaw-bin-npm-math-intrinsics-1.1.0.tgz"
	"https://registry.npmjs.org/media-typer/-/media-typer-1.1.0.tgz -> openclaw-bin-npm-media-typer-1.1.0.tgz"
	"https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-2.0.0.tgz -> openclaw-bin-npm-merge-descriptors-2.0.0.tgz"
	"https://registry.npmjs.org/mime-db/-/mime-db-1.54.0.tgz -> openclaw-bin-npm-mime-db-1.54.0.tgz"
	"https://registry.npmjs.org/mime-types/-/mime-types-3.0.2.tgz -> openclaw-bin-npm-mime-types-3.0.2.tgz"
	"https://registry.npmjs.org/minimalistic-assert/-/minimalistic-assert-1.0.1.tgz -> openclaw-bin-npm-minimalistic-assert-1.0.1.tgz"
	"https://registry.npmjs.org/minimatch/-/minimatch-10.2.5.tgz -> openclaw-bin-npm-minimatch-10.2.5.tgz"
	"https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz -> openclaw-bin-npm-minimist-1.2.8.tgz"
	"https://registry.npmjs.org/minipass/-/minipass-7.1.3.tgz -> openclaw-bin-npm-minipass-7.1.3.tgz"
	"https://registry.npmjs.org/minizlib/-/minizlib-3.1.0.tgz -> openclaw-bin-npm-minizlib-3.1.0.tgz"
	"https://registry.npmjs.org/@mistralai/mistralai/-/mistralai-2.4.0.tgz -> openclaw-bin-npm-mistralai-mistralai-2.4.0.tgz"
	"https://registry.npmjs.org/@modelcontextprotocol/sdk/-/sdk-1.29.0.tgz -> openclaw-bin-npm-modelcontextprotocol-sdk-1.29.0.tgz"
	"https://registry.npmjs.org/@mozilla/readability/-/readability-0.6.0.tgz -> openclaw-bin-npm-mozilla-readability-0.6.0.tgz"
	"https://registry.npmjs.org/ms/-/ms-2.1.3.tgz -> openclaw-bin-npm-ms-2.1.3.tgz"
	"https://registry.npmjs.org/negotiator/-/negotiator-1.0.0.tgz -> openclaw-bin-npm-negotiator-1.0.0.tgz"
	"https://registry.npmjs.org/node-addon-api/-/node-addon-api-8.9.0.tgz -> openclaw-bin-npm-node-addon-api-8.9.0.tgz"
	"https://registry.npmjs.org/@nolyfill/domexception/-/domexception-1.0.28.tgz -> openclaw-bin-npm-node-domexception-1.0.28.tgz"
	"https://registry.npmjs.org/node-edge-tts/-/node-edge-tts-1.2.10.tgz -> openclaw-bin-npm-node-edge-tts-1.2.10.tgz"
	"https://registry.npmjs.org/node-fetch/-/node-fetch-2.7.0.tgz -> openclaw-bin-npm-node-fetch-2.7.0.tgz"
	"https://registry.npmjs.org/node-fetch/-/node-fetch-3.3.2.tgz -> openclaw-bin-npm-node-fetch-3.3.2.tgz"
	"https://registry.npmjs.org/node-gyp-build/-/node-gyp-build-4.8.4.tgz -> openclaw-bin-npm-node-gyp-build-4.8.4.tgz"
	"https://registry.npmjs.org/nth-check/-/nth-check-2.1.1.tgz -> openclaw-bin-npm-nth-check-2.1.1.tgz"
	"https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz -> openclaw-bin-npm-object-assign-4.1.1.tgz"
	"https://registry.npmjs.org/object-inspect/-/object-inspect-1.13.4.tgz -> openclaw-bin-npm-object-inspect-1.13.4.tgz"
	"https://registry.npmjs.org/on-finished/-/on-finished-2.4.1.tgz -> openclaw-bin-npm-on-finished-2.4.1.tgz"
	"https://registry.npmjs.org/once/-/once-1.4.0.tgz -> openclaw-bin-npm-once-1.4.0.tgz"
	"https://registry.npmjs.org/openai/-/openai-6.45.0.tgz -> openclaw-bin-npm-openai-6.45.0.tgz"
	"https://registry.npmjs.org/@openclaw/ai/-/ai-2026.7.1-2.tgz -> openclaw-bin-npm-openclaw-ai-2026.7.1-2.tgz"
	"https://registry.npmjs.org/@openclaw/fs-safe/-/fs-safe-0.4.1.tgz -> openclaw-bin-npm-openclaw-fs-safe-0.4.1.tgz"
	"https://registry.npmjs.org/@openclaw/proxyline/-/proxyline-0.3.3.tgz -> openclaw-bin-npm-openclaw-proxyline-0.3.3.tgz"
	"https://registry.npmjs.org/@opentelemetry/semantic-conventions/-/semantic-conventions-1.41.1.tgz -> openclaw-bin-npm-opentelemetry-semantic-conventions-1.41.1.tgz"
	"https://registry.npmjs.org/p-limit/-/p-limit-2.3.0.tgz -> openclaw-bin-npm-p-limit-2.3.0.tgz"
	"https://registry.npmjs.org/p-locate/-/p-locate-4.1.0.tgz -> openclaw-bin-npm-p-locate-4.1.0.tgz"
	"https://registry.npmjs.org/p-retry/-/p-retry-4.6.2.tgz -> openclaw-bin-npm-p-retry-4.6.2.tgz"
	"https://registry.npmjs.org/p-try/-/p-try-2.2.0.tgz -> openclaw-bin-npm-p-try-2.2.0.tgz"
	"https://registry.npmjs.org/pako/-/pako-1.0.11.tgz -> openclaw-bin-npm-pako-1.0.11.tgz"
	"https://registry.npmjs.org/parseurl/-/parseurl-1.3.3.tgz -> openclaw-bin-npm-parseurl-1.3.3.tgz"
	"https://registry.npmjs.org/partial-json/-/partial-json-0.1.7.tgz -> openclaw-bin-npm-partial-json-0.1.7.tgz"
	"https://registry.npmjs.org/path-exists/-/path-exists-4.0.0.tgz -> openclaw-bin-npm-path-exists-4.0.0.tgz"
	"https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz -> openclaw-bin-npm-path-key-3.1.1.tgz"
	"https://registry.npmjs.org/path-scurry/-/path-scurry-2.0.2.tgz -> openclaw-bin-npm-path-scurry-2.0.2.tgz"
	"https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-8.4.0.tgz -> openclaw-bin-npm-path-to-regexp-8.4.0.tgz"
	"https://registry.npmjs.org/pkce-challenge/-/pkce-challenge-5.0.1.tgz -> openclaw-bin-npm-pkce-challenge-5.0.1.tgz"
	"https://registry.npmjs.org/playwright-core/-/playwright-core-1.61.1.tgz -> openclaw-bin-npm-playwright-core-1.61.1.tgz"
	"https://registry.npmjs.org/pngjs/-/pngjs-5.0.0.tgz -> openclaw-bin-npm-pngjs-5.0.0.tgz"
	"https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.1.tgz -> openclaw-bin-npm-process-nextick-args-2.0.1.tgz"
	"https://registry.npmjs.org/proper-lockfile/-/proper-lockfile-4.1.2.tgz -> openclaw-bin-npm-proper-lockfile-4.1.2.tgz"
	"https://registry.npmjs.org/protobufjs/-/protobufjs-7.6.3.tgz -> openclaw-bin-npm-protobufjs-7.6.3.tgz"
	"https://registry.npmjs.org/@protobufjs/aspromise/-/aspromise-1.1.2.tgz -> openclaw-bin-npm-protobufjs-aspromise-1.1.2.tgz"
	"https://registry.npmjs.org/@protobufjs/base64/-/base64-1.1.2.tgz -> openclaw-bin-npm-protobufjs-base64-1.1.2.tgz"
	"https://registry.npmjs.org/@protobufjs/codegen/-/codegen-2.0.5.tgz -> openclaw-bin-npm-protobufjs-codegen-2.0.5.tgz"
	"https://registry.npmjs.org/@protobufjs/eventemitter/-/eventemitter-1.1.1.tgz -> openclaw-bin-npm-protobufjs-eventemitter-1.1.1.tgz"
	"https://registry.npmjs.org/@protobufjs/fetch/-/fetch-1.1.1.tgz -> openclaw-bin-npm-protobufjs-fetch-1.1.1.tgz"
	"https://registry.npmjs.org/@protobufjs/float/-/float-1.0.2.tgz -> openclaw-bin-npm-protobufjs-float-1.0.2.tgz"
	"https://registry.npmjs.org/@protobufjs/inquire/-/inquire-1.1.2.tgz -> openclaw-bin-npm-protobufjs-inquire-1.1.2.tgz"
	"https://registry.npmjs.org/@protobufjs/path/-/path-1.1.2.tgz -> openclaw-bin-npm-protobufjs-path-1.1.2.tgz"
	"https://registry.npmjs.org/@protobufjs/pool/-/pool-1.1.0.tgz -> openclaw-bin-npm-protobufjs-pool-1.1.0.tgz"
	"https://registry.npmjs.org/@protobufjs/utf8/-/utf8-1.1.1.tgz -> openclaw-bin-npm-protobufjs-utf8-1.1.1.tgz"
	"https://registry.npmjs.org/proxy-addr/-/proxy-addr-2.0.7.tgz -> openclaw-bin-npm-proxy-addr-2.0.7.tgz"
	"https://registry.npmjs.org/qrcode/-/qrcode-1.5.4.tgz -> openclaw-bin-npm-qrcode-1.5.4.tgz"
	"https://registry.npmjs.org/qs/-/qs-6.15.2.tgz -> openclaw-bin-npm-qs-6.15.2.tgz"
	"https://registry.npmjs.org/quickjs-wasi/-/quickjs-wasi-3.0.2.tgz -> openclaw-bin-npm-quickjs-wasi-3.0.2.tgz"
	"https://registry.npmjs.org/range-parser/-/range-parser-1.3.0.tgz -> openclaw-bin-npm-range-parser-1.3.0.tgz"
	"https://registry.npmjs.org/rastermill/-/rastermill-0.3.1.tgz -> openclaw-bin-npm-rastermill-0.3.1.tgz"
	"https://registry.npmjs.org/raw-body/-/raw-body-3.0.2.tgz -> openclaw-bin-npm-raw-body-3.0.2.tgz"
	"https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.8.tgz -> openclaw-bin-npm-readable-stream-2.3.8.tgz"
	"https://registry.npmjs.org/readdirp/-/readdirp-5.0.0.tgz -> openclaw-bin-npm-readdirp-5.0.0.tgz"
	"https://registry.npmjs.org/require-directory/-/require-directory-2.1.1.tgz -> openclaw-bin-npm-require-directory-2.1.1.tgz"
	"https://registry.npmjs.org/require-from-string/-/require-from-string-2.0.2.tgz -> openclaw-bin-npm-require-from-string-2.0.2.tgz"
	"https://registry.npmjs.org/require-main-filename/-/require-main-filename-2.0.0.tgz -> openclaw-bin-npm-require-main-filename-2.0.0.tgz"
	"https://registry.npmjs.org/retry/-/retry-0.12.0.tgz -> openclaw-bin-npm-retry-0.12.0.tgz"
	"https://registry.npmjs.org/retry/-/retry-0.13.1.tgz -> openclaw-bin-npm-retry-0.13.1.tgz"
	"https://registry.npmjs.org/router/-/router-2.2.0.tgz -> openclaw-bin-npm-router-2.2.0.tgz"
	"https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz -> openclaw-bin-npm-safe-buffer-5.1.2.tgz"
	"https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz -> openclaw-bin-npm-safe-buffer-5.2.1.tgz"
	"https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz -> openclaw-bin-npm-safer-buffer-2.1.2.tgz"
	"https://registry.npmjs.org/send/-/send-1.2.1.tgz -> openclaw-bin-npm-send-1.2.1.tgz"
	"https://registry.npmjs.org/serve-static/-/serve-static-2.2.1.tgz -> openclaw-bin-npm-serve-static-2.2.1.tgz"
	"https://registry.npmjs.org/set-blocking/-/set-blocking-2.0.0.tgz -> openclaw-bin-npm-set-blocking-2.0.0.tgz"
	"https://registry.npmjs.org/setimmediate/-/setimmediate-1.0.5.tgz -> openclaw-bin-npm-setimmediate-1.0.5.tgz"
	"https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.2.0.tgz -> openclaw-bin-npm-setprototypeof-1.2.0.tgz"
	"https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz -> openclaw-bin-npm-shebang-command-2.0.0.tgz"
	"https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz -> openclaw-bin-npm-shebang-regex-3.0.0.tgz"
	"https://registry.npmjs.org/side-channel/-/side-channel-1.1.1.tgz -> openclaw-bin-npm-side-channel-1.1.1.tgz"
	"https://registry.npmjs.org/side-channel-list/-/side-channel-list-1.0.1.tgz -> openclaw-bin-npm-side-channel-list-1.0.1.tgz"
	"https://registry.npmjs.org/side-channel-map/-/side-channel-map-1.0.1.tgz -> openclaw-bin-npm-side-channel-map-1.0.1.tgz"
	"https://registry.npmjs.org/side-channel-weakmap/-/side-channel-weakmap-1.0.2.tgz -> openclaw-bin-npm-side-channel-weakmap-1.0.2.tgz"
	"https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.7.tgz -> openclaw-bin-npm-signal-exit-3.0.7.tgz"
	"https://registry.npmjs.org/@silvia-odwyer/photon-node/-/photon-node-0.3.4.tgz -> openclaw-bin-npm-silvia-odwyer-photon-node-0.3.4.tgz"
	"https://registry.npmjs.org/sisteransi/-/sisteransi-1.0.5.tgz -> openclaw-bin-npm-sisteransi-1.0.5.tgz"
	"https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz -> openclaw-bin-npm-source-map-0.6.1.tgz"
	"https://registry.npmjs.org/source-map-support/-/source-map-support-0.5.21.tgz -> openclaw-bin-npm-source-map-support-0.5.21.tgz"
	"https://registry.npmjs.org/sqlite-vec/-/sqlite-vec-0.1.9.tgz -> openclaw-bin-npm-sqlite-vec-0.1.9.tgz"
	"https://registry.npmjs.org/@stablelib/base64/-/base64-1.0.1.tgz -> openclaw-bin-npm-stablelib-base64-1.0.1.tgz"
	"https://registry.npmjs.org/standardwebhooks/-/standardwebhooks-1.0.0.tgz -> openclaw-bin-npm-standardwebhooks-1.0.0.tgz"
	"https://registry.npmjs.org/statuses/-/statuses-2.0.2.tgz -> openclaw-bin-npm-statuses-2.0.2.tgz"
	"https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz -> openclaw-bin-npm-string-width-4.2.3.tgz"
	"https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz -> openclaw-bin-npm-string_decoder-1.1.1.tgz"
	"https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz -> openclaw-bin-npm-strip-ansi-6.0.1.tgz"
	"https://registry.npmjs.org/strtok3/-/strtok3-10.3.5.tgz -> openclaw-bin-npm-strtok3-10.3.5.tgz"
	"https://registry.npmjs.org/tar/-/tar-7.5.19.tgz -> openclaw-bin-npm-tar-7.5.19.tgz"
	"https://registry.npmjs.org/toidentifier/-/toidentifier-1.0.1.tgz -> openclaw-bin-npm-toidentifier-1.0.1.tgz"
	"https://registry.npmjs.org/token-types/-/token-types-6.1.2.tgz -> openclaw-bin-npm-token-types-6.1.2.tgz"
	"https://registry.npmjs.org/@tokenizer/inflate/-/inflate-0.4.1.tgz -> openclaw-bin-npm-tokenizer-inflate-0.4.1.tgz"
	"https://registry.npmjs.org/@tokenizer/token/-/token-0.3.0.tgz -> openclaw-bin-npm-tokenizer-token-0.3.0.tgz"
	"https://registry.npmjs.org/tr46/-/tr46-0.0.3.tgz -> openclaw-bin-npm-tr46-0.0.3.tgz"
	"https://registry.npmjs.org/tree-sitter-bash/-/tree-sitter-bash-0.25.1.tgz -> openclaw-bin-npm-tree-sitter-bash-0.25.1.tgz"
	"https://registry.npmjs.org/ts-algebra/-/ts-algebra-2.0.0.tgz -> openclaw-bin-npm-ts-algebra-2.0.0.tgz"
	"https://registry.npmjs.org/tslib/-/tslib-2.8.1.tgz -> openclaw-bin-npm-tslib-2.8.1.tgz"
	"https://registry.npmjs.org/tslog/-/tslog-4.10.2.tgz -> openclaw-bin-npm-tslog-4.10.2.tgz"
	"https://registry.npmjs.org/type-is/-/type-is-2.1.0.tgz -> openclaw-bin-npm-type-is-2.1.0.tgz"
	"https://registry.npmjs.org/typebox/-/typebox-1.3.3.tgz -> openclaw-bin-npm-typebox-1.3.3.tgz"
	"https://registry.npmjs.org/@types/node/-/node-26.1.0.tgz -> openclaw-bin-npm-types-node-26.1.0.tgz"
	"https://registry.npmjs.org/@types/retry/-/retry-0.12.5.tgz -> openclaw-bin-npm-types-retry-0.12.5.tgz"
	"https://registry.npmjs.org/typescript/-/typescript-6.0.3.tgz -> openclaw-bin-npm-typescript-6.0.3.tgz"
	"https://registry.npmjs.org/uhyphen/-/uhyphen-0.2.0.tgz -> openclaw-bin-npm-uhyphen-0.2.0.tgz"
	"https://registry.npmjs.org/uint8array-extras/-/uint8array-extras-1.5.0.tgz -> openclaw-bin-npm-uint8array-extras-1.5.0.tgz"
	"https://registry.npmjs.org/undici/-/undici-8.5.0.tgz -> openclaw-bin-npm-undici-8.5.0.tgz"
	"https://registry.npmjs.org/undici-types/-/undici-types-8.3.0.tgz -> openclaw-bin-npm-undici-types-8.3.0.tgz"
	"https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz -> openclaw-bin-npm-unpipe-1.0.0.tgz"
	"https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz -> openclaw-bin-npm-util-deprecate-1.0.2.tgz"
	"https://registry.npmjs.org/vary/-/vary-1.1.2.tgz -> openclaw-bin-npm-vary-1.1.2.tgz"
	"https://registry.npmjs.org/web-push/-/web-push-3.6.7.tgz -> openclaw-bin-npm-web-push-3.6.7.tgz"
	"https://registry.npmjs.org/web-streams-polyfill/-/web-streams-polyfill-3.3.3.tgz -> openclaw-bin-npm-web-streams-polyfill-3.3.3.tgz"
	"https://registry.npmjs.org/web-tree-sitter/-/web-tree-sitter-0.26.10.tgz -> openclaw-bin-npm-web-tree-sitter-0.26.10.tgz"
	"https://registry.npmjs.org/webidl-conversions/-/webidl-conversions-3.0.1.tgz -> openclaw-bin-npm-webidl-conversions-3.0.1.tgz"
	"https://registry.npmjs.org/whatwg-url/-/whatwg-url-5.0.0.tgz -> openclaw-bin-npm-whatwg-url-5.0.0.tgz"
	"https://registry.npmjs.org/which/-/which-2.0.2.tgz -> openclaw-bin-npm-which-2.0.2.tgz"
	"https://registry.npmjs.org/which-module/-/which-module-2.0.1.tgz -> openclaw-bin-npm-which-module-2.0.1.tgz"
	"https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-6.2.0.tgz -> openclaw-bin-npm-wrap-ansi-6.2.0.tgz"
	"https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-7.0.0.tgz -> openclaw-bin-npm-wrap-ansi-7.0.0.tgz"
	"https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz -> openclaw-bin-npm-wrappy-1.0.2.tgz"
	"https://registry.npmjs.org/ws/-/ws-8.21.0.tgz -> openclaw-bin-npm-ws-8.21.0.tgz"
	"https://registry.npmjs.org/y18n/-/y18n-4.0.3.tgz -> openclaw-bin-npm-y18n-4.0.3.tgz"
	"https://registry.npmjs.org/y18n/-/y18n-5.0.8.tgz -> openclaw-bin-npm-y18n-5.0.8.tgz"
	"https://registry.npmjs.org/yallist/-/yallist-5.0.0.tgz -> openclaw-bin-npm-yallist-5.0.0.tgz"
	"https://registry.npmjs.org/yaml/-/yaml-2.9.0.tgz -> openclaw-bin-npm-yaml-2.9.0.tgz"
	"https://registry.npmjs.org/yargs/-/yargs-15.4.1.tgz -> openclaw-bin-npm-yargs-15.4.1.tgz"
	"https://registry.npmjs.org/yargs/-/yargs-17.7.3.tgz -> openclaw-bin-npm-yargs-17.7.3.tgz"
	"https://registry.npmjs.org/yargs-parser/-/yargs-parser-18.1.3.tgz -> openclaw-bin-npm-yargs-parser-18.1.3.tgz"
	"https://registry.npmjs.org/yargs-parser/-/yargs-parser-21.1.1.tgz -> openclaw-bin-npm-yargs-parser-21.1.1.tgz"
	"https://registry.npmjs.org/zod/-/zod-4.4.3.tgz -> openclaw-bin-npm-zod-4.4.3.tgz"
	"https://registry.npmjs.org/zod-to-json-schema/-/zod-to-json-schema-3.25.2.tgz -> openclaw-bin-npm-zod-to-json-schema-3.25.2.tgz"
)

OPENCLAW_NPM_SRC_URI_AMD64=(
	"https://registry.npmjs.org/@lydell/node-pty-linux-x64/-/node-pty-linux-x64-1.2.0-beta.12.tgz -> openclaw-bin-npm-lydell-node-pty-linux-x64-1.2.0-beta.12.tgz"
	"https://registry.npmjs.org/sqlite-vec-linux-x64/-/sqlite-vec-linux-x64-0.1.9.tgz -> openclaw-bin-npm-sqlite-vec-linux-x64-0.1.9.tgz"
)

OPENCLAW_NPM_SRC_URI_ARM64=(
	"https://registry.npmjs.org/@lydell/node-pty-linux-arm64/-/node-pty-linux-arm64-1.2.0-beta.12.tgz -> openclaw-bin-npm-lydell-node-pty-linux-arm64-1.2.0-beta.12.tgz"
	"https://registry.npmjs.org/sqlite-vec-linux-arm64/-/sqlite-vec-linux-arm64-0.1.9.tgz -> openclaw-bin-npm-sqlite-vec-linux-arm64-0.1.9.tgz"
)

# node_modules/<path> -> distfile, one per line
OPENCLAW_NPM_PATHS=(
	"node_modules/@agentclientprotocol/sdk|openclaw-bin-npm-agentclientprotocol-sdk-1.1.0.tgz"
	"node_modules/@anthropic-ai/sdk|openclaw-bin-npm-anthropic-ai-sdk-0.109.1.tgz"
	"node_modules/@babel/runtime|openclaw-bin-npm-babel-runtime-7.29.7.tgz"
	"node_modules/@borewit/text-codec|openclaw-bin-npm-borewit-text-codec-0.2.2.tgz"
	"node_modules/@clack/core|openclaw-bin-npm-clack-core-1.4.2.tgz"
	"node_modules/@clack/prompts|openclaw-bin-npm-clack-prompts-1.6.0.tgz"
	"node_modules/@earendil-works/pi-tui|openclaw-bin-npm-earendil-works-pi-tui-0.80.3.tgz"
	"node_modules/@google/genai|openclaw-bin-npm-google-genai-2.10.0.tgz"
	"node_modules/@grammyjs/runner|openclaw-bin-npm-grammyjs-runner-2.0.3.tgz"
	"node_modules/@grammyjs/transformer-throttler|openclaw-bin-npm-grammyjs-transformer-throttler-1.2.1.tgz"
	"node_modules/@grammyjs/types|openclaw-bin-npm-grammyjs-types-3.28.0.tgz"
	"node_modules/@homebridge/ciao|openclaw-bin-npm-homebridge-ciao-1.3.9.tgz"
	"node_modules/@hono/node-server|openclaw-bin-npm-hono-node-server-1.19.14.tgz"
	"node_modules/@isaacs/fs-minipass|openclaw-bin-npm-isaacs-fs-minipass-4.0.1.tgz"
	"node_modules/@lydell/node-pty|openclaw-bin-npm-lydell-node-pty-1.2.0-beta.12.tgz"
	"node_modules/@mistralai/mistralai|openclaw-bin-npm-mistralai-mistralai-2.4.0.tgz"
	"node_modules/@modelcontextprotocol/sdk|openclaw-bin-npm-modelcontextprotocol-sdk-1.29.0.tgz"
	"node_modules/@mozilla/readability|openclaw-bin-npm-mozilla-readability-0.6.0.tgz"
	"node_modules/@openclaw/ai|openclaw-bin-npm-openclaw-ai-2026.7.1-2.tgz"
	"node_modules/@openclaw/fs-safe|openclaw-bin-npm-openclaw-fs-safe-0.4.1.tgz"
	"node_modules/@openclaw/proxyline|openclaw-bin-npm-openclaw-proxyline-0.3.3.tgz"
	"node_modules/@opentelemetry/semantic-conventions|openclaw-bin-npm-opentelemetry-semantic-conventions-1.41.1.tgz"
	"node_modules/@protobufjs/aspromise|openclaw-bin-npm-protobufjs-aspromise-1.1.2.tgz"
	"node_modules/@protobufjs/base64|openclaw-bin-npm-protobufjs-base64-1.1.2.tgz"
	"node_modules/@protobufjs/codegen|openclaw-bin-npm-protobufjs-codegen-2.0.5.tgz"
	"node_modules/@protobufjs/eventemitter|openclaw-bin-npm-protobufjs-eventemitter-1.1.1.tgz"
	"node_modules/@protobufjs/fetch|openclaw-bin-npm-protobufjs-fetch-1.1.1.tgz"
	"node_modules/@protobufjs/float|openclaw-bin-npm-protobufjs-float-1.0.2.tgz"
	"node_modules/@protobufjs/inquire|openclaw-bin-npm-protobufjs-inquire-1.1.2.tgz"
	"node_modules/@protobufjs/path|openclaw-bin-npm-protobufjs-path-1.1.2.tgz"
	"node_modules/@protobufjs/pool|openclaw-bin-npm-protobufjs-pool-1.1.0.tgz"
	"node_modules/@protobufjs/utf8|openclaw-bin-npm-protobufjs-utf8-1.1.1.tgz"
	"node_modules/@silvia-odwyer/photon-node|openclaw-bin-npm-silvia-odwyer-photon-node-0.3.4.tgz"
	"node_modules/@stablelib/base64|openclaw-bin-npm-stablelib-base64-1.0.1.tgz"
	"node_modules/@tokenizer/inflate|openclaw-bin-npm-tokenizer-inflate-0.4.1.tgz"
	"node_modules/@tokenizer/token|openclaw-bin-npm-tokenizer-token-0.3.0.tgz"
	"node_modules/@types/node|openclaw-bin-npm-types-node-26.1.0.tgz"
	"node_modules/@types/retry|openclaw-bin-npm-types-retry-0.12.5.tgz"
	"node_modules/abort-controller|openclaw-bin-npm-abort-controller-3.0.0.tgz"
	"node_modules/accepts|openclaw-bin-npm-accepts-2.0.0.tgz"
	"node_modules/agent-base|openclaw-bin-npm-agent-base-7.1.4.tgz"
	"node_modules/ajv|openclaw-bin-npm-ajv-8.20.0.tgz"
	"node_modules/ajv-formats|openclaw-bin-npm-ajv-formats-3.0.1.tgz"
	"node_modules/ansi-regex|openclaw-bin-npm-ansi-regex-5.0.1.tgz"
	"node_modules/ansi-styles|openclaw-bin-npm-ansi-styles-4.3.0.tgz"
	"node_modules/asn1.js|openclaw-bin-npm-asn1.js-5.4.1.tgz"
	"node_modules/balanced-match|openclaw-bin-npm-balanced-match-4.0.4.tgz"
	"node_modules/base64-js|openclaw-bin-npm-base64-js-1.5.1.tgz"
	"node_modules/bignumber.js|openclaw-bin-npm-bignumber.js-9.3.1.tgz"
	"node_modules/bn.js|openclaw-bin-npm-bn.js-4.12.4.tgz"
	"node_modules/body-parser|openclaw-bin-npm-body-parser-2.3.0.tgz"
	"node_modules/body-parser/node_modules/content-type|openclaw-bin-npm-content-type-2.0.0.tgz"
	"node_modules/boolbase|openclaw-bin-npm-boolbase-1.0.0.tgz"
	"node_modules/bottleneck|openclaw-bin-npm-bottleneck-2.19.5.tgz"
	"node_modules/brace-expansion|openclaw-bin-npm-brace-expansion-5.0.7.tgz"
	"node_modules/buffer-equal-constant-time|openclaw-bin-npm-buffer-equal-constant-time-1.0.1.tgz"
	"node_modules/buffer-from|openclaw-bin-npm-buffer-from-1.1.2.tgz"
	"node_modules/bytes|openclaw-bin-npm-bytes-3.1.2.tgz"
	"node_modules/call-bind-apply-helpers|openclaw-bin-npm-call-bind-apply-helpers-1.0.2.tgz"
	"node_modules/call-bound|openclaw-bin-npm-call-bound-1.0.4.tgz"
	"node_modules/camelcase|openclaw-bin-npm-camelcase-5.3.1.tgz"
	"node_modules/chalk|openclaw-bin-npm-chalk-5.6.2.tgz"
	"node_modules/chokidar|openclaw-bin-npm-chokidar-5.0.0.tgz"
	"node_modules/chownr|openclaw-bin-npm-chownr-3.0.0.tgz"
	"node_modules/clawpdf|openclaw-bin-npm-clawpdf-0.3.0.tgz"
	"node_modules/cliui|openclaw-bin-npm-cliui-8.0.1.tgz"
	"node_modules/color-convert|openclaw-bin-npm-color-convert-2.0.1.tgz"
	"node_modules/color-name|openclaw-bin-npm-color-name-1.1.4.tgz"
	"node_modules/commander|openclaw-bin-npm-commander-15.0.0.tgz"
	"node_modules/content-disposition|openclaw-bin-npm-content-disposition-1.1.0.tgz"
	"node_modules/content-type|openclaw-bin-npm-content-type-1.0.5.tgz"
	"node_modules/cookie|openclaw-bin-npm-cookie-0.7.2.tgz"
	"node_modules/cookie-signature|openclaw-bin-npm-cookie-signature-1.2.2.tgz"
	"node_modules/core-util-is|openclaw-bin-npm-core-util-is-1.0.3.tgz"
	"node_modules/cors|openclaw-bin-npm-cors-2.8.6.tgz"
	"node_modules/croner|openclaw-bin-npm-croner-10.0.1.tgz"
	"node_modules/cross-spawn|openclaw-bin-npm-cross-spawn-7.0.6.tgz"
	"node_modules/css-select|openclaw-bin-npm-css-select-5.2.2.tgz"
	"node_modules/css-what|openclaw-bin-npm-css-what-6.2.2.tgz"
	"node_modules/cssom|openclaw-bin-npm-cssom-0.5.0.tgz"
	"node_modules/data-uri-to-buffer|openclaw-bin-npm-data-uri-to-buffer-4.0.1.tgz"
	"node_modules/debug|openclaw-bin-npm-debug-4.4.3.tgz"
	"node_modules/decamelize|openclaw-bin-npm-decamelize-1.2.0.tgz"
	"node_modules/depd|openclaw-bin-npm-depd-2.0.0.tgz"
	"node_modules/diff|openclaw-bin-npm-diff-9.0.0.tgz"
	"node_modules/dijkstrajs|openclaw-bin-npm-dijkstrajs-1.0.3.tgz"
	"node_modules/dom-serializer|openclaw-bin-npm-dom-serializer-2.0.0.tgz"
	"node_modules/domelementtype|openclaw-bin-npm-domelementtype-2.3.0.tgz"
	"node_modules/domhandler|openclaw-bin-npm-domhandler-5.0.3.tgz"
	"node_modules/domutils|openclaw-bin-npm-domutils-3.2.2.tgz"
	"node_modules/dotenv|openclaw-bin-npm-dotenv-17.4.2.tgz"
	"node_modules/dunder-proto|openclaw-bin-npm-dunder-proto-1.0.1.tgz"
	"node_modules/ecdsa-sig-formatter|openclaw-bin-npm-ecdsa-sig-formatter-1.0.11.tgz"
	"node_modules/ee-first|openclaw-bin-npm-ee-first-1.1.1.tgz"
	"node_modules/emoji-regex|openclaw-bin-npm-emoji-regex-8.0.0.tgz"
	"node_modules/encodeurl|openclaw-bin-npm-encodeurl-2.0.0.tgz"
	"node_modules/entities|openclaw-bin-npm-entities-4.5.0.tgz"
	"node_modules/es-define-property|openclaw-bin-npm-es-define-property-1.0.1.tgz"
	"node_modules/es-errors|openclaw-bin-npm-es-errors-1.3.0.tgz"
	"node_modules/es-object-atoms|openclaw-bin-npm-es-object-atoms-1.1.2.tgz"
	"node_modules/escalade|openclaw-bin-npm-escalade-3.2.0.tgz"
	"node_modules/escape-html|openclaw-bin-npm-escape-html-1.0.3.tgz"
	"node_modules/etag|openclaw-bin-npm-etag-1.8.1.tgz"
	"node_modules/event-target-shim|openclaw-bin-npm-event-target-shim-5.0.1.tgz"
	"node_modules/eventsource|openclaw-bin-npm-eventsource-3.0.7.tgz"
	"node_modules/eventsource-parser|openclaw-bin-npm-eventsource-parser-3.1.0.tgz"
	"node_modules/express|openclaw-bin-npm-express-5.2.1.tgz"
	"node_modules/express-rate-limit|openclaw-bin-npm-express-rate-limit-8.5.2.tgz"
	"node_modules/extend|openclaw-bin-npm-extend-3.0.2.tgz"
	"node_modules/fast-deep-equal|openclaw-bin-npm-fast-deep-equal-3.1.3.tgz"
	"node_modules/fast-sha256|openclaw-bin-npm-fast-sha256-1.3.0.tgz"
	"node_modules/fast-string-truncated-width|openclaw-bin-npm-fast-string-truncated-width-3.0.3.tgz"
	"node_modules/fast-string-width|openclaw-bin-npm-fast-string-width-3.0.2.tgz"
	"node_modules/fast-uri|openclaw-bin-npm-fast-uri-3.1.2.tgz"
	"node_modules/fast-wrap-ansi|openclaw-bin-npm-fast-wrap-ansi-0.2.2.tgz"
	"node_modules/fetch-blob|openclaw-bin-npm-fetch-blob-3.2.0.tgz"
	"node_modules/file-type|openclaw-bin-npm-file-type-22.0.1.tgz"
	"node_modules/finalhandler|openclaw-bin-npm-finalhandler-2.1.1.tgz"
	"node_modules/find-up|openclaw-bin-npm-find-up-4.1.0.tgz"
	"node_modules/formdata-polyfill|openclaw-bin-npm-formdata-polyfill-4.0.10.tgz"
	"node_modules/forwarded|openclaw-bin-npm-forwarded-0.2.0.tgz"
	"node_modules/fresh|openclaw-bin-npm-fresh-2.0.0.tgz"
	"node_modules/function-bind|openclaw-bin-npm-function-bind-1.1.2.tgz"
	"node_modules/gaxios|openclaw-bin-npm-gaxios-7.1.5.tgz"
	"node_modules/gcp-metadata|openclaw-bin-npm-gcp-metadata-8.1.2.tgz"
	"node_modules/get-caller-file|openclaw-bin-npm-get-caller-file-2.0.5.tgz"
	"node_modules/get-east-asian-width|openclaw-bin-npm-get-east-asian-width-1.6.0.tgz"
	"node_modules/get-intrinsic|openclaw-bin-npm-get-intrinsic-1.3.0.tgz"
	"node_modules/get-proto|openclaw-bin-npm-get-proto-1.0.1.tgz"
	"node_modules/glob|openclaw-bin-npm-glob-13.0.6.tgz"
	"node_modules/google-auth-library|openclaw-bin-npm-google-auth-library-10.9.0.tgz"
	"node_modules/google-logging-utils|openclaw-bin-npm-google-logging-utils-1.1.3.tgz"
	"node_modules/gopd|openclaw-bin-npm-gopd-1.2.0.tgz"
	"node_modules/graceful-fs|openclaw-bin-npm-graceful-fs-4.2.11.tgz"
	"node_modules/grammy|openclaw-bin-npm-grammy-1.44.0.tgz"
	"node_modules/grammy/node_modules/node-fetch|openclaw-bin-npm-node-fetch-2.7.0.tgz"
	"node_modules/has-symbols|openclaw-bin-npm-has-symbols-1.1.0.tgz"
	"node_modules/hasown|openclaw-bin-npm-hasown-2.0.4.tgz"
	"node_modules/highlight.js|openclaw-bin-npm-highlight.js-11.11.1.tgz"
	"node_modules/hono|openclaw-bin-npm-hono-4.12.25.tgz"
	"node_modules/hosted-git-info|openclaw-bin-npm-hosted-git-info-10.1.1.tgz"
	"node_modules/html-escaper|openclaw-bin-npm-html-escaper-3.0.3.tgz"
	"node_modules/htmlparser2|openclaw-bin-npm-htmlparser2-10.1.0.tgz"
	"node_modules/htmlparser2/node_modules/entities|openclaw-bin-npm-entities-7.0.1.tgz"
	"node_modules/http-errors|openclaw-bin-npm-http-errors-2.0.1.tgz"
	"node_modules/http_ece|openclaw-bin-npm-http_ece-1.2.0.tgz"
	"node_modules/https-proxy-agent|openclaw-bin-npm-https-proxy-agent-7.0.6.tgz"
	"node_modules/iconv-lite|openclaw-bin-npm-iconv-lite-0.7.2.tgz"
	"node_modules/ieee754|openclaw-bin-npm-ieee754-1.2.1.tgz"
	"node_modules/ignore|openclaw-bin-npm-ignore-7.0.5.tgz"
	"node_modules/immediate|openclaw-bin-npm-immediate-3.0.6.tgz"
	"node_modules/inherits|openclaw-bin-npm-inherits-2.0.4.tgz"
	"node_modules/ip-address|openclaw-bin-npm-ip-address-10.2.0.tgz"
	"node_modules/ipaddr.js|openclaw-bin-npm-ipaddr.js-1.9.1.tgz"
	"node_modules/is-fullwidth-code-point|openclaw-bin-npm-is-fullwidth-code-point-3.0.0.tgz"
	"node_modules/is-promise|openclaw-bin-npm-is-promise-4.0.0.tgz"
	"node_modules/isarray|openclaw-bin-npm-isarray-1.0.0.tgz"
	"node_modules/isexe|openclaw-bin-npm-isexe-2.0.0.tgz"
	"node_modules/jiti|openclaw-bin-npm-jiti-2.7.0.tgz"
	"node_modules/jose|openclaw-bin-npm-jose-6.2.3.tgz"
	"node_modules/json-bigint|openclaw-bin-npm-json-bigint-1.0.0.tgz"
	"node_modules/json-schema-to-ts|openclaw-bin-npm-json-schema-to-ts-3.1.1.tgz"
	"node_modules/json-schema-traverse|openclaw-bin-npm-json-schema-traverse-1.0.0.tgz"
	"node_modules/json-schema-typed|openclaw-bin-npm-json-schema-typed-8.0.2.tgz"
	"node_modules/json5|openclaw-bin-npm-json5-2.2.3.tgz"
	"node_modules/jszip|openclaw-bin-npm-jszip-3.10.1.tgz"
	"node_modules/jwa|openclaw-bin-npm-jwa-2.0.1.tgz"
	"node_modules/jws|openclaw-bin-npm-jws-4.0.1.tgz"
	"node_modules/kysely|openclaw-bin-npm-kysely-0.29.2.tgz"
	"node_modules/lie|openclaw-bin-npm-lie-3.3.0.tgz"
	"node_modules/linkedom|openclaw-bin-npm-linkedom-0.18.12.tgz"
	"node_modules/locate-path|openclaw-bin-npm-locate-path-5.0.0.tgz"
	"node_modules/long|openclaw-bin-npm-long-5.3.2.tgz"
	"node_modules/lru-cache|openclaw-bin-npm-lru-cache-11.5.1.tgz"
	"node_modules/marked|openclaw-bin-npm-marked-18.0.5.tgz"
	"node_modules/math-intrinsics|openclaw-bin-npm-math-intrinsics-1.1.0.tgz"
	"node_modules/media-typer|openclaw-bin-npm-media-typer-1.1.0.tgz"
	"node_modules/merge-descriptors|openclaw-bin-npm-merge-descriptors-2.0.0.tgz"
	"node_modules/mime-db|openclaw-bin-npm-mime-db-1.54.0.tgz"
	"node_modules/mime-types|openclaw-bin-npm-mime-types-3.0.2.tgz"
	"node_modules/minimalistic-assert|openclaw-bin-npm-minimalistic-assert-1.0.1.tgz"
	"node_modules/minimatch|openclaw-bin-npm-minimatch-10.2.5.tgz"
	"node_modules/minimist|openclaw-bin-npm-minimist-1.2.8.tgz"
	"node_modules/minipass|openclaw-bin-npm-minipass-7.1.3.tgz"
	"node_modules/minizlib|openclaw-bin-npm-minizlib-3.1.0.tgz"
	"node_modules/ms|openclaw-bin-npm-ms-2.1.3.tgz"
	"node_modules/negotiator|openclaw-bin-npm-negotiator-1.0.0.tgz"
	"node_modules/node-addon-api|openclaw-bin-npm-node-addon-api-8.9.0.tgz"
	"node_modules/node-domexception|openclaw-bin-npm-node-domexception-1.0.28.tgz"
	"node_modules/node-edge-tts|openclaw-bin-npm-node-edge-tts-1.2.10.tgz"
	"node_modules/node-fetch|openclaw-bin-npm-node-fetch-3.3.2.tgz"
	"node_modules/node-gyp-build|openclaw-bin-npm-node-gyp-build-4.8.4.tgz"
	"node_modules/nth-check|openclaw-bin-npm-nth-check-2.1.1.tgz"
	"node_modules/object-assign|openclaw-bin-npm-object-assign-4.1.1.tgz"
	"node_modules/object-inspect|openclaw-bin-npm-object-inspect-1.13.4.tgz"
	"node_modules/on-finished|openclaw-bin-npm-on-finished-2.4.1.tgz"
	"node_modules/once|openclaw-bin-npm-once-1.4.0.tgz"
	"node_modules/openai|openclaw-bin-npm-openai-6.45.0.tgz"
	"node_modules/p-limit|openclaw-bin-npm-p-limit-2.3.0.tgz"
	"node_modules/p-locate|openclaw-bin-npm-p-locate-4.1.0.tgz"
	"node_modules/p-retry|openclaw-bin-npm-p-retry-4.6.2.tgz"
	"node_modules/p-try|openclaw-bin-npm-p-try-2.2.0.tgz"
	"node_modules/pako|openclaw-bin-npm-pako-1.0.11.tgz"
	"node_modules/parseurl|openclaw-bin-npm-parseurl-1.3.3.tgz"
	"node_modules/partial-json|openclaw-bin-npm-partial-json-0.1.7.tgz"
	"node_modules/path-exists|openclaw-bin-npm-path-exists-4.0.0.tgz"
	"node_modules/path-key|openclaw-bin-npm-path-key-3.1.1.tgz"
	"node_modules/path-scurry|openclaw-bin-npm-path-scurry-2.0.2.tgz"
	"node_modules/path-to-regexp|openclaw-bin-npm-path-to-regexp-8.4.0.tgz"
	"node_modules/pkce-challenge|openclaw-bin-npm-pkce-challenge-5.0.1.tgz"
	"node_modules/playwright-core|openclaw-bin-npm-playwright-core-1.61.1.tgz"
	"node_modules/pngjs|openclaw-bin-npm-pngjs-5.0.0.tgz"
	"node_modules/process-nextick-args|openclaw-bin-npm-process-nextick-args-2.0.1.tgz"
	"node_modules/proper-lockfile|openclaw-bin-npm-proper-lockfile-4.1.2.tgz"
	"node_modules/proper-lockfile/node_modules/retry|openclaw-bin-npm-retry-0.12.0.tgz"
	"node_modules/protobufjs|openclaw-bin-npm-protobufjs-7.6.3.tgz"
	"node_modules/proxy-addr|openclaw-bin-npm-proxy-addr-2.0.7.tgz"
	"node_modules/qrcode|openclaw-bin-npm-qrcode-1.5.4.tgz"
	"node_modules/qrcode/node_modules/cliui|openclaw-bin-npm-cliui-6.0.0.tgz"
	"node_modules/qrcode/node_modules/wrap-ansi|openclaw-bin-npm-wrap-ansi-6.2.0.tgz"
	"node_modules/qrcode/node_modules/y18n|openclaw-bin-npm-y18n-4.0.3.tgz"
	"node_modules/qrcode/node_modules/yargs|openclaw-bin-npm-yargs-15.4.1.tgz"
	"node_modules/qrcode/node_modules/yargs-parser|openclaw-bin-npm-yargs-parser-18.1.3.tgz"
	"node_modules/qs|openclaw-bin-npm-qs-6.15.2.tgz"
	"node_modules/quickjs-wasi|openclaw-bin-npm-quickjs-wasi-3.0.2.tgz"
	"node_modules/range-parser|openclaw-bin-npm-range-parser-1.3.0.tgz"
	"node_modules/rastermill|openclaw-bin-npm-rastermill-0.3.1.tgz"
	"node_modules/raw-body|openclaw-bin-npm-raw-body-3.0.2.tgz"
	"node_modules/readable-stream|openclaw-bin-npm-readable-stream-2.3.8.tgz"
	"node_modules/readable-stream/node_modules/safe-buffer|openclaw-bin-npm-safe-buffer-5.1.2.tgz"
	"node_modules/readdirp|openclaw-bin-npm-readdirp-5.0.0.tgz"
	"node_modules/require-directory|openclaw-bin-npm-require-directory-2.1.1.tgz"
	"node_modules/require-from-string|openclaw-bin-npm-require-from-string-2.0.2.tgz"
	"node_modules/require-main-filename|openclaw-bin-npm-require-main-filename-2.0.0.tgz"
	"node_modules/retry|openclaw-bin-npm-retry-0.13.1.tgz"
	"node_modules/router|openclaw-bin-npm-router-2.2.0.tgz"
	"node_modules/safe-buffer|openclaw-bin-npm-safe-buffer-5.2.1.tgz"
	"node_modules/safer-buffer|openclaw-bin-npm-safer-buffer-2.1.2.tgz"
	"node_modules/send|openclaw-bin-npm-send-1.2.1.tgz"
	"node_modules/serve-static|openclaw-bin-npm-serve-static-2.2.1.tgz"
	"node_modules/set-blocking|openclaw-bin-npm-set-blocking-2.0.0.tgz"
	"node_modules/setimmediate|openclaw-bin-npm-setimmediate-1.0.5.tgz"
	"node_modules/setprototypeof|openclaw-bin-npm-setprototypeof-1.2.0.tgz"
	"node_modules/shebang-command|openclaw-bin-npm-shebang-command-2.0.0.tgz"
	"node_modules/shebang-regex|openclaw-bin-npm-shebang-regex-3.0.0.tgz"
	"node_modules/side-channel|openclaw-bin-npm-side-channel-1.1.1.tgz"
	"node_modules/side-channel-list|openclaw-bin-npm-side-channel-list-1.0.1.tgz"
	"node_modules/side-channel-map|openclaw-bin-npm-side-channel-map-1.0.1.tgz"
	"node_modules/side-channel-weakmap|openclaw-bin-npm-side-channel-weakmap-1.0.2.tgz"
	"node_modules/signal-exit|openclaw-bin-npm-signal-exit-3.0.7.tgz"
	"node_modules/sisteransi|openclaw-bin-npm-sisteransi-1.0.5.tgz"
	"node_modules/source-map|openclaw-bin-npm-source-map-0.6.1.tgz"
	"node_modules/source-map-support|openclaw-bin-npm-source-map-support-0.5.21.tgz"
	"node_modules/sqlite-vec|openclaw-bin-npm-sqlite-vec-0.1.9.tgz"
	"node_modules/standardwebhooks|openclaw-bin-npm-standardwebhooks-1.0.0.tgz"
	"node_modules/statuses|openclaw-bin-npm-statuses-2.0.2.tgz"
	"node_modules/string-width|openclaw-bin-npm-string-width-4.2.3.tgz"
	"node_modules/string_decoder|openclaw-bin-npm-string_decoder-1.1.1.tgz"
	"node_modules/string_decoder/node_modules/safe-buffer|openclaw-bin-npm-safe-buffer-5.1.2.tgz"
	"node_modules/strip-ansi|openclaw-bin-npm-strip-ansi-6.0.1.tgz"
	"node_modules/strtok3|openclaw-bin-npm-strtok3-10.3.5.tgz"
	"node_modules/tar|openclaw-bin-npm-tar-7.5.19.tgz"
	"node_modules/toidentifier|openclaw-bin-npm-toidentifier-1.0.1.tgz"
	"node_modules/token-types|openclaw-bin-npm-token-types-6.1.2.tgz"
	"node_modules/tr46|openclaw-bin-npm-tr46-0.0.3.tgz"
	"node_modules/tree-sitter-bash|openclaw-bin-npm-tree-sitter-bash-0.25.1.tgz"
	"node_modules/ts-algebra|openclaw-bin-npm-ts-algebra-2.0.0.tgz"
	"node_modules/tslib|openclaw-bin-npm-tslib-2.8.1.tgz"
	"node_modules/tslog|openclaw-bin-npm-tslog-4.10.2.tgz"
	"node_modules/type-is|openclaw-bin-npm-type-is-2.1.0.tgz"
	"node_modules/type-is/node_modules/content-type|openclaw-bin-npm-content-type-2.0.0.tgz"
	"node_modules/typebox|openclaw-bin-npm-typebox-1.3.3.tgz"
	"node_modules/typescript|openclaw-bin-npm-typescript-6.0.3.tgz"
	"node_modules/uhyphen|openclaw-bin-npm-uhyphen-0.2.0.tgz"
	"node_modules/uint8array-extras|openclaw-bin-npm-uint8array-extras-1.5.0.tgz"
	"node_modules/undici|openclaw-bin-npm-undici-8.5.0.tgz"
	"node_modules/undici-types|openclaw-bin-npm-undici-types-8.3.0.tgz"
	"node_modules/unpipe|openclaw-bin-npm-unpipe-1.0.0.tgz"
	"node_modules/util-deprecate|openclaw-bin-npm-util-deprecate-1.0.2.tgz"
	"node_modules/vary|openclaw-bin-npm-vary-1.1.2.tgz"
	"node_modules/web-push|openclaw-bin-npm-web-push-3.6.7.tgz"
	"node_modules/web-streams-polyfill|openclaw-bin-npm-web-streams-polyfill-3.3.3.tgz"
	"node_modules/web-tree-sitter|openclaw-bin-npm-web-tree-sitter-0.26.10.tgz"
	"node_modules/webidl-conversions|openclaw-bin-npm-webidl-conversions-3.0.1.tgz"
	"node_modules/whatwg-url|openclaw-bin-npm-whatwg-url-5.0.0.tgz"
	"node_modules/which|openclaw-bin-npm-which-2.0.2.tgz"
	"node_modules/which-module|openclaw-bin-npm-which-module-2.0.1.tgz"
	"node_modules/wrap-ansi|openclaw-bin-npm-wrap-ansi-7.0.0.tgz"
	"node_modules/wrappy|openclaw-bin-npm-wrappy-1.0.2.tgz"
	"node_modules/ws|openclaw-bin-npm-ws-8.21.0.tgz"
	"node_modules/y18n|openclaw-bin-npm-y18n-5.0.8.tgz"
	"node_modules/yallist|openclaw-bin-npm-yallist-5.0.0.tgz"
	"node_modules/yaml|openclaw-bin-npm-yaml-2.9.0.tgz"
	"node_modules/yargs|openclaw-bin-npm-yargs-17.7.3.tgz"
	"node_modules/yargs-parser|openclaw-bin-npm-yargs-parser-21.1.1.tgz"
	"node_modules/zod|openclaw-bin-npm-zod-4.4.3.tgz"
	"node_modules/zod-to-json-schema|openclaw-bin-npm-zod-to-json-schema-3.25.2.tgz"
)

OPENCLAW_NPM_PATHS_AMD64=(
	"node_modules/@lydell/node-pty-linux-x64|openclaw-bin-npm-lydell-node-pty-linux-x64-1.2.0-beta.12.tgz"
	"node_modules/sqlite-vec-linux-x64|openclaw-bin-npm-sqlite-vec-linux-x64-0.1.9.tgz"
)

OPENCLAW_NPM_PATHS_ARM64=(
	"node_modules/@lydell/node-pty-linux-arm64|openclaw-bin-npm-lydell-node-pty-linux-arm64-1.2.0-beta.12.tgz"
	"node_modules/sqlite-vec-linux-arm64|openclaw-bin-npm-sqlite-vec-linux-arm64-0.1.9.tgz"
)

SRC_URI="
	https://registry.npmjs.org/openclaw/-/openclaw-${MY_PV}.tgz -> ${P}.tgz
	${OPENCLAW_NPM_SRC_URI[*]}
	amd64? ( ${OPENCLAW_NPM_SRC_URI_AMD64[*]} )
	arm64? ( ${OPENCLAW_NPM_SRC_URI_ARM64[*]} )
"
S="${WORKDIR}/package"

# openclaw itself is MIT. The vendored npm dependency closure's licenses
# (deduplicated from npm-shrinkwrap.json's per-package "license" fields):
# Apache-2.0, (BSD-3-Clause as) BSD, BSD-2-Clause (as BSD-2),
# BlueOak-1.0.0, ISC, MPL-2.0, 0BSD, Unlicense, (MIT AND Zlib) (as MIT +
# ZLIB), (MIT OR GPL-3.0-or-later), and (MIT OR Apache, i.e. Apache-2.0).
LICENSE="
	MIT
	Apache-2.0 BSD BSD-2 BlueOak-1.0.0 ISC MPL-2.0 0BSD Unlicense ZLIB
	|| ( MIT GPL-3+ )
	|| ( MIT Apache-2.0 )
"
SLOT="0"
KEYWORDS="~amd64 ~arm64"

# ">=22.22.3 <23 || >=24.15.0 <25 || >=25.9.0" per package.json "engines".
RDEPEND="
	|| (
		( >=net-libs/nodejs-22.22.3 <net-libs/nodejs-23 )
		( >=net-libs/nodejs-24.15.0 <net-libs/nodejs-25 )
		>=net-libs/nodejs-25.9.0
	)
"
# Build-time only: _openclaw_safe_extract (below) needs a Python interpreter
# for its tarfile-based safe extraction; nothing installed by this package
# imports or runs Python at runtime.
BDEPEND="${PYTHON_DEPS}"

MY_PN="openclaw"

pkg_setup() {
	[[ ${OPENCLAW_NPM_DEPS_VERSION} == ${PV} ]] ||
		die "OPENCLAW_NPM_DEPS_VERSION (${OPENCLAW_NPM_DEPS_VERSION}) does not match PV (${PV}); the pasted-in dependency arrays were generated for a different version"

	# python-any-r1.eclass EXPORT_FUNCTIONS pkg_setup; defining our own
	# pkg_setup (for the version check above) shadows that unless called
	# explicitly. Populates ${EPYTHON}, used by _openclaw_safe_extract.
	python-any-r1_pkg_setup
}

# A handful of published npm tarballs in this dependency closure (observed
# with pngjs-5.0.0) record directory entries with a broken mode (no
# execute bit for anyone at all -- likely an artifact of whatever tool
# originally packed them), which leaves the extracted directory
# untraversable: archived-mode & ~umask can never add back a missing
# execute bit. GNU tar applies that broken mode unconditionally --
# neither --no-same-permissions nor --no-overwrite-dir prevents it -- and
# aborts extraction partway through with "Cannot open: Permission denied"
# on every entry still to come in that same archive. Python's tarfile
# lets each member's mode be fixed up before extraction instead, so every
# tarball in this ebuild is extracted this way (not just the one known to
# need it, in case a future version bump reveals another affected
# package) rather than plain `tar`/unpack. OR-ing in rather than
# replacing the mode preserves genuinely-set executable bits (e.g.
# openclaw.mjs's).
#
# These are third-party tarballs pulled from the public npm registry, not
# fully trusted input, so extraction also passes tarfile.data_filter (the
# PEP 706 safe-extraction filter: rejects absolute paths, "../" traversal,
# symlinks/hardlinks/device files that would land outside the destination,
# and strips setuid/setgid/sticky bits) in addition to -- not instead of
# -- the manual mode fixup above; verified empirically (see the commit
# introducing this) that combining both on all 300 currently-vendored
# tarballs, including the broken-permission pngjs one, extracts cleanly
# with no rejections.
_openclaw_safe_extract() {
	local archive=$1 dest=$2
	"${EPYTHON}" -c '
import sys, tarfile
with tarfile.open(sys.argv[1]) as t:
	members = t.getmembers()
	for m in members:
		m.mode |= 0o700 if m.isdir() else 0o600
	t.extractall(sys.argv[2], members=members, filter=tarfile.data_filter)
' "${archive}" "${dest}" || die "failed to extract ${archive}"
}

# Extracts one vendored npm dependency tarball (whose top-level directory
# is always the literal name "package", same as ${P}.tgz's own) directly
# into node_modules/<pkgpath> -- no `npm install` invocation, so no
# network access is needed at any build phase. Mirrors
# app-backup/restic-browser's src_prepare loop.
_openclaw_vendor_npm_path() {
	local entry=$1 pkgpath filename tmpdir rootdir
	pkgpath=${entry%%|*}
	filename=${entry##*|}
	tmpdir=$(mktemp -d --tmpdir="${T}") || die
	_openclaw_safe_extract "${DISTDIR}/${filename}" "${tmpdir}"
	rootdir=$(find "${tmpdir}" -mindepth 1 -maxdepth 1 -type d)
	[[ -n ${rootdir} ]] || die "no top-level directory found in ${filename}"
	mkdir -p "${S}/$(dirname "${pkgpath}")" || die
	mv "${rootdir}" "${S}/${pkgpath}" || die
	rm -rf "${tmpdir}" || die
}

src_unpack() {
	_openclaw_safe_extract "${DISTDIR}/${P}.tgz" "${WORKDIR}"
}

src_prepare() {
	default

	mkdir "${S}/node_modules" || die

	local entry
	for entry in "${OPENCLAW_NPM_PATHS[@]}"; do
		_openclaw_vendor_npm_path "${entry}"
	done

	local node_arch arch_paths=()
	case ${ARCH} in
		amd64) node_arch="x64"; arch_paths=( "${OPENCLAW_NPM_PATHS_AMD64[@]}" ) ;;
		arm64) node_arch="arm64"; arch_paths=( "${OPENCLAW_NPM_PATHS_ARM64[@]}" ) ;;
		*) die "unsupported ARCH: ${ARCH}" ;;
	esac
	local arch_entry
	for arch_entry in "${arch_paths[@]}"; do
		_openclaw_vendor_npm_path "${arch_entry}"
	done

	# Unlike @lydell/node-pty/sqlite-vec (one npm package per platform,
	# already handled above by only ever vendoring the matching variant),
	# tree-sitter-bash bundles prebuilt native addons for every platform
	# inside a single npm package. Strip the ones that can never run here
	# so the image doesn't ship dead-arch ELF objects (which also trips a
	# spurious QA soname-resolution warning on the foreign-arch .node).
	local tsb="${S}/node_modules/tree-sitter-bash/prebuilds" keep="linux-${node_arch}" d
	if [[ -d ${tsb} ]]; then
		for d in "${tsb}"/*/; do
			d=${d%/}
			[[ $(basename "${d}") == "${keep}" ]] || rm -rf "${d}" || die
		done
	fi
}

src_install() {
	local installdir="/usr/lib/node_modules/${MY_PN}"

	insinto "${installdir}"
	doins -r dist skills docs src patches node_modules
	doins package.json npm-shrinkwrap.json pnpm-workspace.yaml \
		LICENSE THIRD_PARTY_NOTICES.md

	exeinto "${installdir}"
	doexe openclaw.mjs

	dosym -r "${installdir}/openclaw.mjs" /usr/bin/openclaw

	dodoc "${FILESDIR}/${P}-third-party-licenses.txt"

	einstalldocs
}
