#!/sbin/openrc-run
# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

FILEBEAT_USER="${FILEBEAT_USER:-root}"
FILEBEAT_GROUP="${FILEBEAT_GROUP:-root}"
FILEBEAT_CONFIG="${FILEBEAT_CONFIG:-/etc/filebeat/filebeat.yml}"
FILEBEAT_DATADIR="${FILEBEAT_DATADIR:-/var/lib/filebeat}"
FILEBEAT_LOGDIR="${FILEBEAT_LOGDIR:-/var/log/filebeat}"
FILEBEAT_OPTS="${FILEBEAT_OPTS:-}"

command="/usr/bin/filebeat"
command_args="--path.home /usr/share/filebeat
	--path.config ${FILEBEAT_CONFIG%/*}
	--path.data ${FILEBEAT_DATADIR}
	--path.logs ${FILEBEAT_LOGDIR}
	-c ${FILEBEAT_CONFIG##*/} ${FILEBEAT_OPTS}"
command_background="true"
command_user="${FILEBEAT_USER}:${FILEBEAT_GROUP}"
pidfile="/run/filebeat.pid"
retry="TERM/30/KILL/5"
start_stop_daemon_args="--chdir /usr/share/filebeat"

extra_commands="checkconfig"

depend() {
	need net
	after elasticsearch
}

checkconfig() {
	if [ ! -f "${FILEBEAT_CONFIG}" ]; then
		eerror "Configuration file ${FILEBEAT_CONFIG} does not exist"
		return 1
	fi

	ebegin "Checking Filebeat configuration"
	"${command}" ${command_args} test config
	eend $?
}

start_pre() {
	checkpath -d -o "${FILEBEAT_USER}:${FILEBEAT_GROUP}" -m 0750 \
		"${FILEBEAT_DATADIR}" "${FILEBEAT_LOGDIR}"
	checkconfig
}
